In [1]:
import numpy as np
import pandas as pd

# Plantilla

Es necesario ajustar las definiciones, las fuentes de los datos y posiblemente definiciones si la ENEMDU tiene una dimensión geográfica y temporal al mismo tiempo

Ahora hay bases por mes, entonces calculamos para cada mes

In [3]:
data1 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m3\data_orig\Stata\enero2008_per.dta", convert_categoricals=False) # para bases de stata
data2 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m3\data_orig\Stata\febrero2008_per.dta", convert_categoricals=False) # para bases de stata
data3 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m3\data_orig\Stata\marzo2008_per.dta", convert_categoricals=False) # para bases de stata

data4 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m6\data_orig\Stata\abril2008_per.dta", convert_categoricals=False) # para bases de stata
data5 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m6\data_orig\Stata\mayo2008_per.dta", convert_categoricals=False) # para bases de stata
data6 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m6\data_orig\Stata\junio2008_per.dta", convert_categoricals=False) # para bases de stata

data7 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m9\data_orig\Stata\julio2008_per.dta", convert_categoricals=False) # para bases de stata
data8 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m9\data_orig\Stata\agosto2008_per.dta", convert_categoricals=False) # para bases de stata
data9 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m9\data_orig\Stata\septiembre2008_per.dta", convert_categoricals=False) # para bases de stata

data10 = pd.read_spss(r"Z:\survey\ECU\ENEMDU\2008\m12\data_orig\Spss\octubre1008_per.sav", convert_categoricals=False) # para bases de stata
data11 = pd.read_spss(r"Z:\survey\ECU\ENEMDU\2008\m12\data_orig\Spss\noviembre2008_per.sav", convert_categoricals=False) # para bases de stata
data12 = pd.read_spss(r"Z:\survey\ECU\ENEMDU\2008\m12\data_orig\Spss\diciembre2008_per.sav", convert_categoricals=False) # para bases de stata

######################
#data1 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m3/data_orig/Stata/enero2008_per.dta", convert_categoricals=False) # para bases de stata
#data2 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m3/data_orig/Stata/febrero2008_per.dta", convert_categoricals=False) # para bases de stata
#data3 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m3/data_orig/Stata/marzo2008_per.dta", convert_categoricals=False) # para bases de stata

#data4 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m6/data_orig/Stata/abril2008_per.dta", convert_categoricals=False) # para bases de stata
#data5 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m6/data_orig/Stata/mayo2008_per.dta", convert_categoricals=False) # para bases de stata
#data6 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m6/data_orig/Stata/junio2008_per.dta", convert_categoricals=False) # para bases de stata

#data7 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m9/data_orig/Stata/julio2008_per.dta", convert_categoricals=False) # para bases de stata
#data8 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m9/data_orig/Stata/agosto2008_per.dta", convert_categoricals=False) # para bases de stata
#data9 = pd.read_stata(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m9/data_orig/Stata/septiembre2008_per.dta", convert_categoricals=False) # para bases de stata

#data10 = pd.read_spss(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m12/data_orig/Spss/octubre1008_per.sav", convert_categoricals=False) # para bases de stata
#data11 = pd.read_spss(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m12/data_orig/Spss/noviembre2008_per.sav", convert_categoricals=False) # para bases de stata
#data12 = pd.read_spss(r"/home/edu/Dropbox/datos/ECU/ECU/ENEMDU/2008/m12/data_orig/Spss/diciembre2008_per.sav", convert_categoricals=False) # para bases de stata

## Revisar los datos

| enero   | febrero | marzo   | abril   | mayo    | junio   | julio   | agosto  | septiembre | octubre | noviembre | diciembre |
|---------|---------|---------|---------|---------|---------|---------|---------|------------|---------|-----------|-----------|
| area    | area    | area    | area    | area    | area    | area    | area    | area       | area    | area      | area      |
| ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad     | ciudad  | ciudad    | ciudad    |
| zona    | zona    | zona    | zona    | zona    | zona    | zona    | zona    | zona       | zona    | zona      | zona      |
| sector  | sector  | sector  | sector  | sector  | sector  | sector  | sector  | sector     | sector  | sector    | sector    |
| panelm  | panelm  | panelm  | panelm  | panelm  | panelm  | panelm  | panelm  | panelm     | panelm  | panelm    | panelm    |
| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda   | vivienda| vivienda  | vivienda  |
| hogar   | hogar   | hogar   | hogar   | hogar   | hogar   | hogar   | hogar   | hogar      | hogar   | hogar     | hogar     |
| p02     | p02     | p02     | p02     | p02     | p02     | p02     | p02     | p02        | p02     | p02       | p02       |
| p03     | p03     | p03     | p03     | p03     | p03     | p03     | p03     | p03        | p03     | p03       | p03       |
| p66     | p66     | p66     | p66     | p66     | p66     | p66     | p66     | p66        | p66     | p66       | p66       |
| fexp    | fexp    | fexp    | fexp    | fexp    | fexp    | fexp    | fexp    | fexp       | fexp    | fexp      | fexp      |
| p20     | p20     | p20     | p20     | p20     | p20     | p20     | p20     | p20        | p20     | p20       | p20       |

En esta encuesta tenemos una base para cada mes, esto cambia la lógica que habíamos tenido hasta ahora así que de aquí en adelante cambiamos algo del código, mantenemos de acuerdo a las etiquetas de las variables p66 como la variable de ingreso laboral monetario de la actividad principal asalariada para mantener la concordancia con el resto de los años.

Elegimos hacer los cálculos en las bases mensuales para poder usar la representatividad mensual, con un promedio simple debería bastar para tener el resultado del trimestre

Ahora usamos p20 que pregunta si trabajo la semana pasada, si se cumple vamos a asumir que trabajo durante todo el mes, ahora en adelante capturaremos incluso de mejor forma el mercado laboral, mantenemos la idea de que si el individuo trabajo recibe su ingreso laboral reportado.

In [4]:
columnas = ['area', 'ciudad', 'zona', 'sector', 'panelm',
            'vivienda', 'hogar', 'p02', 'p03', 'p66', 'p20',
            'fexp']

In [5]:
columnas_upper = [x.upper() for x in columnas]

Filtramos solo las columnas de interés para alivar el peso en la memoria

In [6]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base = base[columnas]

for base in [data10, data11, data12]:
    base = base[columnas_upper]

Creamos una variable de ingreso laboral que es igual al ingreso por asalariado y limpiamos según los valores de ingrl, para mantener ambas variables para cada base consistente

In [7]:
data1['p66'] = pd.to_numeric(data1['p66'], errors='coerce')
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x > 6000 else x)
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x < 0 else x)

data2['p66'] = pd.to_numeric(data2['p66'], errors='coerce')
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x > 6500 else x)
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x < 0 else x)

data3['p66'] = pd.to_numeric(data3['p66'], errors='coerce')
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x > 6800 else x)
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x < 0 else x)

data4['p66'] = pd.to_numeric(data4['p66'], errors='coerce')
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x > 3800 else x)
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x < 0 else x)

data5['p66'] = pd.to_numeric(data5['p66'], errors='coerce')
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x > 6000 else x)
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x < 0 else x)

data6['p66'] = pd.to_numeric(data6['p66'], errors='coerce')
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x > 7000 else x)
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x < 0 else x)

data7['p66'] = pd.to_numeric(data7['p66'], errors='coerce')
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x > 7000 else x)
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x < 0 else x)

data8['p66'] = pd.to_numeric(data8['p66'], errors='coerce')
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x > 8000 else x)
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x < 0 else x)

data9['p66'] = pd.to_numeric(data9['p66'], errors='coerce')
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x > 7000 else x)
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x < 0 else x)

data10['P66'] = pd.to_numeric(data10['P66'], errors='coerce')
data10['P66'] = data10['P66'].apply(lambda x: np.nan if x > 4500 else x)
data10['P66'] = data10['P66'].apply(lambda x: np.nan if x < 0 else x)

data11['P66'] = pd.to_numeric(data11['P66'], errors='coerce')
data11['P66'] = data11['P66'].apply(lambda x: np.nan if x > 4000 else x)
data11['P66'] = data11['P66'].apply(lambda x: np.nan if x < 0 else x)

data12['P66'] = pd.to_numeric(data12['P66'], errors='coerce')
data12['P66'] = data12['P66'].apply(lambda x: np.nan if x > 7000 else x)
data12['P66'] = data12['P66'].apply(lambda x: np.nan if x < 0 else x)

In [8]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['ingr'] = base['p66']

for base in [data10, data11, data12]:
    base['ingr'] = base['P66']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']

Ingreso mensual asumiendo que las personas reciben el mismo valor reportado en 'ingr' siempre que reportan estar ocupados la semana pasada, de acuerdo a la variable 'trabajo'

In [9]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['ingr'] = base.apply(lambda x: x['ingr'] if x['p20'] == 1 else np.nan, axis=1)

for base in [data10, data11, data12]:
    base['ingr'] = base.apply(lambda x: x['ingr'] if x['P20'] == 1 else np.nan, axis=1)

## Deflactamos y transformamos el ingreso

Esto deja todo en dólares constantes de 2014

In [10]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 2008]
datos_base = data_externa[data_externa['Año'] == 2014]

Diccionarios de ipc

In [11]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_base.iterrows()
     }

### Creamos identificadores para las ciudades siguiendo los códigos del INEC y para los trimestres

In [13]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    print(base['ciudad'][0])
    fac = base['ciudad'].apply(lambda x: len(str(x))).min()
    print(fac)

10150
5
10150
5
10150
5
10150
5
10150
5
10150
5
10150
5
10150
5
10150
5

In [14]:
# Corregimos los códigos para usarlos cómo texto
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['ciudad'] = base['ciudad'].apply(str)
    base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == fac else x)
    base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

for base in [data10, data11, data12]:
    base['ciudad'] = base['CIUDAD'].apply(str)
    base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == fac else x)
    base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4038648594.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

Diccionario ciudades disponibles

In [15]:
parroquia_dict = {
    '0101': 'Cuenca',
    '0901': 'Guayaquil',
    '0801': 'Esmeraldas',
    '0701': 'Machala',
    '1308': 'Manta',
    '1701': 'Quito',
    '1101': 'Loja',
    '1801': 'Ambato'
}

def get_parroquia(codigo):
    if codigo in parroquia_dict:
        return parroquia_dict[codigo]
    elif codigo[:2] in ['01', '02', '03', '04', '05', '06', '10', '11', '17', '18']:
        return 'Sierra'
    elif codigo[:2] in ['07', '08', '09', '12', '13', '23', '24']:
        return 'Costa'
    else:
        return 'Nacional'

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)

In [16]:
data5['ciudad_asignada'].value_counts()

ciudad_asignada
Guayaquil    4381
Quito        3116
Cuenca       2488
Machala      2413
Ambato       2176
Name: count, dtype: int64

### Asignamos el ipc correspondiente según ciudad correspondiente

$\begin{equation}
    ingr_{USD-base-2014}^{i} = ingr_{dólares}^{i}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Desde 2000 en adelante ya no es necesario utilizar el tipo de cambio debido al cambio de moneda

In [17]:
# Función que asigna valores correspondientes
def asigna_ipc(fila, trimestre):
    return ipc_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila, trimestre):
    return ipc_base_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

In [18]:
data1['ipc'] = data1.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data1['ipc_base'] = data1.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data2['ipc'] = data2.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data2['ipc_base'] = data2.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data3['ipc'] = data3.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data3['ipc_base'] = data3.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data4['ipc'] = data4.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data4['ipc_base'] = data4.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data5['ipc'] = data5.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data5['ipc_base'] = data5.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data6['ipc'] = data6.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data6['ipc_base'] = data6.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data7['ipc'] = data7.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data7['ipc_base'] = data7.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data8['ipc'] = data8.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data8['ipc_base'] = data8.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data9['ipc'] = data9.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data9['ipc_base'] = data9.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data10['ipc'] = data10.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data10['ipc_base'] = data10.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data11['ipc'] = data11.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data11['ipc_base'] = data11.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data12['ipc'] = data12.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data12['ipc_base'] = data12.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data1['ipc'] = data1.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data1['ipc_base'] = data1.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data2['ipc'] = data2.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data2['ipc_base'] = data2.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data3['ipc'] = data3.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data3['ipc_base'] = data3.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data4['ipc'] = data4.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data4['ipc_base'] = data4.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data5['ipc'] = data5.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data5['ipc_base'] = data5.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data6['ipc'] = data6.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data6['ipc_base'] = data6.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data7['ipc'] = data7.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data7['ipc_base'] = data7.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data8['ipc'] = data8.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data8['ipc_base'] = data8.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data9['ipc'] = data9.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\2802951969.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data9['ipc_base'] = data9.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

In [19]:
# Calculamos el deflactor
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['def'] = (base['ipc_base'] / base['ipc'])

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])

In [20]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_r'] = base['ingr'] * base['def']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']

In [21]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_r'].mean())

517.7684129910175
390.54343158166904
386.63089421668343
386.53164659470366
417.44508332661604
349.0727982126179
402.2177189011358
397.18042643660755
393.24889164380386
414.3335153804606
413.64455590646867
324.613965434477

## Regiones

In [22]:
# Corregimos los códigos para usarlos cómo texto
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ciudad'] = base['ciudad'].apply(str)
    base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == fac else x)

    base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:2])

In [23]:
regiones_dict = {
    'Guayas': '09',
    'Manabí': '13',
    'El Oro': '07',
    'Los Ríos': '12',
    'Pichincha': '17',
    'Azuay': '01',
    'Galápagos': '20',
    'Sierra': ['04', '10', '05', '18', '02', '06', '03', '11'],
    'Costa, Santo Domingo': ['08', '24', '23'],
    'Amazonía': ['14', '15', '16', '19', '21', '22', '90']
}

In [24]:
codigo_region = {}
for region, codes in regiones_dict.items():
    
    if isinstance(codes, list):
        for code in codes:
            codigo_region[code] = region
    
    else:
        codigo_region[codes] = region

# Mapeo de regiones
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['region'] = base['ciudad_2'].map(codigo_region)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1650291667.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['region'] = base['ciudad_2'].map(codigo_region)

In [25]:
data3['region'].value_counts()

region
Guayas                  6466
Pichincha               4735
Sierra                  4541
El Oro                  2893
Azuay                   2624
Amazonía                2005
Manabí                  1440
Los Ríos                 858
Costa, Santo Domingo     599
Name: count, dtype: int64

In [26]:
data6['region'].value_counts()

region
Sierra                  8292
Guayas                  7891
Pichincha               5557
Amazonía                4371
Azuay                   3231
El Oro                  3123
Manabí                  2750
Los Ríos                1672
Costa, Santo Domingo     982
Name: count, dtype: int64

In [27]:
data9['region'].value_counts()

region
Guayas                  6369
Sierra                  4661
Pichincha               4517
El Oro                  3012
Azuay                   2617
Amazonía                2051
Manabí                  1532
Los Ríos                 985
Costa, Santo Domingo     595
Name: count, dtype: int64

In [28]:
data12['region'].value_counts()

region
Sierra       16695
Amazonía     10756
Pichincha     6420
Manabí        5810
Los Ríos      5674
Galápagos     3711
Name: count, dtype: int64

## Calculo ingreso de los hogares

In [29]:
columnas_idef = ['area', 'ciudad', 'zona', 'sector', 'vivienda',
       'hogar']
columnas_idef_upper = [x.upper() for x in columnas_idef]

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)

for base in [data10, data11, data12]:
    base['idef_hogar'] = base[columnas_idef_upper].astype(str).agg(''.join, axis=1)

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['idef_hogar'].nunique())

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)

1215
1220
2136
1238
1280
3211
1273
1333
3791
1256
1217
6162

Si todos los miembros del hogar tienen NA como ingreso, mantener NA, si al menos uno tiene un ingreso sumamos para el ingreso del hogar, así evitamos subestimar el ingreso del hogar si tenemos valores perdidos

In [30]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [31]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)

In [33]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_h'].mean())

1859.121370752483
1435.784448471765
1387.082631612204
1499.7409112081843
1569.146492791128
1252.0044813091854
1559.318838704087
1451.3793939790291
933.0874325680371
1589.47179408485
1617.365984073918
1161.2075055246266

## Sacamos edades negativas y mayores a 100 años

Transformamos las variables de edad a numericas para evitar problemas

In [34]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['edad'] = pd.to_numeric(base['p03'], errors='coerce')

for base in [data10, data11, data12]:
    base['edad'] = pd.to_numeric(base['P03'], errors='coerce')

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')

In [35]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base = base.loc[(base['edad'] >= 0) & (base['edad'] < 100)]

## Ingreso individual descontando cargas familiares

Utilizando la metodología del autor dividimos el ingreso del hogar para la escala $(A_{i}+kC_{i})^{s}$ donde $A_{i}$ es al número de adultos, $C_{i}$ es el número de niños en el hogar $i$. $k$ es el costo en recursos de cada niño y $s$ busca reflejar las restricciones

In [36]:
k = 0.4
s = 0.9

In [37]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    # Si es necesario calcular el número de niños
    base['es_nino'] = base['edad'] < 10 
    base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')

    # Si es necesario calcular el número de adultos
    base['es_adulto'] = base['edad'] > 10
    base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')

In [38]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['escala'] = (base['adultos'] + k * base['ninos']) ** s

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s

In [39]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_t'] = base['ingr_h'] / base['escala']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_24280\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']

In [40]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
        print(base['ingr_t'].mean())

199.71078638244003
151.12813954547306
144.70619825918152
154.4592666187294
168.809501528838
131.3317446861637
165.46187078951402
161.49842453150214
157.80827429697678
167.10923569659198
164.30928908708452
117.15133188940445

## Umbrales de pobreza

Incluimos los índices de pobreza si es posible a nivel regional para luego poder utilizar de mejor forma el factor de expansión

$\begin{equation}
    umbral_{USD-base-2014}^{i} = umbral_{año}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

Diccionario de umbral

In [41]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))
salario_dict = dict(zip(datos_actual['trimestre'], datos_actual['salario básico unificado']))
ano = 2008

## Cálculo del índice de pobreza de Foster, Greer y Thorbecke

Para calcular un ínidce de pobreza se utiliza a Foster, Greer y Thorbecke (1984), ya que satisface algunas caracterísitcas de distribución que son positivas e igual a las enunciadas por Sen, el autor usa el mismo índice.

$\begin{equation}FGT_{\alpha} = \frac{1}{N}\sum_{i=1}^{H}\left(\frac{z-y_{i}}{z}\right)^{\alpha}\end{equation}$

Donde $z$ es el umbral de pobreza, $N$ es el número de personas en la economía, $H$ es el número de pobres (personas debajo de la línea de pobreza) $y_{i}$ es el ingreso de cada individuo. Mientras mayor es el valor de $\alpha$ mayor es el peso de los individuos más pobres, mayor $FGT$ mayor pobreza en la economía.

En este caso los umbrales están anivel nacional, aún así buscamos calcular la pobreza por región y sacar un promedio ponderado por región para la pobreza nacional, con el objetivo de hacerlo más específico

## Calculo del índice de desigualdad de Atkinson

Vamos a calcular el índice de desigualdad de atkinson con un parámetro $\epsilon$ de aversión a la desigualdad y un $\mu$ que es igual a la media de los ingresos individuales, con la siguiente fórmula.

$\begin{equation}A = 1-\frac{1}{\mu}\left(\frac{1}{N}\sum_{i=1}^{N}y^{1-\epsilon}\right)^{1/(1-\epsilon)}\end{equation}$

Donde $y_{i}$ es el ingreso individual y $\mu$ es el ingreso medio

In [42]:
for base in [data10, data11, data12]:
    base.columns = base.columns.str.lower()

In [43]:
resultados_list = []

# Diccionario de dataframes mensuales
data_dict = {
    1: data1, 2: data2, 3: data3, 4: data4, 
    5: data5, 6: data6, 7: data7, 8: data8,
    9: data9, 10: data10, 11: data11, 12: data12
}

# Para cada mes
for mes in range(1, 13):
    col_ingr = f'ingr_t'
    
    # Calcula trimestre (1-4) basado en el mes
    trimestre = (mes - 1) // 3 + 1
    
    umbral = umbral_dict.get(trimestre)
    salario = salario_dict.get(trimestre)
    df_actual = data_dict[mes]
    
    # Agrupa por región
    grouped = df_actual.groupby('region')
    
    for region_name, group in grouped:
        # 1. Filtra datos
        valid = group.dropna(subset=[col_ingr])
        
        if len(valid) == 0:
            continue
            
        # Extrae los vectores 
        ingresos = valid[col_ingr].values
        pesos = valid['fexp'].values
        
        # 2. Calcula indices
        gaps = (umbral - ingresos) / umbral
        gaps = np.clip(gaps, a_min=0, a_max=None)
        
        # 3. Calcula FGT
        total_poblacion = pesos.sum()
        
        # FGT0
        fgt0 = (pesos * (gaps > 0).astype(int)).sum() / total_poblacion
        
        # FGT1
        fgt1 = (pesos * (gaps ** 1)).sum() / total_poblacion
        
        # FGT2
        fgt2 = (pesos * (gaps ** 2)).sum() / total_poblacion
        
        # 4. Calcula Ingreso promedio
        ingreso_promedio = np.average(ingresos, weights=pesos)

        # 5. Desigualdad de Atkinson
        atkinson_resultados = {}
        
        if ingreso_promedio > 0:
            for epsilon in [0.25, 0.5, 0.75]:
                # La suma ponderada de la utilidad
                utility_sum = np.sum((ingresos ** (1 - epsilon)) * pesos)
                
                # promedio de esa utilidad
                utility_mean = utility_sum / total_poblacion
                
                # ingreso equivalente
                y_ede = utility_mean ** (1 / (1 - epsilon))
                
                # índice final
                atkinson_index = 1 - (y_ede / ingreso_promedio)
                atkinson_resultados[f'a{int(epsilon*100)}'] = atkinson_index
        else:
            # Si nadie gana nada, definimos desigualdad como NaN
            atkinson_resultados = {'a25': np.nan, 'a50': np.nan, 'a75': np.nan}

        # 6. Calcula mediana del ingreso
        # Ordena
        sort_idx = np.argsort(ingresos)
        ingreso_ordenado = ingresos[sort_idx]
        pesos_ordenado = pesos[sort_idx]
        cumsum_pesos = np.cumsum(pesos_ordenado)
        cutoff = total_poblacion / 2.0
        mediana = ingreso_ordenado[np.searchsorted(cumsum_pesos, cutoff)]
        
        # 7. Guarda resultados
        resultados_list.append({
            'ano': ano,
            'mes': mes,
            'trimestre': trimestre,
            'region': region_name,
            'fgt0': fgt0,
            'fgt1': fgt1,
            'fgt2': fgt2,
            'a25': atkinson_resultados['a25'],
            'a50': atkinson_resultados['a50'],
            'a75': atkinson_resultados['a75'],
            'ingreso_promedio': ingreso_promedio,
            'ingreso_mediana': mediana + 1 if mediana < 1 else mediana,
            'salario_minimo': salario,
            'kaitz_indice': salario / (mediana + 1 if mediana < 1 else mediana)         
        })

# lista a DataFrame
df_final_regional = pd.DataFrame(resultados_list)
df_final_regional

,ano,mes,trimestre,region,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,ingreso_mediana,salario_minimo,kaitz_indice
0,2008,1,1,Azuay,0.142545,0.064315,0.040705,0.068839,0.140267,0.219550,269.532056,230.932573,200.0,0.866054
1,2008,1,1,El Oro,0.242777,0.091075,0.044368,0.061755,0.119774,0.174473,148.182622,116.957295,200.0,1.710026
2,2008,1,1,Guayas,0.261462,0.103835,0.055838,0.082439,0.158234,0.228068,166.251363,117.363946,200.0,1.704101
3,2008,1,1,Pichincha,0.143824,0.049411,0.026230,0.077837,0.152656,0.224156,262.984446,187.131564,200.0,1.068767
4,2008,1,1,Sierra,0.275730,0.118140,0.067911,0.120356,0.229815,0.328070,232.876226,134.924620,200.0,1.482309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,2008,12,4,Galápagos,0.687361,0.377720,0.253338,0.122535,0.236488,0.351412,84.595760,52.611587,200.0,3.801444
65,2008,12,4,Los Ríos,0.478029,0.175425,0.094372,0.052329,0.103244,0.154180,99.306462,83.134553,200.0,2.405739
66,2008,12,4,Manabí,0.567317,0.239981,0.139286,0.065557,0.129964,0.198010,89.226520,73.264715,200.0,2.729827
67,2008,12,4,Pichincha,0.203132,0.068889,0.035504,0.064883,0.127317,0.189950,187.113678,144.692260,200.0,1.382244
68,2008,12,4,Sierra,0.431638,0.208720,0.133921,0.085354,0.170541,0.261153,122.029817,91.989781,200.0,2.174155

In [44]:
# Agregar por año, trimestre y región
df_trimestral = df_final_regional.groupby(['ano', 'trimestre', 'region']).agg({
    'fgt0': 'mean',
    'fgt1': 'mean',
    'fgt2': 'mean',
    'a25': 'mean',
    'a50': 'mean',
    'a75': 'mean',
    'ingreso_promedio': 'mean',
    'ingreso_mediana': 'mean',
    'salario_minimo': 'mean',
    'kaitz_indice': 'mean'
}).reset_index()

df_trimestral

,ano,trimestre,region,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,ingreso_mediana,salario_minimo,kaitz_indice
0,2008,1,Amazonía,0.271012,0.101021,0.056827,0.061864,0.121920,0.181321,155.472246,129.079500,200.0,1.549433
1,2008,1,Azuay,0.186099,0.071846,0.042012,0.075566,0.148464,0.223584,213.785822,170.146977,200.0,1.243219
2,2008,1,"Costa, Santo Domingo",0.455637,0.210016,0.110111,0.066760,0.133935,0.208122,108.536781,89.705374,200.0,2.229521
3,2008,1,El Oro,0.310334,0.108413,0.054172,0.049476,0.097981,0.147756,125.013304,107.887662,200.0,1.874749
4,2008,1,Guayas,0.307764,0.109490,0.056049,0.070841,0.136510,0.199872,143.632815,107.519837,200.0,1.874926
5,2008,1,Los Ríos,0.451553,0.172585,0.090528,0.052086,0.103011,0.152582,99.310193,81.782751,200.0,2.445503
6,2008,1,Manabí,0.530296,0.200508,0.099944,0.062749,0.122396,0.178840,100.865634,69.181193,200.0,2.890959
7,2008,1,Pichincha,0.160227,0.053636,0.027544,0.069623,0.135925,0.201638,217.227409,163.709342,200.0,1.234018
8,2008,1,Sierra,0.308874,0.135643,0.082393,0.084924,0.169715,0.263940,169.235818,122.138723,200.0,1.646141
9,2008,2,Amazonía,0.506703,0.251842,0.161130,0.086633,0.178514,0.296498,102.395952,76.235112,200.0,2.623463
10,2008,2,Azuay,0.204454,0.075188,0.040770,0.070845,0.137953,0.205181,186.606348,143.369674,200.0,1.482959
11,2008,2,"Costa, Santo Domingo",0.577454,0.266940,0.161987,0.070590,0.141692,0.214496,84.538369,66.229748,200.0,3.019791
12,2008,2,El Oro,0.281987,0.090414,0.045641,0.049338,0.097021,0.144752,126.238357,104.236359,200.0,1.921218
13,2008,2,Guayas,0.328170,0.117010,0.060906,0.068591,0.132173,0.194732,132.176206,103.088919,200.0,1.945894
14,2008,2,Los Ríos,0.415125,0.132741,0.071869,0.054292,0.105497,0.154447,104.117070,84.163511,200.0,2.376327
15,2008,2,Manabí,0.591216,0.287718,0.177095,0.105616,0.202598,0.298954,96.830678,62.519093,200.0,3.199023
16,2008,2,Pichincha,0.168510,0.059294,0.032001,0.062662,0.124106,0.189482,205.620369,163.839924,200.0,1.228729
17,2008,2,Sierra,0.331058,0.147743,0.089257,0.072315,0.144413,0.221677,141.863994,113.793933,200.0,1.884454
18,2008,3,Amazonía,0.329050,0.120270,0.064492,0.070987,0.142312,0.220352,158.543219,120.095960,200.0,1.665335
19,2008,3,Azuay,0.198243,0.081015,0.044588,0.068025,0.133992,0.199337,193.956336,156.108777,200.0,1.284243
20,2008,3,"Costa, Santo Domingo",0.396623,0.140779,0.084804,0.084421,0.166961,0.259039,139.760399,95.173876,200.0,2.101417
21,2008,3,El Oro,0.290178,0.100316,0.048959,0.057497,0.111403,0.163500,135.318681,109.438543,200.0,1.837849
22,2008,3,Guayas,0.275865,0.099696,0.051756,0.066790,0.129360,0.193032,145.518590,112.247521,200.0,1.786015
23,2008,3,Los Ríos,0.454361,0.179383,0.093998,0.071862,0.141237,0.212309,119.574699,86.825602,200.0,2.303468
24,2008,3,Manabí,0.405038,0.200931,0.123441,0.084228,0.166472,0.252781,122.563969,97.476134,200.0,2.051784
25,2008,3,Pichincha,0.162095,0.058596,0.033767,0.066844,0.132454,0.202817,211.329488,162.969821,200.0,1.234235
26,2008,3,Sierra,0.318151,0.131052,0.075640,0.070581,0.141148,0.217664,146.157129,114.168749,200.0,1.752788
27,2008,4,Amazonía,0.272332,0.098593,0.052275,0.056524,0.111849,0.169085,145.338212,119.851767,200.0,1.684014
28,2008,4,Galápagos,0.687361,0.377720,0.253338,0.122535,0.236488,0.351412,84.595760,52.611587,200.0,3.801444
29,2008,4,Los Ríos,0.478029,0.175425,0.094372,0.052329,0.103244,0.154180,99.306462,83.134553,200.0,2.405739
30,2008,4,Manabí,0.567317,0.239981,0.139286,0.065557,0.129964,0.198010,89.226520,73.264715,200.0,2.729827
31,2008,4,Pichincha,0.162572,0.053598,0.026991,0.059272,0.116772,0.174973,202.910366,160.844165,200.0,1.250251
32,2008,4,Sierra,0.300945,0.126940,0.075033,0.074607,0.147482,0.223374,162.513757,125.924049,200.0,1.658530

### Inserta los cálculos en la base final

In [45]:
indices = pd.read_csv("indices_region.csv", encoding='latin-1')

In [46]:
import os

# 2. cheque el archivo
if not os.path.isfile('indices_region.csv'):
    # Headers si es la primera vez
    df_trimestral.to_csv('indices_region.csv', index=False, encoding='latin-1')
else:
    # SI ya existe, append
    df_trimestral.to_csv('indices_region.csv', mode='a', index=False, header=False, encoding='latin-1')