In [1]:
import numpy as np
import pandas as pd

In [5]:
# data = pd.read_stata(r"Z:\harmonized\ECU\ENEMDU\data_arm\ECU_1990m11_BID.dta") # para bases de stata
data = pd.read_stata(r"Bases Enendum 96, 97, 98\ECU_1998m11.dta") # para bases de stata

In [6]:
data.columns

Index(['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
       'formul', 'persona', 'numpers', 'resumen', 'reljefe', 'edad', 'sexo',
       'nivinst', 'anoinst', 'asistea', 'sabele', 'iess', 'donnac', 'lugnac',
       'siemvic', 'donvian', 'lugvian', 'cuanvic', 'trabajo', 'actayuda',
       'hortrasa', 'ratmeh', 'hormas', 'ratmah', 'aunotra', 'pornot',
       'bustrasa', 'bustrama', 'sitios', 'amigos', 'directo', 'prensa',
       'agepu', 'agepri', 'tresne', 'tiembus', 'motnobus', 'deseatra',
       'condina', 'trabant', 'motnotra', 'tiemnot', 'rama', 'grupo',
       'catetrab', 'pertrabn', 'npertra', 'numtrab', 'estabil', 'hortrahp',
       'hortrahs', 'hortraho', 'ramas', 'grupos', 'cates', 'ingpat', 'ingasg',
       'ingepv', 'ingdom', 'ingjub', 'ingalq', 'ingotr', 'nov', 'dic', 'ene',
       'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct',
       'condact', 'peamsiu', 'secins', 'subequ', 'ingrl', 'vivefe', 'fexp',
       'fexp1'],
      dtype='object')

In [7]:
data = data[['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
       'formul', 'persona', 'numpers', 'edad', 'trabajo', 'ingpat', 'ingasg',
       'ingepv', 'ingdom', 'ingjub', 'ingalq', 'ingotr', 'nov', 'dic', 'ene',
       'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'ingrl', 'fexp1', 'fexp']]

In [8]:
data ['sum_ing'] = data [['ingasg', 'ingepv', 'ingdom']].sum(axis=1)

In [9]:
data['suma_ing_ene'] = data.apply(lambda x: x['sum_ing'] if x['ene'] == 'trabajando' else None, axis=1)
data['suma_ing_feb'] = data.apply(lambda x: x['sum_ing'] if x['feb'] == 'trabajando' else None, axis=1)
data['suma_ing_mar'] = data.apply(lambda x: x['sum_ing'] if x['mar'] == 'trabajando' else None, axis=1)
data['suma_ing_abr'] = data.apply(lambda x: x['sum_ing'] if x['abr'] == 'trabajando' else None, axis=1)
data['suma_ing_may'] = data.apply(lambda x: x['sum_ing'] if x['may'] == 'trabajando' else None, axis=1)
data['suma_ing_jun'] = data.apply(lambda x: x['sum_ing'] if x['jun'] == 'trabajando' else None, axis=1)
data['suma_ing_jul'] = data.apply(lambda x: x['sum_ing'] if x['jul'] == 'trabajando' else None, axis=1)
data['suma_ing_ago'] = data.apply(lambda x: x['sum_ing'] if x['ago'] == 'trabajando' else None, axis=1)
data['suma_ing_sep'] = data.apply(lambda x: x['sum_ing'] if x['sep'] == 'trabajando' else None, axis=1)
data['suma_ing_oct'] = data.apply(lambda x: x['sum_ing'] if x['oct'] == 'trabajando' else None, axis=1)
data['suma_ing_nov'] = data.apply(lambda x: x['sum_ing'] if x['nov'] == 'trabajando' else None, axis=1)
data['suma_ing_dic'] = data.apply(lambda x: x['sum_ing'] if x['dic'] == 'trabajando' else None, axis=1)

In [10]:
data['suma_ing_t1'] = (data['suma_ing_ene'] + data['suma_ing_feb'] + data['suma_ing_mar'])/3
data['suma_ing_t2'] = (data['suma_ing_abr'] + data['suma_ing_may'] + data['suma_ing_jun'])/3
data['suma_ing_t3'] = (data['suma_ing_jul'] + data['suma_ing_ago'] + data['suma_ing_sep'])/3
data['suma_ing_t4'] = (data['suma_ing_oct'] + data['suma_ing_nov'] + data['suma_ing_dic'])/3

In [11]:
# Llenar valores perdidos con un dato (0)
data['suma_ing_t1'] = data['suma_ing_t1'].fillna(0)
data['suma_ing_t2'] = data['suma_ing_t2'].fillna(0)
data['suma_ing_t3'] = data['suma_ing_t3'].fillna(0)
data['suma_ing_t4'] = data['suma_ing_t4'].fillna(0)

In [12]:
data

,rn,dominio,ciudad,zona,sector,vivienda,hogar,formul,persona,numpers,...,suma_ing_jul,suma_ing_ago,suma_ing_sep,suma_ing_oct,suma_ing_nov,suma_ing_dic,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4
0,1,3,010150,001,007,01,1,1,1,6,...,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0
1,1,3,010150,001,007,01,1,1,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,1,3,010150,001,007,01,1,1,3,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,1,3,010150,001,007,01,1,1,4,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,1,3,010150,001,007,01,1,1,5,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40504,3,8,210450,001,011,12,1,1,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40505,3,8,210450,001,011,12,1,1,3,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40506,3,8,210450,001,011,12,1,1,4,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40507,3,8,210450,001,011,12,1,1,5,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40508,3,8,210450,001,011,12,1,1,6,6,...,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
data['suma_ing_t1'].mean()

np.float64(287102.9054284233)

In [14]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: openpyxl in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [16]:
import pandas as pd

data_externa = pd.read_excel(r"data_externa.xlsx", sheet_name='datos', engine='openpyxl')

In [17]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 1998]
datos_base = data_externa[data_externa['Año'] == 2014]

In [18]:
datos_actual

,Año,trimestre,Nacional,Sierra,Costa,Guayaquil,Esmeraldas,Machala,Manta,Santo Domingo,Quito,Loja,Cuenca,Ambato,salario básico unificado,tipo de cambio,umbral de pobreza
32,1998,1,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,4655.000000,375.832026
33,1998,2,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,5192.666667,378.853988
34,1998,3,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,5700.333333,381.904114
35,1998,4,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,6676.000000,385.117817

In [19]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_base.iterrows()
     }

tipo_cambio_dict = dict(zip(datos_actual['trimestre'], datos_actual['tipo de cambio']))

In [20]:
# Corregimos los códigos para usarlos cómo texto
data['ciudad'] = data['ciudad'].apply(str)
data['ciudad'] = data['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)

data['ciudad_2'] = data['ciudad'].apply(lambda x: x[:2])

In [21]:
parroquia_dict = {
    '01': 'Cuenca',
    '09': 'Guayaquil',
    '17': 'Quito'
}

data['ciudad_asignada'] = data['ciudad_2'].apply(lambda x: parroquia_dict.get(x, 'Nacional'))

In [22]:
def assgna_trimestre(fila):
    if 'trabajando' in [fila['ene'], fila['feb'], fila['mar']]:
        return 1
    elif 'trabajando' in [fila['abr'], fila['may'], fila['jun']]:
        return 2
    elif 'trabajando' in [fila['jul'], fila['ago'], fila['sep']]:
        return 3
    elif 'trabajando' in [fila['oct'], fila['nov'], fila['dic']]:
        return 4
    else:
        return None
    
data['trimestre'] = data.apply(assgna_trimestre, axis=1)

In [23]:
# Función que asigna valores correspondientes
def asigna_ipc(fila):
    return ipc_dict.get(fila['trimestre'], {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila):
    return ipc_base_dict.get(fila['trimestre'], {}).get(fila['ciudad_asignada'], None)

In [24]:
data['ipc'] = data.apply(asigna_ipc, axis=1)
data['ipc_base'] = data.apply(asigna_ipc_base, axis=1)
data['tipo_cambio'] = data['trimestre'].map(tipo_cambio_dict)

In [25]:
# Calculamos el deflactor
data['def'] = (data['ipc_base'] / data['ipc'])

In [26]:
data['ingr_t1_r'] = (data['suma_ing_t1'] / data['tipo_cambio']) * data['def']
data['ingr_t2_r'] = (data['suma_ing_t2'] / data['tipo_cambio']) * data['def']
data['ingr_t3_r'] = (data['suma_ing_t3'] / data['tipo_cambio']) * data['def']
data['ingr_t4_r'] = (data['suma_ing_t4'] / data['tipo_cambio']) * data['def']

In [27]:
data[['suma_ing_t1', 'suma_ing_t2', 'suma_ing_t3', 'suma_ing_t4', 'ipc', 'ipc_base', 'def', 'tipo_cambio', 'ingr_t1_r', 'ingr_t2_r', 'ingr_t3_r', 'ingr_t4_r']]

,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4,ipc,ipc_base,def,tipo_cambio,ingr_t1_r,ingr_t2_r,ingr_t3_r,ingr_t4_r
0,720000.0,720000.0,720000.0,720000.0,10.345311,97.862086,9.459559,4655.0,1463.132682,1463.132682,1463.132682,1463.132682
1,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
40504,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40505,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40506,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40507,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40508,0.0,0.0,0.0,0.0,11.900493,98.083034,8.241930,4655.0,0.000000,0.000000,0.000000,0.000000

In [28]:
data['ingr_t4_r'].mean()

np.float64(1166.2965489464414)

In [29]:
columnas_idef = ['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar']

data['idef_hogar'] = data[columnas_idef].astype(str).agg(''.join, axis=1)
len(data['idef_hogar'].unique())

9216

In [30]:
data [['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar', 'idef_hogar', 'persona', 'numpers']]

,rn,dominio,ciudad,zona,sector,vivienda,hogar,idef_hogar,persona,numpers
0,1,3,010150,001,007,01,1,13010150001007011,1,6
1,1,3,010150,001,007,01,1,13010150001007011,2,6
2,1,3,010150,001,007,01,1,13010150001007011,3,6
3,1,3,010150,001,007,01,1,13010150001007011,4,6
4,1,3,010150,001,007,01,1,13010150001007011,5,6
...,...,...,...,...,...,...,...,...,...,...
40504,3,8,210450,001,011,12,1,38210450001011121,2,6
40505,3,8,210450,001,011,12,1,38210450001011121,3,6
40506,3,8,210450,001,011,12,1,38210450001011121,4,6
40507,3,8,210450,001,011,12,1,38210450001011121,5,6
40508,3,8,210450,001,011,12,1,38210450001011121,6,6

In [31]:
data['ingr_t1_h'] = data.groupby('idef_hogar')['ingr_t1_r'].transform('sum')
data['ingr_t2_h'] = data.groupby('idef_hogar')['ingr_t2_r'].transform('sum')
data['ingr_t3_h'] = data.groupby('idef_hogar')['ingr_t3_r'].transform('sum')
data['ingr_t4_h'] = data.groupby('idef_hogar')['ingr_t4_r'].transform('sum')

In [32]:
data[['ingr_t1_h', 'ingr_t2_h', 'ingr_t3_h', 'ingr_t4_h']]

         ingr_t1_h    ingr_t2_h    ingr_t3_h    ingr_t4_h
0      1463.132682  1463.132682  1463.132682  1463.132682
1      1463.132682  1463.132682  1463.132682  1463.132682
2      1463.132682  1463.132682  1463.132682  1463.132682
3      1463.132682  1463.132682  1463.132682  1463.132682
4      1463.132682  1463.132682  1463.132682  1463.132682
...            ...          ...          ...          ...
40504  1593.498894  1593.498894  1593.498894  1593.498894
40505  1593.498894  1593.498894  1593.498894  1593.498894
40506  1593.498894  1593.498894  1593.498894  1593.498894
40507  1593.498894  1593.498894  1593.498894  1593.498894
40508  1593.498894  1593.498894  1593.498894  1593.498894

[40509 rows x 4 columns]

In [33]:
print("Ingreso medio de un hogar t4: ", data['ingr_t4_h'].mean())
print("Mediana del ingreso de un hogar t4: ", data['ingr_t4_h'].median())

Ingreso medio de un hogar t4:  2483.9901183202246
Mediana del ingreso de un hogar t4:  1062.332596256261

In [34]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

In [35]:
data ['edad']

0        33
1        28
2        12
3         7
4         4
         ..
40504    28
40505     9
40506     4
40507     2
40508    18
Name: edad, Length: 40509, dtype: int64

In [36]:
data = data.loc[(data['edad'] >= 0) & (data['edad'] < 100)]
len(data)

40509

In [37]:
k = 0.4
s = 0.9

In [38]:
# Si es necesario calcular el número de niños
data['es_nino'] = data['edad'] < 10

data['ninos'] = data.groupby('idef_hogar')['es_nino'].transform('sum')

# Si es necesario calcular el número de adultos
data['es_adulto'] = data['edad'] > 10

data['adultos'] = data.groupby('idef_hogar')['es_adulto'].transform('sum')

In [39]:
data['escala'] = (data['adultos'] + k * data['ninos']) ** s

In [40]:
data['ingr_t_t1'] = data['ingr_t1_h'] / data['escala']
data['ingr_t_t2'] = data['ingr_t2_h'] / data['escala']
data['ingr_t_t3'] = data['ingr_t3_h'] / data['escala']
data['ingr_t_t4'] = data['ingr_t4_h'] / data['escala']

In [41]:
data[['ingr_t_t1', 'ingr_t_t2', 'ingr_t_t3', 'ingr_t_t4']]

        ingr_t_t1   ingr_t_t2   ingr_t_t3   ingr_t_t4
0      402.123404  402.123404  402.123404  402.123404
1      402.123404  402.123404  402.123404  402.123404
2      402.123404  402.123404  402.123404  402.123404
3      402.123404  402.123404  402.123404  402.123404
4      402.123404  402.123404  402.123404  402.123404
...           ...         ...         ...         ...
40504  437.952899  437.952899  437.952899  437.952899
40505  437.952899  437.952899  437.952899  437.952899
40506  437.952899  437.952899  437.952899  437.952899
40507  437.952899  437.952899  437.952899  437.952899
40508  437.952899  437.952899  437.952899  437.952899

[40509 rows x 4 columns]

In [42]:
print("Ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].mean())
print("Mediana del ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].median())

Ingreso individual descontando cargas familiares t4:  665.2600120566833
Mediana del ingreso individual descontando cargas familiares t4:  272.47600854064507

In [43]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

In [44]:
# Asigna el umbral por trimestre si hay umbral por región modificar
data['umbral'] = data['trimestre'].map(umbral_dict)

data['umbral'] = data.groupby('idef_hogar')['umbral'].transform('mean')

In [45]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [46]:
data['persona_fexp'] = 1 * data['fexp']

In [47]:
for t in [1, 2, 3, 4]:
    condicion = data['trimestre'] == t
    col_ingr = f'ingr_t_t{t}'
    col_pobres = f'pobres_t{t}'

    # una columna que identifica a quienes están por debajo de la línea de pobreza por trimestre
    data.loc[condicion, col_pobres] = (
        (data.loc[condicion, col_ingr] - data.loc[condicion, 'umbral']) < 0
    ).astype(int)

In [48]:
print("pobreza t1: ", (data['pobres_t1'] * data['fexp']).sum()/data.loc[data['trimestre'] == 1]['persona_fexp'].sum())
print("pobreza t2: ", (data['pobres_t2'] * data['fexp']).sum()/data.loc[data['trimestre'] == 2]['persona_fexp'].sum())
print("pobreza t3: ", (data['pobres_t3'] * data['fexp']).sum()/data.loc[data['trimestre'] == 3]['persona_fexp'].sum())
print("pobreza t4: ", (data['pobres_t4'] * data['fexp']).sum()/data.loc[data['trimestre'] == 4]['persona_fexp'].sum())

pobreza t1:  0.5000701588520222
pobreza t2:  0.6380246723785792
pobreza t3:  0.6959185767470955
pobreza t4:  0.689001772405395

In [49]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp[f'ingr_t_t{t}'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[t] - df_temp[f'ingr_t_t{t}']) / umbral_dict[t]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total
    
    # Guardamos los resultados
    datos_final.loc[f't{t}', 'fgt0'] = fgt0
    datos_final.loc[f't{t}', 'fgt1'] = fgt1
    datos_final.loc[f't{t}', 'fgt2'] = fgt2

In [50]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()
    
    # Ingreso promedio ponderado
    mu = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp[f'ingr_t_t{t}']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    datos_final.loc[f't{t}', 'a25'] = a25
    datos_final.loc[f't{t}', 'a50'] = a50
    datos_final.loc[f't{t}', 'a75'] = a75

In [51]:
for t in [1, 2, 3, 4]:
    df_temp = data.loc[data['trimestre'] == t].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total
    
    datos_final.loc[f't{t}', 'ingreso_promedio'] = media_ponderada

In [52]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.499964,0.361247,0.318452,0.230868,0.46464,0.750227,842.049938
t2,0.638025,0.474377,0.415434,0.262581,0.521045,0.816335,519.466897
t3,0.696737,0.51312,0.460338,0.257056,0.531548,0.848475,410.481944
t4,0.689002,0.600149,0.573847,0.242898,0.557103,0.906672,196.862122

In [53]:
datos_final.to_csv('datos_final1998.csv')