In [1]:
import numpy as np
import pandas as pd

# Plantilla

Es necesario ajustar las definiciones, las fuentes de los datos y posiblemente definiciones si la ENEMDU tiene una dimensión geográfica y temporal al mismo tiempo

Ahora hay bases por mes, entonces calculamos para cada mes

In [3]:
data1 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_01_SPSS\enemdu_persona_2022_01.sav", convert_categoricals=False) # para bases de stata
data2 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_02_SPSS\enemdu_persona_2022_02.sav", convert_categoricals=False) # para bases de stata
data3 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_03_SPSS\enemdu_persona_2022_03.sav", convert_categoricals=False) # para bases de stata

data4 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_04_SPSS\enemdu_persona_2022_04.sav", convert_categoricals=False) # para bases de stata
data5 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_05_SPSS\enemdu_persona_2022_05.sav", convert_categoricals=False) # para bases de stata
data6 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_06_SPSS\enemdu_persona_2022_06.sav", convert_categoricals=False) # para bases de stata

data7 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_07_SPSS\enemdu_persona_2022_07.sav", convert_categoricals=False) # para bases de stata
data8 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_08_SPSS\enemdu_persona_2022_08.sav", convert_categoricals=False) # para bases de stata
data9 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_09_SPSS\enemdu_persona_2022_09.sav", convert_categoricals=False) # para bases de stata

data10 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_10_SPSS\enemdu_persona_2022_10.sav", convert_categoricals=False) # para bases de stata
data11 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_11_SPSS\enemdu_persona_2022_11.sav", convert_categoricals=False) # para bases de stata
data12 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2022\1_BDD_ENEMDU_2022_12_SPSS\enemdu_persona_2022_12.sav", convert_categoricals=False) # para bases de stata

## Revisar los datos

| enero   | febrero | marzo   | abril   | mayo    | junio   | julio   | agosto  | septiembre | octubre | noviembre | diciembre |
|---------|---------|---------|---------|---------|---------|---------|---------|------------|---------|-----------|-----------|
| area| area| area| area| area| area| area| area| area| area| area| area|
| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad|
| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda|
| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar|
| p02| p02| p02| p02| p02| p02| p02| p02| p02| p02| p02| p02|
| p03| p03| p03| p03| p03| p03| p03| p03| p03| p03| p03| p03|
| p66| p66| p66| p66| p66| p66| p66| p66| p66| p66| p66| p66|
| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp|
| p20| p20| p20| p20| p20| p20| p20| p20| p20| p20| p20| p20|
| id_hogar| id_hogar| if_hogar| if_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar|

En esta encuesta tenemos una base para cada mes, esto cambia la lógica que habíamos tenido hasta ahora así que de aquí en adelante cambiamos algo del código, mantenemos de acuerdo a las etiquetas de las variables p66 como la variable de ingreso laboral monetario de la actividad principal asalariada para mantener la concordancia con el resto de los años.

Elegimos hacer los cálculos en las bases mensuales para poder usar la representatividad mensual, con un promedio simple debería bastar para tener el resultado del trimestre.

Ahora usamos p20 que pregunta si trabajo la semana pasada, si se cumple vamos a asumir que trabajo durante todo el mes, ahora en adelante capturaremos incluso de mejor forma el mercado laboral, mantenemos la idea de que si el individuo trabajo recibe su ingreso laboral reportado.

In [17]:
columnas = pd.Index(['area', 'ciudad', 'vivienda', 
                     'hogar', 'p66', 'fexp', 'p02', 'p03', 
                     'p20', 'id_hogar'])

Filtramos solo las columnas de interés para alivar el peso en la memoria

In [18]:
data1 = data1[columnas.intersection(data1.columns)]
data2 = data2[columnas.intersection(data2.columns)]
data3 = data3[columnas.intersection(data3.columns)]
data4 = data4[columnas.intersection(data4.columns)]
data5 = data5[columnas.intersection(data5.columns)]
data6 = data6[columnas.intersection(data6.columns)]
data7 = data7[columnas.intersection(data7.columns)]
data8 = data8[columnas.intersection(data8.columns)]
data9 = data9[columnas.intersection(data9.columns)]
data10 = data10[columnas.intersection(data10.columns)]
data11 = data11[columnas.intersection(data11.columns)]
data12 = data12[columnas.intersection(data12.columns)]

Creamos una variable de ingreso laboral que es igual al ingreso por asalariado y limpiamos según los valores de ingrl, para mantener ambas variables para cada base consistente

In [31]:
data12['p66'].value_counts().sort_index(ascending=False)

p66
999999.0     14
8200.0        1
6000.0        1
5300.0        1
5000.0        3
           ...
20.0          5
15.0          3
14.0          1
10.0          4
0.0         140
Name: count, Length: 487, dtype: int64

In [32]:
data1['p66'] = pd.to_numeric(data1['p66'], errors='coerce')
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x > 10000 else x)
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x < 0 else x)

data2['p66'] = pd.to_numeric(data2['p66'], errors='coerce')
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x > 9000 else x)
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x < 0 else x)

data3['p66'] = pd.to_numeric(data3['p66'], errors='coerce')
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x > 6200 else x)
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x < 0 else x)

data4['p66'] = pd.to_numeric(data4['p66'], errors='coerce')
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x > 7000 else x)
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x < 0 else x)

data5['p66'] = pd.to_numeric(data5['p66'], errors='coerce')
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x > 14250 else x)
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x < 0 else x)

data6['p66'] = pd.to_numeric(data6['p66'], errors='coerce')
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x > 8000 else x)
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x < 0 else x)

data7['p66'] = pd.to_numeric(data7['p66'], errors='coerce')
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x > 7500 else x)
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x < 0 else x)

data8['p66'] = pd.to_numeric(data8['p66'], errors='coerce')
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x > 6000 else x)
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x < 0 else x)

data9['p66'] = pd.to_numeric(data9['p66'], errors='coerce')
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x > 8500 else x)
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x < 0 else x)

data10['p66'] = pd.to_numeric(data10['p66'], errors='coerce')
data10['p66'] = data10['p66'].apply(lambda x: np.nan if x > 6400 else x)
data10['p66'] = data10['p66'].apply(lambda x: np.nan if x < 0 else x)

data11['p66'] = pd.to_numeric(data11['p66'], errors='coerce')
data11['p66'] = data11['p66'].apply(lambda x: np.nan if x > 10000 else x)
data11['p66'] = data11['p66'].apply(lambda x: np.nan if x < 0 else x)

data12['p66'] = pd.to_numeric(data12['p66'], errors='coerce')
data12['p66'] = data12['p66'].apply(lambda x: np.nan if x > 82000 else x)
data12['p66'] = data12['p66'].apply(lambda x: np.nan if x < 0 else x)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\637148138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['p66'] = pd.to_numeric(data1['p66'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\637148138.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['p66'] = data1['p66'].apply(lambda x: np.nan if x > 10000 else x)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\637148138.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['p66'] = data1['p66'].apply(lambda x: np.nan if x < 0 else x)

In [34]:
for base in [data1, data2, data3, data4, data5, data6, 
             data7, data8, data9, data10, data11, data12]:
    base['ingr'] = base['p66']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2360950996.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ingr'] = base['p66']

Ingreso mensual asumiendo que las personas reciben el mismo valor reportado en 'ingr' siempre que reportan estar ocupados la semana pasada, de acuerdo a la variable 'trabajo'

In [35]:
for base in [data1, data2, data3, data4, data5, data6, 
             data7, data8, data9, data10, data11, data12]:
    base['ingr'] = base.apply(lambda x: x['ingr'] if x['p20'] == 1 else np.nan, axis=1)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1112614857.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ingr'] = base.apply(lambda x: x['ingr'] if x['p20'] == 1 else np.nan, axis=1)

## Deflactamos y transformamos el ingreso

Esto deja todo en dólares constantes de 2014

In [36]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 2022]
datos_base = data_externa[data_externa['Año'] == 2014]

Diccionarios de ipc

In [37]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_base.iterrows()
     }

### Creamos identificadores para las ciudades siguiendo los códigos del INEC y para los trimestres

In [38]:
# Corregimos los códigos para usarlos cómo texto
for base in [data1, data2, data3, data4, data5,
             data6, data7, data8, data9, data10, data11,
             data12]:
    base['ciudad'] = base['ciudad'].apply(str)
    base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)
    base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2426839849.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ciudad'] = base['ciudad'].apply(str)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2426839849.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2426839849.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

Diccionario ciudades disponibles

In [41]:
parroquia_dict = {
    '0101': 'Cuenca',
    '0901': 'Guayaquil',
    '0801': 'Esmeraldas',
    '0701': 'Machala',
    '1308': 'Manta',
    '1701': 'Quito',
    '1101': 'Loja',
    '1801': 'Ambato'
}

def get_parroquia(codigo):
    if codigo in parroquia_dict:
        return parroquia_dict[codigo]
    elif codigo[:2] in ['01', '02', '03', '04', '05', '06', '10', '11', '17', '18']:
        return 'Sierra'
    elif codigo[:2] in ['07', '08', '09', '12', '13', '23', '24']:
        return 'Costa'
    else:
        return 'Nacional'

for base in [data1, data2, data3, data4, data5,
             data6, data7, data8, data9,
             data10, data11, data12]:
    base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2732502318.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)

In [45]:
data9['ciudad_asignada'].value_counts()

ciudad_asignada
Nacional    15283
Sierra       5532
Quito        3696
Costa        2947
Ambato       1903
Loja          434
Manta          60
Name: count, dtype: int64

### Asignamos el ipc correspondiente según ciudad correspondiente

$\begin{equation}
    ingr_{USD-base-2014}^{i} = ingr_{dólares}^{i}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Desde 2000 en adelante ya no es necesario utilizar el tipo de cambio debido al cambio de moneda

In [46]:
# Función que asigna valores correspondientes
def asigna_ipc(fila, trimestre):
    return ipc_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila, trimestre):
    return ipc_base_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

In [47]:
data1['ipc'] = data1.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data1['ipc_base'] = data1.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data2['ipc'] = data2.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data2['ipc_base'] = data2.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data3['ipc'] = data3.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data3['ipc_base'] = data3.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data4['ipc'] = data4.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data4['ipc_base'] = data4.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data5['ipc'] = data5.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data5['ipc_base'] = data5.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data6['ipc'] = data6.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data6['ipc_base'] = data6.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data7['ipc'] = data7.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data7['ipc_base'] = data7.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data8['ipc'] = data8.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data8['ipc_base'] = data8.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data9['ipc'] = data9.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data9['ipc_base'] = data9.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data10['ipc'] = data10.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data10['ipc_base'] = data10.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data11['ipc'] = data11.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data11['ipc_base'] = data11.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data12['ipc'] = data12.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data12['ipc_base'] = data12.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2802951969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['ipc'] = data1.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2802951969.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['ipc_base'] = data1.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

In [48]:
# Calculamos el deflactor
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['def'] = (base['ipc_base'] / base['ipc'])

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1671624327.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['def'] = (base['ipc_base'] / base['ipc'])

In [49]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_r'] = base['ingr'] * base['def']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\3754981744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ingr_r'] = base['ingr'] * base['def']

In [51]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_r'].mean())

690.2136858609168
444.1187440341826
447.79349502146374
467.771618547242
449.9594581127811
448.93620769953947
437.5071858507814
440.97938886562747
522.3563156411632
450.02036376319785
455.0961252034351
479.0090568861162

## Calculo ingreso de los hogares

In [52]:
for base in [data1, data2, data3, data4, data5, 
             data6, data7, data8, data9, data10, data11, data12]:
    base['idef_hogar'] = base['id_hogar']

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['idef_hogar'].nunique())

8836
8807
8821
8792
8839
8830
8937
8962
8965
8864
8857
8852

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\3534142507.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['idef_hogar'] = base['id_hogar']

Si todos los miembros del hogar tienen NA como ingreso, mantener NA, si al menos uno tiene un ingreso sumamos para el ingreso del hogar, así evitamos subestimar el ingreso del hogar si tenemos valores perdidos

In [53]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [54]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1636345169.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)

In [55]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_h'].mean())

965.403017903962
641.0691259928598
640.0681076437213
659.9327973892463
648.94765545758
641.325952483401
630.2041728525646
633.1237819766998
756.7035828715345
654.4286685628202
660.501198270512
694.9346838066068

## Sacamos edades negativas y mayores a 100 años

Transformamos las variables de edad a numericas para evitar problemas

In [56]:
for base in [data1, data2, data3, data4, data5, data6, data7, 
             data8, data9, data10, data11, data12]:
    base['edad'] = pd.to_numeric(base['p03'], errors='coerce')

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1087045015.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')

In [57]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base = base.loc[(base['edad'] >= 0) & (base['edad'] < 100)]

## Ingreso individual descontando cargas familiares

Utilizando la metodología del autor dividimos el ingreso del hogar para la escala $(A_{i}+kC_{i})^{s}$ donde $A_{i}$ es al número de adultos, $C_{i}$ es el número de niños en el hogar $i$. $k$ es el costo en recursos de cada niño y $s$ busca reflejar las restricciones

In [58]:
k = 0.4
s = 0.9

In [59]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    # Si es necesario calcular el número de niños
    base['es_nino'] = base['edad'] < 10 
    base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')

    # Si es necesario calcular el número de adultos
    base['es_adulto'] = base['edad'] > 10
    base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\3602317441.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\3602317441.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\3602317441.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\3602317441.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')

In [60]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['escala'] = (base['adultos'] + k * base['ninos']) ** s

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\4179537099.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s

In [61]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_t'] = base['ingr_h'] / base['escala']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1010359397.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['ingr_t'] = base['ingr_h'] / base['escala']

In [62]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
        print(base['ingr_t'].mean())

300.4899523475989
198.36732402341485
197.67546696134076
205.99275718757832
203.09648946017327
201.1121102932832
197.57959008872373
197.16577802760108
238.56822890564206
204.42059027418168
210.45099316203903
221.5908985972029

## Umbrales de pobreza

Incluimos los índices de pobreza si es posible a nivel regional para luego poder utilizar de mejor forma el factor de expansión

$\begin{equation}
    umbral_{USD-base-2014}^{i} = umbral_{año}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

Diccionario de umbral

In [63]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

## Cálculo del índice de pobreza de Foster, Greer y Thorbecke

Para calcular un ínidce de pobreza se utiliza a Foster, Greer y Thorbecke (1984), ya que satisface algunas caracterísitcas de distribución que son positivas e igual a las enunciadas por Sen, el autor usa el mismo índice.

$\begin{equation}FGT_{\alpha} = \frac{1}{N}\sum_{i=1}^{H}\left(\frac{z-y_{i}}{z}\right)^{\alpha}\end{equation}$

Donde $z$ es el umbral de pobreza, $N$ es el número de personas en la economía, $H$ es el número de pobres (personas debajo de la línea de pobreza) $y_{i}$ es el ingreso de cada individuo. Mientras mayor es el valor de $\alpha$ mayor es el peso de los individuos más pobres, mayor $FGT$ mayor pobreza en la economía.

En este caso los umbrales están anivel nacional, aún así buscamos calcular la pobreza por región y sacar un promedio ponderado por región para la pobreza nacional, con el objetivo de hacerlo más específico

In [64]:
for base in [data1, data2, data3, data4, data5, data6, data7, 
             data8, data9, data10, data11, data12]:
        base['persona_fexp'] = 1 * base['fexp']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\2680591142.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['persona_fexp'] = 1 * base['fexp']

In [65]:
def trimestre(base):
    """Returns quarter number based on dataframe identity."""
    trimestre_1 = [data1, data2, data3]
    trimestre_2 = [data4, data5, data6]
    trimestre_3 = [data7, data8, data9]
    trimestre_4 = [data10, data11, data12]

    if any(base is df for df in trimestre_1):
        return 1
    elif any(base is df for df in trimestre_2):
        return 2
    elif any(base is df for df in trimestre_3):
        return 3
    elif any(base is df for df in trimestre_4):
        return 4
    else:
        return print("Problema")

In [66]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    
    t = trimestre(base)
    base['pobres_t'] = (
        (base['ingr_t'] - umbral_dict.get(trimestre(base)) < 0
    ).astype(int))

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\511293179.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base['pobres_t'] = (

In [68]:
for base in [data1, data2, data3, data4, data5, data6, data7, 
             data8, data9, data10, data11, data12]:
    print(f"pobreza : ", (base['pobres_t'] * base['fexp']).sum()/base.loc[base['ingr_t'] >= 0]['persona_fexp'].sum())

pobreza :  0.24029239560859067
pobreza :  0.2662228944946949
pobreza :  0.28156383053969036
pobreza :  0.2626582940445825
pobreza :  0.255100891523757
pobreza :  0.2605133081188544
pobreza :  0.3140190527875645
pobreza :  0.2684848258196578
pobreza :  0.24389417456753457
pobreza :  0.29017543297423126
pobreza :  0.27175394427794447
pobreza :  0.2569529555144999

In [69]:
# Calculamos los índices por mes, luego buscaremos la manera de sacar los indices trimestrales como un promedio ponderado de los meses
datos_final_mensual = pd.DataFrame(index=[f'm{x+1}' for x in range(12)], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio', 'factor'])

In [70]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12]

for idx, base in enumerate(datasets, start=1):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp['ingr_t'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[trimestre(base)] - df_temp['ingr_t']) / umbral_dict[trimestre(base)]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total

    # Assign to the corresponding row: data1→m1, data2→m2, etc.
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['fgt0','fgt1','fgt2']] = [fgt0, fgt1, fgt2]

In [72]:
datos_final_mensual

         fgt0      fgt1      fgt2  a25  a50  a75 ingreso_promedio factor
m1   0.249319  0.109904  0.071893  NaN  NaN  NaN              NaN    NaN
m2   0.278906  0.117746  0.074472  NaN  NaN  NaN              NaN    NaN
m3   0.301518  0.125653  0.078579  NaN  NaN  NaN              NaN    NaN
m4    0.27042  0.121534  0.077694  NaN  NaN  NaN              NaN    NaN
m5   0.262866  0.114291  0.071899  NaN  NaN  NaN              NaN    NaN
m6   0.267534    0.1028   0.06147  NaN  NaN  NaN              NaN    NaN
m7   0.314981  0.141711  0.092691  NaN  NaN  NaN              NaN    NaN
m8   0.274634  0.103853  0.058248  NaN  NaN  NaN              NaN    NaN
m9    0.25052  0.103777   0.06578  NaN  NaN  NaN              NaN    NaN
m10  0.290175   0.11775  0.068248  NaN  NaN  NaN              NaN    NaN
m11  0.271754  0.115524  0.069097  NaN  NaN  NaN              NaN    NaN
m12  0.256953  0.095927   0.05577  NaN  NaN  NaN              NaN    NaN

## Calculo del índice de desigualdad de Atkinson

Vamos a calcular el índice de desigualdad de atkinson con un parámetro $\epsilon$ de aversión a la desigualdad y un $\mu$ que es igual a la media de los ingresos individuales, con la siguiente fórmula.

$\begin{equation}A = 1-\frac{1}{\mu}\left(\frac{1}{N}\sum_{i=1}^{N}y^{1-\epsilon}\right)^{1/(1-\epsilon)}\end{equation}$

Donde $y_{i}$ es el ingreso individual y $\mu$ es el ingreso medio

In [73]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12]

for idx, base in enumerate(datasets, start=1):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()

    # Ingreso promedio ponderado
    mu = (df_temp['ingr_t'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp['ingr_t']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['a25','a50','a75']] = [a25, a50, a75]

In [74]:
datos_final_mensual

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,factor
m1,0.249319,0.109904,0.071893,0.112387,0.220648,0.341083,NaN,NaN
m2,0.278906,0.117746,0.074472,0.0889,0.174407,0.270681,NaN,NaN
m3,0.301518,0.125653,0.078579,0.086213,0.169913,0.261914,NaN,NaN
m4,0.27042,0.121534,0.077694,0.087921,0.175535,0.277497,NaN,NaN
m5,0.262866,0.114291,0.071899,0.094127,0.181895,0.281097,NaN,NaN
m6,0.267534,0.1028,0.06147,0.079198,0.156182,0.241094,NaN,NaN
m7,0.314981,0.141711,0.092691,0.091155,0.182641,0.295874,NaN,NaN
m8,0.274634,0.103853,0.058248,0.080932,0.156171,0.235364,NaN,NaN
m9,0.25052,0.103777,0.06578,0.091079,0.179535,0.281211,NaN,NaN
m10,0.290175,0.11775,0.068248,0.080308,0.157594,0.240676,NaN,NaN
m11,0.271754,0.115524,0.069097,0.086376,0.168393,0.259706,NaN,NaN
m12,0.256953,0.095927,0.05577,0.084397,0.163436,0.248904,NaN,NaN

Guardamos el ingreso promedio

In [75]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12]

for idx, base in enumerate(datasets, start=1):
    df_temp = base.loc[base['ingr_t'] >= 0].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp['ingr_t'] * df_temp['fexp']).sum() / peso_total
    factor = df_temp['fexp'].sum()
    
    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['ingreso_promedio', 'factor']] = [media_ponderada, factor]

In [76]:
datos_final_mensual

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,factor
m1,0.249319,0.109904,0.071893,0.112387,0.220648,0.341083,247.52528,10391381.479977
m2,0.278906,0.117746,0.074472,0.0889,0.174407,0.270681,169.012849,11076549.929773
m3,0.301518,0.125653,0.078579,0.086213,0.169913,0.261914,163.920026,11265942.659158
m4,0.27042,0.121534,0.077694,0.087921,0.175535,0.277497,182.833951,11257180.35717
m5,0.262866,0.114291,0.071899,0.094127,0.181895,0.281097,174.371622,11101741.041978
m6,0.267534,0.1028,0.06147,0.079198,0.156182,0.241094,168.383213,11361318.667153
m7,0.314981,0.141711,0.092691,0.091155,0.182641,0.295874,161.688502,10976401.494479
m8,0.274634,0.103853,0.058248,0.080932,0.156171,0.235364,168.342295,11544655.456348
m9,0.25052,0.103777,0.06578,0.091079,0.179535,0.281211,192.867701,11187164.79096
m10,0.290175,0.11775,0.068248,0.080308,0.157594,0.240676,166.848011,11221516.342561
m11,0.271754,0.115524,0.069097,0.086376,0.168393,0.259706,175.137377,11856050.746585
m12,0.256953,0.095927,0.05577,0.084397,0.163436,0.248904,181.36104,11344755.742303

### Con los índices calculados de forma trimestral calculamos un índice promedio trimestral ponderado por la suma de los factores en el mes

In [77]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [78]:
valuores = ['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio']
trimestres = {
    't1': ['m1', 'm2', 'm3'],
    't2': ['m4', 'm5', 'm6'], 
    't3': ['m7', 'm8', 'm9'],
    't4': ['m10', 'm11', 'm12']
}

for trimestre, mes in trimestres.items():
    datos_trimestre = datos_final_mensual.loc[mes]
    weights = datos_trimestre['factor']
    
    # Calcula promedio ponderado
    weighted_avgs = (datos_trimestre[valuores].multiply(weights, axis=0)).sum() / weights.sum()
    datos_final.loc[trimestre, valuores] = weighted_avgs

In [79]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.277296,0.117978,0.075067,0.095431,0.18754,0.290012,192.183867
t2,0.266961,0.112837,0.07032,0.087025,0.171108,0.266417,175.179022
t3,0.279769,0.116155,0.071963,0.087628,0.172545,0.270284,174.315172
t4,0.272881,0.109791,0.064428,0.083745,0.163239,0.249942,174.48625

### Inserta los cálculos en la base final

In [80]:
indices = pd.read_csv("indices.csv", encoding='latin-1')

In [81]:
ano = 2022
# Asegurar que el índice de datos_final coincide con trimestres 1..4
datos_final = datos_final.copy()
datos_final["trimestre"] = [1, 2, 3, 4]
datos_final["Año"] = ano

# Reemplazar en indices usando mask
for col in ["fgt0","fgt1","fgt2","a25","a50","a75","ingreso_promedio"]:
    indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1581573299.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.2772959742209305 0.26696093662694237 0.27976915789934464
 0.27288121957496014]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1581573299.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.11797800921564558 0.11283737875335086 0.11615531937158309
 0.10979104810677948]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1581573299.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.07506678539244437 0.0703197134612638 0.07196331231257545
 0.06442796809155679]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1581573299.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.09543120793883764 0.08702530836774844 0.0876281547677856
 0.08374543573403824]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1581573299.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.18753962323880177 0.17110798340532443 0.17254472488505282
 0.16323877482992966]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1581573299.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.290012463536841 0.2664167901995058 0.2702838053697325
 0.24994236897196417]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21944\1581573299.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[192.1838667921891 175.1790223120162 174.31517170971588 174.4862496737559]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

In [82]:
indices.to_csv('indices.csv', encoding='latin-1', index=None)