In [121]:
import numpy as np
import pandas as pd

# Plantilla

Es necesario ajustar las definiciones, las fuentes de los datos y posiblemente definiciones si la ENEMDU tiene una dimensión geográfica y temporal al mismo tiempo

Ahora hay bases por mes, entonces calculamos para cada mes

In [122]:
data1 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m3\data_orig\Stata\enero2008_per.dta", convert_categoricals=False) # para bases de stata
data2 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m3\data_orig\Stata\febrero2008_per.dta", convert_categoricals=False) # para bases de stata
data3 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m3\data_orig\Stata\marzo2008_per.dta", convert_categoricals=False) # para bases de stata

data4 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m6\data_orig\Stata\abril2008_per.dta", convert_categoricals=False) # para bases de stata
data5 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m6\data_orig\Stata\mayo2008_per.dta", convert_categoricals=False) # para bases de stata
data6 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m6\data_orig\Stata\junio2008_per.dta", convert_categoricals=False) # para bases de stata

data7 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m9\data_orig\Stata\julio2008_per.dta", convert_categoricals=False) # para bases de stata
data8 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m9\data_orig\Stata\agosto2008_per.dta", convert_categoricals=False) # para bases de stata
data9 = pd.read_stata(r"Z:\survey\ECU\ENEMDU\2008\m9\data_orig\Stata\septiembre2008_per.dta", convert_categoricals=False) # para bases de stata

data10 = pd.read_spss(r"Z:\survey\ECU\ENEMDU\2008\m12\data_orig\Spss\octubre1008_per.sav", convert_categoricals=False) # para bases de stata
data11 = pd.read_spss(r"Z:\survey\ECU\ENEMDU\2008\m12\data_orig\Spss\noviembre2008_per.sav", convert_categoricals=False) # para bases de stata
data12 = pd.read_spss(r"Z:\survey\ECU\ENEMDU\2008\m12\data_orig\Spss\diciembre2008_per.sav", convert_categoricals=False) # para bases de stata

## Revisar los datos

| enero   | febrero | marzo   | abril   | mayo    | junio   | julio   | agosto  | septiembre | octubre | noviembre | diciembre |
|---------|---------|---------|---------|---------|---------|---------|---------|------------|---------|-----------|-----------|
| area    | area    | area    | area    | area    | area    | area    | area    | area       | area    | area      | area      |
| ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad  | ciudad     | ciudad  | ciudad    | ciudad    |
| zona    | zona    | zona    | zona    | zona    | zona    | zona    | zona    | zona       | zona    | zona      | zona      |
| sector  | sector  | sector  | sector  | sector  | sector  | sector  | sector  | sector     | sector  | sector    | sector    |
| panelm  | panelm  | panelm  | panelm  | panelm  | panelm  | panelm  | panelm  | panelm     | panelm  | panelm    | panelm    |
| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda   | vivienda| vivienda  | vivienda  |
| hogar   | hogar   | hogar   | hogar   | hogar   | hogar   | hogar   | hogar   | hogar      | hogar   | hogar     | hogar     |
| p02     | p02     | p02     | p02     | p02     | p02     | p02     | p02     | p02        | p02     | p02       | p02       |
| p03     | p03     | p03     | p03     | p03     | p03     | p03     | p03     | p03        | p03     | p03       | p03       |
| p66     | p66     | p66     | p66     | p66     | p66     | p66     | p66     | p66        | p66     | p66       | p66       |
| fexp    | fexp    | fexp    | fexp    | fexp    | fexp    | fexp    | fexp    | fexp       | fexp    | fexp      | fexp      |
| p20     | p20     | p20     | p20     | p20     | p20     | p20     | p20     | p20        | p20     | p20       | p20       |

En esta encuesta tenemos una base para cada mes, esto cambia la lógica que habíamos tenido hasta ahora así que de aquí en adelante cambiamos algo del código, mantenemos de acuerdo a las etiquetas de las variables p66 como la variable de ingreso laboral monetario de la actividad principal asalariada para mantener la concordancia con el resto de los años.

Elegimos hacer los cálculos en las bases mensuales para poder usar la representatividad mensual, con un promedio simple debería bastar para tener el resultado del trimestre

Ahora usamos p20 que pregunta si trabajo la semana pasada, si se cumple vamos a asumir que trabajo durante todo el mes, ahora en adelante capturaremos incluso de mejor forma el mercado laboral, mantenemos la idea de que si el individuo trabajo recibe su ingreso laboral reportado.

In [123]:
columnas = ['area', 'ciudad', 'zona', 'sector', 'panelm',
            'vivienda', 'hogar', 'p02', 'p03', 'p66', 'p20',
            'fexp']

In [124]:
columnas_upper = [x.upper() for x in columnas]

Filtramos solo las columnas de interés para alivar el peso en la memoria

In [125]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base = base[columnas]

for base in [data10, data11, data12]:
    base = base[columnas_upper]

Creamos una variable de ingreso laboral que es igual al ingreso por asalariado y limpiamos según los valores de ingrl, para mantener ambas variables para cada base consistente

In [126]:
data1['p66'] = pd.to_numeric(data1['p66'], errors='coerce')
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x > 6000 else x)
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x < 0 else x)

data2['p66'] = pd.to_numeric(data2['p66'], errors='coerce')
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x > 6500 else x)
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x < 0 else x)

data3['p66'] = pd.to_numeric(data3['p66'], errors='coerce')
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x > 6800 else x)
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x < 0 else x)

data4['p66'] = pd.to_numeric(data4['p66'], errors='coerce')
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x > 3800 else x)
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x < 0 else x)

data5['p66'] = pd.to_numeric(data5['p66'], errors='coerce')
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x > 6000 else x)
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x < 0 else x)

data6['p66'] = pd.to_numeric(data6['p66'], errors='coerce')
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x > 7000 else x)
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x < 0 else x)

data7['p66'] = pd.to_numeric(data7['p66'], errors='coerce')
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x > 7000 else x)
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x < 0 else x)

data8['p66'] = pd.to_numeric(data8['p66'], errors='coerce')
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x > 8000 else x)
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x < 0 else x)

data9['p66'] = pd.to_numeric(data9['p66'], errors='coerce')
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x > 7000 else x)
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x < 0 else x)

data10['P66'] = pd.to_numeric(data10['P66'], errors='coerce')
data10['P66'] = data10['P66'].apply(lambda x: np.nan if x > 4500 else x)
data10['P66'] = data10['P66'].apply(lambda x: np.nan if x < 0 else x)

data11['P66'] = pd.to_numeric(data11['P66'], errors='coerce')
data11['P66'] = data11['P66'].apply(lambda x: np.nan if x > 4000 else x)
data11['P66'] = data11['P66'].apply(lambda x: np.nan if x < 0 else x)

data12['P66'] = pd.to_numeric(data12['P66'], errors='coerce')
data12['P66'] = data12['P66'].apply(lambda x: np.nan if x > 7000 else x)
data12['P66'] = data12['P66'].apply(lambda x: np.nan if x < 0 else x)

In [127]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['ingr'] = base['p66']

for base in [data10, data11, data12]:
    base['ingr'] = base['P66']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4126663853.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr'] = base['p66']

Ingreso mensual asumiendo que las personas reciben el mismo valor reportado en 'ingr' siempre que reportan estar ocupados la semana pasada, de acuerdo a la variable 'trabajo'

In [128]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['ingr'] = base.apply(lambda x: x['ingr'] if x['p20'] == 1 else np.nan, axis=1)

for base in [data10, data11, data12]:
    base['ingr'] = base.apply(lambda x: x['ingr'] if x['P20'] == 1 else np.nan, axis=1)

## Deflactamos y transformamos el ingreso

Esto deja todo en dólares constantes de 2014

In [129]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 2008]
datos_base = data_externa[data_externa['Año'] == 2014]

Diccionarios de ipc

In [130]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_base.iterrows()
     }

### Creamos identificadores para las ciudades siguiendo los códigos del INEC y para los trimestres

In [131]:
# Corregimos los códigos para usarlos cómo texto
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['ciudad'] = base['ciudad'].apply(str)
    base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)
    base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

for base in [data10, data11, data12]:
    base['ciudad'] = base['CIUDAD'].apply(str)
    base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)
    base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\697387645.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

Diccionario ciudades disponibles

In [132]:
parroquia_dict = {
    '0101': 'Cuenca',
    '0901': 'Guayaquil',
    '0801': 'Esmeraldas',
    '0701': 'Machala',
    '1308': 'Manta',
    '1701': 'Quito',
    '1101': 'Loja',
    '1801': 'Ambato'
}

def get_parroquia(codigo):
    if codigo in parroquia_dict:
        return parroquia_dict[codigo]
    elif codigo[:2] in ['01', '02', '03', '04', '05', '06', '10', '11', '17', '18']:
        return 'Sierra'
    elif codigo[:2] in ['07', '08', '09', '12', '13', '23', '24']:
        return 'Costa'
    else:
        return 'Nacional'

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3074031309.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)

In [133]:
data5['ciudad_asignada'].value_counts()

ciudad_asignada
Guayaquil    4381
Quito        3116
Cuenca       2488
Machala      2413
Ambato       2176
Name: count, dtype: int64

### Asignamos el ipc correspondiente según ciudad correspondiente

$\begin{equation}
    ingr_{USD-base-2014}^{i} = ingr_{dólares}^{i}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Desde 2000 en adelante ya no es necesario utilizar el tipo de cambio debido al cambio de moneda

In [134]:
# Función que asigna valores correspondientes
def asigna_ipc(fila, trimestre):
    return ipc_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila, trimestre):
    return ipc_base_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

In [135]:
data1['ipc'] = data1.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data1['ipc_base'] = data1.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data2['ipc'] = data2.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data2['ipc_base'] = data2.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data3['ipc'] = data3.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data3['ipc_base'] = data3.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data4['ipc'] = data4.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data4['ipc_base'] = data4.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data5['ipc'] = data5.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data5['ipc_base'] = data5.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data6['ipc'] = data6.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data6['ipc_base'] = data6.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data7['ipc'] = data7.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data7['ipc_base'] = data7.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data8['ipc'] = data8.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data8['ipc_base'] = data8.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data9['ipc'] = data9.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data9['ipc_base'] = data9.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data10['ipc'] = data10.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data10['ipc_base'] = data10.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data11['ipc'] = data11.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data11['ipc_base'] = data11.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data12['ipc'] = data12.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data12['ipc_base'] = data12.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data1['ipc'] = data1.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data1['ipc_base'] = data1.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data2['ipc'] = data2.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data2['ipc_base'] = data2.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data3['ipc'] = data3.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data3['ipc_base'] = data3.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data4['ipc'] = data4.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data4['ipc_base'] = data4.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data5['ipc'] = data5.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data5['ipc_base'] = data5.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data6['ipc'] = data6.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data6['ipc_base'] = data6.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data7['ipc'] = data7.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data7['ipc_base'] = data7.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data8['ipc'] = data8.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data8['ipc_base'] = data8.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data9['ipc'] = data9.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\2802951969.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data9['ipc_base'] = data9.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

In [136]:
# Calculamos el deflactor
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['def'] = (base['ipc_base'] / base['ipc'])

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1671624327.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['def'] = (base['ipc_base'] / base['ipc'])

In [137]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_r'] = base['ingr'] * base['def']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3754981744.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_r'] = base['ingr'] * base['def']

In [138]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_r'].mean())

517.7684129910175
390.54343158166904
386.63089421668343
386.53164659470366
417.44508332661604
349.0727982126179
402.2177189011358
397.18042643660755
393.24889164380386
414.3335153804606
413.64455590646867
324.613965434477

## Calculo ingreso de los hogares

In [139]:
columnas_idef = ['area', 'ciudad', 'zona', 'sector', 'vivienda',
       'hogar']
columnas_idef_upper = [x.upper() for x in columnas_idef]

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)

for base in [data10, data11, data12]:
    base['idef_hogar'] = base[columnas_idef_upper].astype(str).agg(''.join, axis=1)

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['idef_hogar'].nunique())

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1542101142.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['idef_hogar'] = base[columnas_idef].astype(str).agg(''.join, axis=1)

1215
1220
2136
1238
1280
3211
1273
1333
3791
1256
1217
6162

Si todos los miembros del hogar tienen NA como ingreso, mantener NA, si al menos uno tiene un ingreso sumamos para el ingreso del hogar, así evitamos subestimar el ingreso del hogar si tenemos valores perdidos

In [140]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [141]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1636345169.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)

In [142]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_h'].mean())

1859.121370752483
1435.784448471765
1387.082631612204
1499.7409112081843
1569.146492791128
1252.0044813091854
1559.318838704087
1451.3793939790291
933.0874325680371
1589.47179408485
1617.365984073918
1161.2075055246266

## Sacamos edades negativas y mayores a 100 años

Transformamos las variables de edad a numericas para evitar problemas

In [143]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    base['edad'] = pd.to_numeric(base['p03'], errors='coerce')

for base in [data10, data11, data12]:
    base['edad'] = pd.to_numeric(base['P03'], errors='coerce')

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1012421227.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['edad'] = pd.to_numeric(base['p03'], errors='coerce')

In [144]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base = base.loc[(base['edad'] >= 0) & (base['edad'] < 100)]

## Ingreso individual descontando cargas familiares

Utilizando la metodología del autor dividimos el ingreso del hogar para la escala $(A_{i}+kC_{i})^{s}$ donde $A_{i}$ es al número de adultos, $C_{i}$ es el número de niños en el hogar $i$. $k$ es el costo en recursos de cada niño y $s$ busca reflejar las restricciones

In [145]:
k = 0.4
s = 0.9

In [146]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    # Si es necesario calcular el número de niños
    base['es_nino'] = base['edad'] < 10 
    base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')

    # Si es necesario calcular el número de adultos
    base['es_adulto'] = base['edad'] > 10
    base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_nino'] = base['edad'] < 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['es_adulto'] = base['edad'] > 10
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\3602317441.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')

In [147]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['escala'] = (base['adultos'] + k * base['ninos']) ** s

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\4179537099.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['escala'] = (base['adultos'] + k * base['ninos']) ** s

In [148]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_t'] = base['ingr_h'] / base['escala']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1010359397.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['ingr_t'] = base['ingr_h'] / base['escala']

In [149]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
        print(base['ingr_t'].mean())

199.71078638244003
151.12813954547306
144.70619825918152
154.4592666187294
168.809501528838
131.3317446861637
165.46187078951402
161.49842453150214
157.80827429697678
167.10923569659198
164.30928908708452
117.15133188940445

## Umbrales de pobreza

Incluimos los índices de pobreza si es posible a nivel regional para luego poder utilizar de mejor forma el factor de expansión

$\begin{equation}
    umbral_{USD-base-2014}^{i} = umbral_{año}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

Diccionario de umbral

In [150]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

## Cálculo del índice de pobreza de Foster, Greer y Thorbecke

Para calcular un ínidce de pobreza se utiliza a Foster, Greer y Thorbecke (1984), ya que satisface algunas caracterísitcas de distribución que son positivas e igual a las enunciadas por Sen, el autor usa el mismo índice.

$\begin{equation}FGT_{\alpha} = \frac{1}{N}\sum_{i=1}^{H}\left(\frac{z-y_{i}}{z}\right)^{\alpha}\end{equation}$

Donde $z$ es el umbral de pobreza, $N$ es el número de personas en la economía, $H$ es el número de pobres (personas debajo de la línea de pobreza) $y_{i}$ es el ingreso de cada individuo. Mientras mayor es el valor de $\alpha$ mayor es el peso de los individuos más pobres, mayor $FGT$ mayor pobreza en la economía.

En este caso los umbrales están anivel nacional, aún así buscamos calcular la pobreza por región y sacar un promedio ponderado por región para la pobreza nacional, con el objetivo de hacerlo más específico

In [151]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
        base['persona_fexp'] = 1 * base['fexp']

for base in [data10, data11, data12]:
        base['persona_fexp'] = 1 * base['FEXP']

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\425030869.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['persona_fexp'] = 1 * base['fexp']

In [152]:
def trimestre(base):
    """Returns quarter number based on dataframe identity."""
    trimestre_1 = [data1, data2, data3]
    trimestre_2 = [data4, data5, data6]
    trimestre_3 = [data7, data8, data9]
    trimestre_4 = [data10, data11, data12]

    if any(base is df for df in trimestre_1):
        return 1
    elif any(base is df for df in trimestre_2):
        return 2
    elif any(base is df for df in trimestre_3):
        return 3
    elif any(base is df for df in trimestre_4):
        return 4
    else:
        return print("Problema")

In [153]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    
    t = trimestre(base)
    base['pobres_t'] = (
        (base['ingr_t'] - umbral_dict.get(trimestre(base)) < 0
    ).astype(int))

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\511293179.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  base['pobres_t'] = (

In [154]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9]:
    print(f"pobreza : ", (base['pobres_t'] * base['fexp']).sum()/base.loc[base['ingr_t'] >= 0]['persona_fexp'].sum())

for base in [data10, data11, data12]:
    print(f"pobreza : ", (base['pobres_t'] * base['FEXP']).sum()/base.loc[base['ingr_t'] >= 0]['persona_fexp'].sum())

pobreza :  0.21137256730802487
pobreza :  0.23407272694838
pobreza :  0.3280533291812781
pobreza :  0.2384994225659192
pobreza :  0.24063345347333698
pobreza :  0.38895251283620935
pobreza :  0.19305166263114076
pobreza :  0.21446564140564656
pobreza :  0.3203653847969716
pobreza :  0.20509824729967174
pobreza :  0.2160707890572422
pobreza :  0.3920396659470984

In [155]:
# Calculamos los índices por mes, luego buscaremos la manera de sacar los indices trimestrales como un promedio ponderado de los meses
datos_final_mensual = pd.DataFrame(index=[f'm{x+1}' for x in range(12)], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio', 'factor'])

In [156]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9]

for idx, base in enumerate(datasets, start=1):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp['ingr_t'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[trimestre(base)] - df_temp['ingr_t']) / umbral_dict[trimestre(base)]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total

    # Assign to the corresponding row: data1→m1, data2→m2, etc.
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['fgt0','fgt1','fgt2']] = [fgt0, fgt1, fgt2]

datasets = [data10, data11, data12]

for idx, base in enumerate(datasets, start=10):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp['ingr_t'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[trimestre(base)] - df_temp['ingr_t']) / umbral_dict[trimestre(base)]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['FEXP'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['FEXP']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['FEXP']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['FEXP']).sum() / peso_total

    # Assign to the corresponding row: data1→m1, data2→m2, etc.
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['fgt0','fgt1','fgt2']] = [fgt0, fgt1, fgt2]

In [157]:
datos_final_mensual

         fgt0      fgt1      fgt2  a25  a50  a75 ingreso_promedio factor
m1   0.223931  0.081726  0.044404  NaN  NaN  NaN              NaN    NaN
m2   0.253224  0.079236  0.039897  NaN  NaN  NaN              NaN    NaN
m3   0.346156  0.118547  0.062342  NaN  NaN  NaN              NaN    NaN
m4   0.260191  0.073156  0.033676  NaN  NaN  NaN              NaN    NaN
m5   0.253949  0.086885  0.048524  NaN  NaN  NaN              NaN    NaN
m6   0.406643  0.165287  0.097094  NaN  NaN  NaN              NaN    NaN
m7   0.196699  0.067073  0.034825  NaN  NaN  NaN              NaN    NaN
m8   0.223054  0.074917  0.038522  NaN  NaN  NaN              NaN    NaN
m9   0.331645   0.12747  0.072239  NaN  NaN  NaN              NaN    NaN
m10  0.205098  0.067001  0.033702  NaN  NaN  NaN              NaN    NaN
m11  0.216071  0.075909    0.0388  NaN  NaN  NaN              NaN    NaN
m12   0.39204  0.165423  0.096817  NaN  NaN  NaN              NaN    NaN

## Calculo del índice de desigualdad de Atkinson

Vamos a calcular el índice de desigualdad de atkinson con un parámetro $\epsilon$ de aversión a la desigualdad y un $\mu$ que es igual a la media de los ingresos individuales, con la siguiente fórmula.

$\begin{equation}A = 1-\frac{1}{\mu}\left(\frac{1}{N}\sum_{i=1}^{N}y^{1-\epsilon}\right)^{1/(1-\epsilon)}\end{equation}$

Donde $y_{i}$ es el ingreso individual y $\mu$ es el ingreso medio

In [158]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9]

for idx, base in enumerate(datasets, start=1):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()

    # Ingreso promedio ponderado
    mu = (df_temp['ingr_t'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp['ingr_t']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['a25','a50','a75']] = [a25, a50, a75]

datasets = [data10, data11, data12]

for idx, base in enumerate(datasets, start=10):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['FEXP'].sum()

    # Ingreso promedio ponderado
    mu = (df_temp['ingr_t'] * df_temp['FEXP']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp['ingr_t']**(1-i) * df_temp['FEXP']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['a25','a50','a75']] = [a25, a50, a75]

In [159]:
datos_final_mensual

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,factor
m1,0.223931,0.081726,0.044404,0.086328,0.167346,0.243445,NaN,NaN
m2,0.253224,0.079236,0.039897,0.065164,0.12657,0.188585,NaN,NaN
m3,0.346156,0.118547,0.062342,0.072934,0.141444,0.209727,NaN,NaN
m4,0.260191,0.073156,0.033676,0.05998,0.11655,0.170557,NaN,NaN
m5,0.253949,0.086885,0.048524,0.074538,0.145921,0.220426,NaN,NaN
m6,0.406643,0.165287,0.097094,0.084587,0.164998,0.247133,NaN,NaN
m7,0.196699,0.067073,0.034825,0.060465,0.118538,0.177362,NaN,NaN
m8,0.223054,0.074917,0.038522,0.065631,0.128212,0.190637,NaN,NaN
m9,0.331645,0.12747,0.072239,0.084784,0.165441,0.250357,NaN,NaN
m10,0.205098,0.067001,0.033702,0.058143,0.114903,0.174023,NaN,NaN
m11,0.216071,0.075909,0.0388,0.060839,0.119228,0.176825,NaN,NaN
m12,0.39204,0.165423,0.096817,0.075844,0.149243,0.224098,NaN,NaN

Guardamos el ingreso promedio

In [160]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9]

for idx, base in enumerate(datasets, start=1):
    df_temp = base.loc[base['ingr_t'] >= 0].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp['ingr_t'] * df_temp['fexp']).sum() / peso_total
    factor = df_temp['fexp'].sum()
    
    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['ingreso_promedio', 'factor']] = [media_ponderada, factor] 

datasets = [data10, data11, data12]

for idx, base in enumerate(datasets, start=10):
    df_temp = base.loc[base['ingr_t'] >= 0].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['FEXP'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp['ingr_t'] * df_temp['FEXP']).sum() / peso_total
    factor = df_temp['FEXP'].sum()
    
    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['ingreso_promedio', 'factor']] = [media_ponderada, factor]

In [162]:
datos_final_mensual

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,factor
m1,0.223931,0.081726,0.044404,0.086328,0.167346,0.243445,209.265481,4384161.023179
m2,0.253224,0.079236,0.039897,0.065164,0.12657,0.188585,160.148499,4394526.230219
m3,0.346156,0.118547,0.062342,0.072934,0.141444,0.209727,143.54963,8755756.896586
m4,0.260191,0.073156,0.033676,0.05998,0.11655,0.170557,162.200983,4417321.655458
m5,0.253949,0.086885,0.048524,0.074538,0.145921,0.220426,173.623682,4400706.6691
m6,0.406643,0.165287,0.097094,0.084587,0.164998,0.247133,129.904542,12669783.333024
m7,0.196699,0.067073,0.034825,0.060465,0.118538,0.177362,173.503032,4399797.200558
m8,0.223054,0.074917,0.038522,0.065631,0.128212,0.190637,172.460032,4387364.448553
m9,0.331645,0.12747,0.072239,0.084784,0.165441,0.250357,157.703797,8146908.892666
m10,0.205098,0.067001,0.033702,0.058143,0.114903,0.174023,175.601189,4471151.544239
m11,0.216071,0.075909,0.0388,0.060839,0.119228,0.176825,174.118848,4488270.269814
m12,0.39204,0.165423,0.096817,0.075844,0.149243,0.224098,128.97651,12996873.451673

### Con los índices calculados de forma trimestral calculamos un índice promedio trimestral ponderado por la suma de los factores en el mes

In [163]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [165]:
valuores = ['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio']
trimestres = {
    't1': ['m1', 'm2', 'm3'],
    't2': ['m4', 'm5', 'm6'], 
    't3': ['m7', 'm8', 'm9'],
    't4': ['m10', 'm11', 'm12']
}

for trimestre, mes in trimestres.items():
    datos_trimestre = datos_final_mensual.loc[mes]
    weights = datos_trimestre['factor']
    
    # Calcula promedio ponderado
    weighted_avgs = (datos_trimestre[valuores].multiply(weights, axis=0)).sum() / weights.sum()
    datos_final.loc[trimestre, valuores] = weighted_avgs

In [172]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.292305,0.099488,0.052231,0.074336,0.144192,0.212859,164.140704
t2,0.345265,0.130291,0.07411,0.077471,0.151131,0.225921,145.497515
t3,0.268449,0.098162,0.053783,0.073503,0.143609,0.215919,165.631862
t4,0.318,0.127082,0.072105,0.069172,0.136114,0.204237,147.699023

### Inserta los cálculos en la base final

In [173]:
indices = pd.read_csv("indices.csv", encoding='latin-1')

In [174]:
ano = 2008
# Asegurar que el índice de datos_final coincide con trimestres 1..4
datos_final = datos_final.copy()
datos_final["trimestre"] = [1, 2, 3, 4]
datos_final["Año"] = ano

# Reemplazar en indices usando mask
for col in ["fgt0","fgt1","fgt2","a25","a50","a75","ingreso_promedio"]:
    indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1782966650.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.2923049889304853 0.3452646768888479 0.2684492942399367
 0.31799988503003496]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1782966650.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.0994883383485269 0.13029094740340655 0.09816206541527041
 0.1270820932278637]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1782966650.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.05223145315466201 0.07410994151316672 0.05378268748848695
 0.07210460501607717]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1782966650.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.07433564981368046 0.07747051315388706 0.07350328832337355
 0.06917216662003767]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1782966650.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.14419243621739822 0.15113120614548706 0.14360929481002188
 0.136114427491948]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1782966650.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.21285910686451004 0.225921349127801 0.215918676282482
 0.2042373669987289]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_18740\1782966650.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[164.14070428152678 145.4975153977114 165.63186221057262
 147.69902290766223]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

In [175]:
indices.to_csv('indices.csv', encoding='latin-1', index=None)