In [1]:
import numpy as np
import pandas as pd

# Plantilla

Es necesario ajustar las definiciones, las fuentes de los datos y posiblemente definiciones si la ENEMDU tiene una dimensión geográfica y temporal al mismo tiempo

In [2]:
# data = pd.read_stata(r"Z:\harmonized\ECU\ENEMDU\data_arm\ECU_1990m11_BID.dta") # para bases de stata
data = pd.read_stata(r"datos/ECU_2007m12_BID.dta", convert_categoricals=False) # para bases de stata

In [3]:
df, meta = pd.read_stata(r"datos/ECU_2007m12_BID.dta", iterator=True), None
meta = df.variable_labels()
print("\nVariable labels:")
for col, label in meta.items():
    print(f"{col}: {label}")

Variable labels:
region_BID_c: Regiones BID
region_c: division politico-administrativa, provincia
pais_c: Nombre del PaÃ­s
anio_c: Anio de la encuesta
mes_c: Mes de la encuesta
zona_c: Zona del pais
factor_ch: Factor de expansion del hogar
idh_ch: ID del hogar
idp_ci: ID de la persona en el hogar
factor_ci: Factor de expansion del individuo
sexo_ci: Sexo del individuo
edad_ci: Edad del individuo en aÃ±os
relacion_ci: Relacion o parentesco con el jefe del hogar
civil_ci: Estado civil
jefe_ci: Jefe/a de hogar
nconyuges_ch: # de conyuges en el hogar
nhijos_ch: # de hijos en el hogar
notropari_ch: # de otros familiares en el hogar
notronopari_ch: # de no familiares en el hogar
nempdom_ch: # de empleados domesticos
clasehog_ch: Tipo de hogar
nmiembros_ch: # de miembros en el hogar
miembros_ci: =1: es miembro del hogar
nmayor21_ch: # de familiares mayores a 21 anios en el hogar
nmenor21_ch: # de familiares menores a 21 anios en el hogar
nmayor65_ch: # de familiares mayores a 65 anios en el hogar
nmenor6_ch: # de familiares menores a 6 anios en el hogar
nmenor1_ch: # de familiares menores a 1 anio en el hogar
condocup_ci: Condicion de ocupaciÃ³n de acuerdo a def armonizada para cada pais
categoinac_ci: CondiciÃ³n de inactividad
emp_ci: =1: si ocupado (empleado)
cesante_ci: Desocupado cesante-trabajo anteriormente
desemp_ci: Desempleado que buscÃ³ empleo en el periodo de referencia
subemp_ci: Personas en subempleo por horas (<30 horas y dispuestas a trabajar +)
durades_ci: Duracion del desempleo en meses
pea_ci: PoblaciÃ³n EconÃ³micamente Activa
nempleos_ci: # de empleos
antiguedad_ci: Antiguedad en la actividad actual
desalent_ci: Trabajadores desalentados: creen q no conseguiran trabajo
horaspri_ci: Horas trabajadas en la actividad principal
horastot_ci: Horas trabajadas semanalmente en todos los empleos
tiempoparc_ci: Personas que trabajan medio tiempo (<30 horas y NO dispuestas a trabajar +)
categopri_ci: Categoria ocupacional en la actividad principal
categosec_ci: Categoria ocupacional en la actividad secundaria
rama_ci: Rama de actividad laboral de la ocupacion principal-Grandes Divisiones (ISIC Rev
spublico_ci: =1: Personas que trabajan en el sector pÃºblico
tamemp_ci: # empleados en la empresa segun rangos
cotizando_ci: Cotizante a la Seguridad Social (SS)
instcot_ci: Institucion a la cual cotiza o es afiliado - variable original de cada pais
afiliado_ci: Afiliado a la Seguridad Social
formal_ci: Formalidad Laboral
tipocontrato_ci: Tipo de contrato segun su duracion
ocupa_ci: Ocupacion laboral en la actividad principal
pension_ci: =1: Recibe pension contributiva
pensionsub_ci: =1: recibe pension subsidiada / no contributiva
tipopen_ci: Tipo de pension - variable original de cada pais
instpen_ci: Institucion proveedora de la pension - variable original de cada pais
ylmpri_ci: Ingreso laboral monetario actividad principal
ylnmpri_ci: Ingreso laboral NO monetario actividad principal
ylmsec_ci: Ingreso laboral monetario segunda actividad
ylnmsec_ci: Ingreso laboral NO monetario actividad secundaria
ylmotros_ci: Ingreso laboral monetario de otros trabajos
ylnmotros_ci: Ingreso laboral NO monetario de otros trabajos
ylm_ci: Ingreso laboral monetario total individual
ylnm_ci: Ingreso laboral NO monetario total individual
ynlm_ci: Ingreso no laboral monetario total individual
ynlnm_ci: Ingreso no laboral no monetario total individual
nrylmpri_ci: ID de no respuesta ingreso de la actividad principal
ylm_ch: Ingreso laboral monetario del hogar
ylnm_ch: Ingreso laboral no monetario del hogar
ylmnr_ch: Ingreso laboral monetario del hogar con missing en NR
ynlm_ch: Ingreso no laboral monetario del hogar
ynlnm_ch: Ingreso no laboral no monetario del hogar
ylmhopri_ci: Salario monetario horario de la actividad principal
ylmho_ci: Salario monetario horario de todas las actividades
nrylmpri_ch: Hogares con algÃºn miembro que no respondiÃ³ por ingresos
remesas_ci: Remesas mensuales reportadas por el individuo
remesas_ch: Remesas mensuales del hogar
ypen_ci: Monto de ingreso por pension contributiva
ypensub_ci: Monto de ingreso por pension subsidiada / no contributiva
aedu_ci: Anios de educacion aprobados
eduui_ci: Superior incompleto
eduuc_ci: Superior completo
edupre_ci: Educacion preescolar
eduac_ci: Superior universitario vs superior no universitario
asiste_ci: =1 si asiste actualmente a la escuela
edupub_ci: Asiste a un centro de ensenanza pÃºblico
pqnoasis1_ci: Razones para no asistir a la escuela-variable armonizada
asispre_ci: Asiste a educacion prescolar
luz_ch: La principal fuente de iluminaciÃ³n es electricidad
luzmide_ch: Usan medidor para pagar consumo de electricidad
combust_ch: Principal combustible gas o electricidad
piso_ch: Materiales de construcciÃ³n del piso
pared_ch: Materiales de construcciÃ³n de las paredes
techo_ch: techo_ch
resid_ch: MÃ©todo de eliminaciÃ³n de residuos
dorm_ch: # de habitaciones exclusivas para dormir
cuartos_ch: # Habitaciones en el hogar
cocina_ch: Cuarto separado y exclusivo para cocinar
telef_ch: El hogar tiene servicio telefÃ³nico fijo
refrig_ch: El hogar posee refrigerador o heladera
freez_ch: El hogar posee freezer o congelador
auto_ch: El hogar posee automovil particular
compu_ch: El hogar posee computador
internet_ch: El hogar posee conexiÃ³n a internet
cel_ch: El hogar tiene servicio telefonico celular
vivi1_ch: Tipo de vivienda en la que reside el hogar
vivi2_ch: =1: la vivienda es casa o departamento
viviprop_ch: Propiedad de la vivienda
vivitit_ch: El hogar posee un tÃ­tulo de propiedad
vivialq_ch: Alquiler mensual
vivialqimp_ch: Alquiler mensual imputado
aguared_ch: Acceso a fuente de agua por red
aguafconsumo_ch:
aguafuente_ch:
aguadist_ch: UbicaciÃ³n de la principal fuente de agua
aguadisp1_ch:
aguadisp2_ch:
aguatrat_ch:
aguamala_ch: Agua unimproved segÃºn MDG
aguamejorada_ch: El hogar tiene acceso a agua potable de fuente mejorada
aguamide_ch: Usan medidor para pagar consumo de agua
bano_ch: El hogar tiene servicio sanitario
banoex_ch: El servicio sanitario es exclusivo del hogar
banomejorado_ch: El hogar tiene acceso a saneamiento de fuente mejorada
sinbano_ch:
migrante_ci: =1 si es migrante
migrantiguo5_ci: =1 si es migrante antiguo (5 anos o mas)
miglac_ci: =1 si es migrante proveniente de un pais LAC
salmm_ci: Salario minimo legal a precios corrientes
lp19_2011: LÃ­nea de pobreza extrema (WB) USD 1.9 per capita, PPP 2011
lp31_2011: LÃ­nea de pobreza extrema USD 3.1 per capita, PPP 2011
lp5_2011: LÃ­nea de pobreza moderada USD 5 per capita, PPP 2011
lp_ci: Linea de pobreza oficial del pais en moneda local a precios corrientes
lpe_ci: Linea de indigencia oficial del pais en moneda local a precios corrientes
lp365_2017: LÃ­nea de pobreza extrema USD 3.1 per capita, moneda local PPP 2017
lp685_2017: LÃ­nea de pobreza moderada USD 6.85 per capita, moneda local PPP 2017
lp14_2017: LÃ­nea de vulnerabilidad USD 14.15 per capita, moneda local PPP 2017
lp81_2017: LÃ­nea de clase media USD 81.22 per capita, moneda local PPP 2017
tc_c: Tipo de cambio oficial (aÃ±o de la encuesta)
cpi_c: Ãndice de precios al consumidor (aÃ±o de la encuesta)
cpi2011: Ãndice de precios al consumidor (2011)
cpi2017: Ãndice de precios al consumidor (2017)
ratio_cpi2011: Tasa de Ã­ndice de precios al consumidor (CPI_actual/CPI_2011)
ratio_cpi2017: Tasa de Ã­ndice de precios al consumidor (CPI_actual/CPI_2017)
ppp_c: Poder de paridad adquisitivo (aÃ±o de la encuesta)
ppp_2011: Poder de paridad adquisitivo (PPP) 2011
ppp_2017: Poder de paridad adquisitivo (PPP) 2017
area: area
ciudad: ciudad
zona: zona
sector: sector
panelm: panel
vivienda: vivienda
hogar: hogar
p01: 1. persona
p02: 2. sexo
p03: 3. edad
p04: 4. relación de parentesco
p05a: 5a. seguro social - alternativa 1
p05b: 5b. seguro social - alternativa 2
p05c: 5c. satisfecho por atención del iess
p05d: 5d. conforme con valores y servicios iess
p06: 6. estado civil
p07: 7. asiste a clases
p08: 8. jornada a la que asiste
p09: 9. razón x la que no asiste
p10a: 10a. nivel de instrucción
p10b: 10b. año aprobado
p11: 11. sabe leer y escribir
p12a: 12a. por sus estudios obtuvo algún título
p12b: 12b. qué título obtuvo
p13: 13. idioma de los padres
p14: 14. idioma que habla
p15: 15. como se considera
p15a: 15a. cuánto está dispuesto a pagar x seguro
p15b: 15b. cuánto está dispuesto a pagar x jubilacion
p15c: 15c. a qué seguro se afiliaría
p15d: 15d. tiene alguna discapacidad
p16a: 16a. siempre vivió en este lugar
p16b: 16b. años que vive en este lugar
p17a: 17a. dónde vivió antes
p17b: 17b. lugar donde vivió antes
p18: 18. razón por la que vino a este lugar
cod_inf: código del informante
p20: 20. trabajó la semana pasada
p21: 21. actividad que realizó para ayudar en su hogar
p22: 22. tiene trabajo del cual estuvo ausente
p23: 23. razón por la que no trabajó
p24: 24. horas de trabajo en la semana anterior
p25: 25. razón por la que trabajó menos de 40 horas
p26: 26. razón por la que trabajó mas de 40 horas
p27: 27. desea trabajar mas horas
p28: 28. està disponible para trabajar horas adicionales
p29: 29. cuàntas horas a la semana estarìa disponible para trabaj
p30: 30. gestiòn realizada para cambiar la situaciòn actual de tr
p31: 31. razòn x la que busca cambiar la situaciòn actual de trab
p32: 32. buscó trabajo el mes anterior
p33: 33. semanas que busca trabajo
p34: 34. razón por la que no buscó trabajo
p35: 35. desea trabajar y esta dispuesto a hacerlo
p36: 36. condición de inactividad
p37: 37. trabajó anteriormente
p38: 38. motivos por los que dejó de trabajar
p39: 39. número de semanas que no trabaja
codindustria: 40. rama de actividad
codocupa: 41. grupo de ocupación
p42: 42. categoría de ocupación
p43: 43. el trabajo que tiene es
p44a: 44a. recibe alimentación
p44b: 44b. recibe vivienda
p44c: 44c. recibe transporte
p44d: 44d. recibe vacaciones
p44e: 44e. recibe ropa de trabajo
p44f: 44f. recibe seguro social
p44g: 44g. recibe seguro medico
p44h: 44h. recibe guardería
p44i: 44i. recibe cursos de capacitación
p45: 45. cuàntos años trabaja
p46: 46. sitio de trabajo
p47a: 47a. tamaño del establecimiento
p47b: 47b. nùmero personas trabajan en el establecimiento
p48: 48. en el establecimiento se lleva
p49: 49. el establecimiento tiene ruc
p50: 50. número de trabajos
p51a: 51a. horas de trabajo principal
p51b: 51b. horas de trabajo secundario
p51c: 51c. horas de otros trabajos
p52: 52. rama de actividad - trabajo secundario
p53: 53. grupo de ocupación - trabajo secundario
p54: 54. categoría de ocupación - trabajo secundario
p55: 55. sitio de trabajo secundario
p56a: 56a. tamañó establecimiento - trabajo secundario
p56b: 56b. personas que trabajan - trabajo secundario
p57: 57. en el establ. trabajo secundario se lleva
p58: 58. el establ. trabajo secundario tiene ruc
p59: 59. cómo se siente en su trabajo
p60a: 60a. descontento x ingresos bajos
p60b: 60b. descontento x muchas horas de trabajo
p60c: 60c. descontento x horarios inconvenientes
p60d: 60d. descontento x sobrecarga de trabajo
p60e: 60e. descontento x no tener estabilidad
p60f: 60f. descontento x ambiente perjudicial
p60g: 60g. descontento x trabajar en la calle
p60h: 60h. descontento x posibles accidentes
p60i: 60i. descontento x las activ. que realiza
p60j: 60j. descontento x pocas posibilidades de progreso
p60k: 60k. descontento x malas relaciones laborales
p61: 61. participa en los quehaceres del hogar
p62a: 62a. participa en el arreglo de casa - horas
p62b: 62b. participa en las compras - horas
p62c: 62c. participa en el arreglo de ropa - horas
p62d: 62d. participa en la preparación de alimentos - horas
p62e: 62e. participa en el cuidado de niños, ancianos - horas
p62f: 62f. participa en ayudar en tareas escolares - horas
p62g: 62g. participa en trabajos comunitarios - horas
p62h: 62h. participa en mingas - horas
p62i: 62i. participa en reuniones del barrio - horas
p63: 63. ingresos - patronos cta. propia
p64a: 64a. retiró bienes del negocio
p64b: 64b. monto de retiro de bienes del negocio
p65: 65. monto gastado en funcionamiento negocio
p66: 66. ingreso de asalariados y/o empl. domésticos
p67: 67. descuentos de asalariados
p68a: 68a. recibió ingreso en especies
p68b: 68b. ingreso en especies de asalariados
p69: 69. ingreso ocup. secundaria - asalariados e independientes
p70a: 70a. recibió pago en especies - trabajo secundario
p70b: 70b. pago en especies - trabajo secundario
p71a: 71a. recibió ingresos derivados del capital
p71b: 71b. ingreso recibido por transacciones de capital
p72a: 72a. recibe jubilación o pensiones
p72b: 72b. ingreso por jubilación o pensiones
p73a: 73a. recibió regalos o donaciones
p73b: 73b. ingreso por regalos o donaciones
p74a: 74a. recibió dinero del exterior
p74b: 74b. ingreso del exterior
p75: 75. recibió el bono de desarrollo humano
p76: 76.  monto que recibió por el bdh
p77a: 77a. frecuencia con que cobra el bdh
p77b: 77b. monto que recibe del bdh según frecuencia
p78: 78. gasto para ir a cobrar el bdh
p79: 79. sabe si tiene una obligación para cobrar el bdh
p80a: 80a. obligación 1
p80b: 80b. obligación 2
p80c: 80c. obligación 3
ingrl: ingreso del trabajo
condact: condición de actividad (clasificación para >= 10 años)
peamsiu: sectores (clasificación para >= 10 años)
cr01: 1. credito - recibió algún crédito
cr02a1: 2a. crédito - crédito productivo solidario
cr02a2: 2a. crédito - monto crédito productivo solidario
cr02b1: 2b. crédito - crédito de desarrollo humano
cr02b2: 2b. crédito - monto crédito de desarrollo humano
cr02c1: 2c. crédito - 5-5-5
cr02c2: 2c. crédito - monto 5-5-5
cr02d1: 2d. crédito - otro del bnf
cr02d2: 2d. crédito - monto otro del bnf
cr02e1: 2e. crédito - iess
cr02e2: 2e. crédito - monto iess
cr02f1: 2f. crédito - banco privado
cr02f2: 2f. crédito - monto banco privado
cr02g1: 2g. crédito - chulquero
cr02g2: 2g. crédito - monto chulquero
ed01: 1. educación - se matriculó en el año 2007-2008
ed02a: 2a. educación - nivel que se matriculó, año 2007-2008
ed02b: 2b. educación - año en que se matriculó, 2007-2008
ed03a: 3a. educación - dió aporte voluntario por matricula
ed03b: 3b. educación - monto del aporte voluntario x matricula
ed04: 4. educación - veces matriculado en el año que indica
ed05: 5. educación - tipo de establecimiento
ed06: 6. educación - recibió textos gratuitos
ed07: 7. educación - que institución entregó los textos
ed08a: 8a. educación - recibe desayuno escolar
ed08b: 8b. educación - frecuencia desayuno escolar
ed09: 9. educación - monto colaboración desayuno escolar
ed10a: 10a. educación - recibe almuerzo escolar
ed10b: 10b. educación - frecuencia almuerzo escolar
ed11: 11. educación - monto colaboración almuerzo escolar
fexp: factor de expansión
prov: provincia
rn: región natural
rgnl: regional
pet: población en edad de trabajar de 10 años y más (pet)
pea: población económicamente activa (pea)
ocupa: ocupados
onocla: ocupados no clasificados
oplenos: ocupados plenos
suboc: subempleados
suboc1: subempleados visibles
suboc2: subempleados otras formas
deso: desocupados
deso1: cesantes
deso2: desocupados 1a vez
deaboc1: desempleados abiertos
deaboc2: desempleados ocultos
pei: población económicamente inactiva (pei)
formal: población formal
informal: población informal
srvdom: población servicio doméstico
nocla: ocupados no clasificados por sector
grupo1: grupo de ocupación (población ocupada de 10 años y más)
rama1: rama de actividad (población ocupada de 10 años y más)
vi01: 1. tipo de vivienda
vi02: 2. la vivienda que ocupa es
vi03: 3. material predominante del piso
vi04: 4. número de cuartos
vi05: 5. número de cuartos para dormir
vi06: 6. qué utiliza el hogar para cocinar
vi07: 7. tipo de servicio higiénico
vi08: 8. de donde obtiene el agua
vi09: 9. el servicio de ducha es
vi10: 10. tipo de alumbrado
vi11: 11. forma de eliminación de basura
vi12: 12. tiene fincas, parcelas o tierras
vi13: 13. forma de tenencia de las tierras
vi1401a: 14.1 tiene refrigerador
vi1401b: 14.1 nro. regrigeradores
vi1402a: 14.2 tiene televisor a color
vi1402b: 14.2 nro. televisores a color
vi1403a: 14.3 tiene licuadora
vi1403b: 14.3 nro. licuadoras
vi1404a: 14.4 tiene computadora
vi1404b: 14.4 nro. computadoras
vi1405a: 14.5 tiene equipo de sonido
vi1405b: 14.5 nro. equipos de sonido
vi1406a: 14.6 tiene micro-hondas
vi1406b: 14.6 nro. micro-hondas
vi1407a: 14.7 tiene cocina con horno
vi1407b: 14.7 nro. cocina con horno
vi1408a: 14.8 tiene cocina sin horno
vi1408b: 14.8 nro. cocinas sin horno
vi1409a: 14.9 tiene radio grabadora
vi1409b: 14.9 nro. radio grabadoras
vi1410a: 14.10 tiene lavadora
vi1410b: 14.10 nro. lavadoras
vi1411a: 14.11 tiene dvd-vhs
vi1411b: 14.11 nro. dvd-vhs
vi1412a: 14.12 tiene bicicleta
vi1412b: 14.12 nro. bicicletas
vi1413a: 14.13 tiene motocicleta
vi1413b: 14.13 nro. motocicletas
vi1414a: 14.14 tiene automovil camioneta
vi1414b: 14.14 nro. automovil camioneta
vi1415a: 14.15 tiene línea telefónica
vi1415b: 14.15 nro. líneas telefónicas
reljefe: 4. relación de parentesco
upm_ci: Unidad Primaria de Muestreo
estrato_ci: Estrato
afroind_ci: Raza o etnia del individuo
afroind_ch: Raza/etnia del hogar en base a raza/etnia del jefe de hogar
afroind_ano_c: AÃ±o Cambio de MetodologÃ­a MediciÃ³n Raza/Etnicidad
dis_ci: Personas con discapacidad
dis_ch: Hogares con miembros con discapacidad
iess: 5a. seguro social - alternativa 1
trabant: 37. trabajó anteriormente
bustrama: 32. buscó trabajo el mes anterior
motnobus: 34. razón por la que no buscó trabajo
hortrahp: 51a. horas de trabajo principal
hortrahs: 51b. horas de trabajo secundario
hortraho: 51c. horas de otros trabajos
hormas: 27. desea trabajar mas horas
catetrab: 42. categoría de ocupación
cates: 54. categoría de ocupación - trabajo secundario
estabil: 43. el trabajo que tiene es
numtrab: 50. número de trabajos
tiembus: 33. semanas que busca trabajo
p65b:
tcylmpri_ch: Id hogar donde algÃºn miembro reporta como top-code el ingr de activ. principal
tcylmpri_ci: Identificador de top-code del ingreso de la actividad principal
ytot_ci:
rentaimp_ch: Rentas imputadas del hogar
autocons_ci: Autoconsumo reportado por el individuo
autocons_ch: Autoconsumo reportado por el hogar
des1_ch: Tipo de desague segÃºn unimproved de MDG
des2_ch: Tipo de desague sin incluir definiciÃ³n MDG
migantiguo5_ci: =1 si es migrante antiguo (5 anos o mas)
migrantelac_ci: =1 si es migrante proveniente de un pais LAC
cpi:

## Revisar los datos

- rn - regiones naturales
- area - area
- prov - provincia
- cuidad - ciudad
- zona - zona
- sector - sector
- panelm - panel
- vivienda - vivienda
- hogar - hogar
- fexp - factor de expansión
- p01 - persona
- p03 - edad
- p63 - ingresos - patronos cta. propia
- p66 - ingreso de asalariados y/o empl. domésticos
- p67 - descuentos de asalariados
- p68b - ingreso en especies de asalariados
- p71b - ingreso recibido por transacciones de capital
- p72b - ingreso por jubilación o pensiones
- ingrl - ingresos del trabajo
- condact - condición de actividad

En esta encuesta las variables y metodología cambian bastante, usaremos p66 de acuerdo a las etiquetas de las variables lo más cercano a las anteriores como la variable de ingreso laboral monetario de la actividad principal asalariada para mantener la concordancia con el resto de los años.

En esta encuesta ya no tenemos las variables que indicaban la condición de actividad en cada mes, por lo que tenemos que cambiar la lógica, la variable panelm representa un trimestre, cambiamos la lógica para recuperar los ingresos y los hogares trimestrales de acuerdo a esta variable.

In [16]:
data[['p63', 'p66', 'p67', 'p68b', 'p71b', 'p72b', 'ingrl']].mean()

p63        487.212341
p66        224.087882
p67         25.405549
p68b        39.882146
p71b       245.483286
p72b       233.980075
ingrl    25538.392878
dtype: float64

Filtramos solo las columnas de interés para alivar el peso en la memoria

In [11]:
len(data)

76922

In [10]:
data['condact'].value_counts()

condact
7    24087
3    19258
8    15859
1    11147
2     4618
5      883
6      734
0      336
Name: count, dtype: int64

In [6]:
data.columns

Index(['region_BID_c', 'region_c', 'pais_c', 'anio_c', 'mes_c', 'zona_c',
       'factor_ch', 'idh_ch', 'idp_ci', 'factor_ci',
       ...
       'tcylmpri_ci', 'ytot_ci', 'rentaimp_ch', 'autocons_ci', 'autocons_ch',
       'des1_ch', 'des2_ch', 'migantiguo5_ci', 'migrantelac_ci', 'cpi'],
      dtype='object', length=419)

In [8]:
data = data[['rn', 'area', 'prov', 'ciudad', 'zona', 'sector', 'panelm',
             'vivienda', 'hogar', 'fexp', 'p01', 'p03', 'p63', 'p66', 
             'p67', 'p68b', 'p71b', 'p72b', 'ingrl', 'condact', 
              'ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 
              'oct', 'nov', 'dic']]

KeyError: "['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'] not in index"

Por alguna razón extraña tenemos varias columnas del factos de expansión

In [11]:
data['fexp']

             fexp        fexp
0      194.911911  194.911911
1      194.911911  194.911911
2      194.911911  194.911911
3      194.911911  194.911911
4      194.911911  194.911911
...           ...         ...
77959  230.986725  230.986725
77960  230.986725  230.986725
77961  230.986725  230.986725
77962  230.986725  230.986725
77963  230.986725  230.986725

[77964 rows x 2 columns]

In [12]:
data = data.loc[:, ~data.columns.duplicated()]

In [13]:
data.columns

Index(['rn', 'area', 'ciudad', 'zona', 'prov', 'sector', 'panelm', 'vivienda',
       'hogar', 'persona', 'edad', 'fexp', 'pe61', 'pe63', 'pe64', 'pe65b',
       'pe68a', 'pe69b', 'ingrl', 'ene', 'feb', 'mar', 'abr', 'may', 'jun',
       'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
      dtype='object')

Creamos una variable de ingreso laboral que es igual al ingreso por asalariado

In [14]:
data['ingr'] = data['pe63']

Ingreso mensual asumiendo que las personas reciben el mismo valor reportado en 'ingr' siempre que reportan estar ocupados en un mes, ahora las variables categoricas por mes tienen diferentes leyendas y no aparecen las etiquetas en la base de 2004, planteamos estas etiquetas basandonos en la continuidad más lógica desde diciembre de 2002

En diciembre de 2002 las personas reportadas como Trabajando fueron 6197, en enero de 2004 son 35209
- 1 - Desocupado
- 2 - Buscando trabajo
- 3 - Trabajando

In [15]:
data['ene'].value_counts()

ene
1.0    37798
3.0    31945
2.0     1018
Name: count, dtype: int64

In [16]:
data['ingr_ene'] = data.apply(lambda x: x['ingr'] if x['ene'] == 3 else None, axis=1)
data['ingr_feb'] = data.apply(lambda x: x['ingr'] if x['feb'] == 3 else None, axis=1)
data['ingr_mar'] = data.apply(lambda x: x['ingr'] if x['mar'] == 3 else None, axis=1)
data['ingr_abr'] = data.apply(lambda x: x['ingr'] if x['abr'] == 3 else None, axis=1)
data['ingr_may'] = data.apply(lambda x: x['ingr'] if x['may'] == 3 else None, axis=1)
data['ingr_jun'] = data.apply(lambda x: x['ingr'] if x['jun'] == 3 else None, axis=1)
data['ingr_jul'] = data.apply(lambda x: x['ingr'] if x['jul'] == 3 else None, axis=1)
data['ingr_ago'] = data.apply(lambda x: x['ingr'] if x['ago'] == 3 else None, axis=1)
data['ingr_sep'] = data.apply(lambda x: x['ingr'] if x['sep'] == 3 else None, axis=1)
data['ingr_oct'] = data.apply(lambda x: x['ingr'] if x['oct'] == 3 else None, axis=1)
data['ingr_nov'] = data.apply(lambda x: x['ingr'] if x['nov'] == 3 else None, axis=1)
data['ingr_dic'] = data.apply(lambda x: x['ingr'] if x['dic'] == 3 else None, axis=1)

In [19]:
data[['ingr_ene', 'ingr_feb', 'ingr_mar', 'ingr_abr', 'ingr_may', 'ingr_jun', 'ingr_jul', 'ingr_ago', 'ingr_sep', 'ingr_oct', 'ingr_nov', 'ingr_dic']].mean()

ingr_ene     52.151013
ingr_feb     47.210762
ingr_mar    107.243860
ingr_abr    107.286074
ingr_may    115.775748
ingr_jun    112.227116
ingr_jul    109.553704
ingr_ago    107.167641
ingr_sep    106.342703
ingr_oct    105.847380
ingr_nov    114.227157
ingr_dic     64.721139
dtype: float64

## Deflactamos y transformamos el ingreso

Esto deja todo en dólares constantes de 2014

In [20]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 2006]
datos_base = data_externa[data_externa['Año'] == 2014]

Diccionarios de ipc, desde 2005, tenemos datos del ipc para más provincias

In [21]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],        
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],        
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_base.iterrows()
     }

### Creamos identificadores para las ciudades siguiendo los códigos del INEC y para los trimestres

In [23]:
# Corregimos los códigos para usarlos cómo texto
data['ciudad'] = data['ciudad'].apply(str)
data['ciudad'] = data['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)

data['ciudad_2'] = data['ciudad'].apply(lambda x: x[:2])

Diccionario ciudades disponibles

In [24]:
parroquia_dict = {
    '01': 'Cuenca',
    '09': 'Guayaquil',
    '17': 'Quito',
    '08': 'Esmeraldas',
    '13': 'Costa',
    '12': 'Costa',
    '07': 'Costa',
    '10': 'Sierra',
    '02': 'Sierra',
    '05': 'Sierra',
    '18': 'Ambato',
    '06': 'Sierra',
    '04': 'Sierra',
    '11': 'Loja',
    '03': 'Sierra'
}

data['ciudad_asignada'] = data['ciudad_2'].apply(lambda x: parroquia_dict.get(x, 'Nacional'))

In [25]:
data['ciudad_asignada'].value_counts()

ciudad_asignada
Sierra        22326
Costa         17593
Guayaquil      9632
Quito          6779
Esmeraldas     6154
Nacional       4220
Loja           3898
Cuenca         3869
Ambato         3493
Name: count, dtype: int64

### Asignamos el ipc correspondiente según ciudad correspondiente

$\begin{equation}
    ingr_{USD-base-2014}^{i} = ingr_{dólares}^{i}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Desde 2000 en adelante ya no es necesario utilizar el tipo de cambio debido al cambio de moneda

In [26]:
# Función que asigna valores correspondientes
def asigna_ipc(fila, trimestre):
    return ipc_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila, trimestre):
    return ipc_base_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

In [27]:
data['ipc_t1'] = data.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data['ipc_base_t1'] = data.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data['ipc_t2'] = data.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data['ipc_base_t2'] = data.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data['ipc_t3'] = data.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data['ipc_base_t3'] = data.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data['ipc_t4'] = data.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data['ipc_base_t4'] = data.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

In [28]:
# Calculamos el deflactor
data['def_t1'] = (data['ipc_base_t1'] / data['ipc_t1'])
data['def_t2'] = (data['ipc_base_t2'] / data['ipc_t2'])
data['def_t3'] = (data['ipc_base_t3'] / data['ipc_t3'])
data['def_t4'] = (data['ipc_base_t4'] / data['ipc_t4'])

In [29]:
# Ingreso real por mes
data['ingr_ene_r'] = data['ingr_ene'] * data['def_t1']
data['ingr_feb_r'] = data['ingr_feb'] * data['def_t1']
data['ingr_mar_r'] = data['ingr_mar'] * data['def_t1']
data['ingr_abr_r'] = data['ingr_abr'] * data['def_t2']
data['ingr_may_r'] = data['ingr_may'] * data['def_t2']
data['ingr_jun_r'] = data['ingr_jun'] * data['def_t2']
data['ingr_jul_r'] = data['ingr_jul'] * data['def_t3']
data['ingr_ago_r'] = data['ingr_ago'] * data['def_t3']
data['ingr_sep_r'] = data['ingr_sep'] * data['def_t3']
data['ingr_oct_r'] = data['ingr_oct'] * data['def_t4']
data['ingr_nov_r'] = data['ingr_nov'] * data['def_t4']
data['ingr_dic_r'] = data['ingr_dic'] * data['def_t4']

Ingreso mensual promedio en el trimeste

In [30]:
data['ingr_t1_r'] = (data['ingr_ene_r'] + data['ingr_feb_r'] + data['ingr_mar_r'])/3
data['ingr_t2_r'] = (data['ingr_abr_r'] + data['ingr_may_r'] + data['ingr_jun_r'])/3
data['ingr_t3_r'] = (data['ingr_jul_r'] + data['ingr_ago_r'] + data['ingr_sep_r'])/3
data['ingr_t4_r'] = (data['ingr_oct_r'] + data['ingr_nov_r'] + data['ingr_dic_r'])/3

In [31]:
data[['ingr_t1_r', 'ingr_t2_r', 'ingr_t3_r', 'ingr_t4_r']].mean()

ingr_t1_r     70.244068
ingr_t2_r    147.754829
ingr_t3_r    148.046006
ingr_t4_r     88.266275
dtype: float64

## Calculo ingreso de los hogares

En este año no tenemos la variable numpers

In [34]:
columnas_idef = ['rn', 'area', 'prov', 'ciudad', 'zona', 'sector', 'panelm', 'vivienda', 'hogar']

data['idef_hogar'] = data[columnas_idef].astype(str).agg(''.join, axis=1)
len(data['idef_hogar'].unique())

18475

In [35]:
data[['rn', 'area', 'prov', 'ciudad', 'zona', 'sector', 'panelm', 'vivienda',
             'hogar',
      'idef_hogar', 'persona']]

,rn,area,prov,ciudad,zona,sector,panelm,vivienda,hogar,idef_hogar,persona
0,1,1,1,010150,1,6,11,1,1,111010150161111,3
1,1,1,1,010150,1,6,11,1,1,111010150161111,1
2,1,1,1,010150,1,6,11,1,1,111010150161111,2
3,1,1,1,010150,1,6,11,1,1,111010150161111,4
4,1,1,1,010150,1,6,14,1,1,111010150161411,2
...,...,...,...,...,...,...,...,...,...,...,...
77959,2,2,9,091752,930,1,12,1,1,22909175293011211,6
77960,2,2,9,091752,930,1,12,1,1,22909175293011211,3
77961,2,2,9,091752,930,1,12,1,1,22909175293011211,2
77962,2,2,9,091752,930,1,12,1,1,22909175293011211,5
77963,2,2,9,091752,930,1,12,1,1,22909175293011211,1

Si todos los miembros del hogar tienen NA como ingreso, mantener NA, si al menos uno tiene un ingreso sumamos para el ingreso del hogar, así evitamos subestimar el ingreso del hogar si tenemos valores perdidos

In [36]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [37]:
data['ingr_t1_h'] = data.groupby('idef_hogar')['ingr_t1_r'].transform(sum_with_na)
data['ingr_t2_h'] = data.groupby('idef_hogar')['ingr_t2_r'].transform(sum_with_na)
data['ingr_t3_h'] = data.groupby('idef_hogar')['ingr_t3_r'].transform(sum_with_na)
data['ingr_t4_h'] = data.groupby('idef_hogar')['ingr_t4_r'].transform(sum_with_na)

In [38]:
data[['ingr_t1_h', 'ingr_t2_h', 'ingr_t3_h', 'ingr_t4_h']].mean()

ingr_t1_h     73.907752
ingr_t2_h    137.634081
ingr_t3_h    128.438038
ingr_t4_h    102.896374
dtype: object

In [39]:
print("Ingreso medio de un hogar t4: ", data['ingr_t4_h'].mean())
print("Mediana del ingreso de un hogar t4: ", data['ingr_t4_h'].median())

Ingreso medio de un hogar t4:  102.89637437697968
Mediana del ingreso de un hogar t4:  13.72324744584281

## Sacamos edades negativas y mayores a 100 años

In [40]:
len(data)

77964

En este caso en la variable edad tenemos números y el texto 'menos de un año' así que primero transformamos todas las filas que digan 'menos de un año' a 0

In [41]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

In [42]:
data = data.loc[(data['edad'] >= 0) & (data['edad'] < 100)]
len(data)

77964

## Ingreso individual descontando cargas familiares

Utilizando la metodología del autor dividimos el ingreso del hogar para la escala $(A_{i}+kC_{i})^{s}$ donde $A_{i}$ es al número de adultos, $C_{i}$ es el número de niños en el hogar $i$. $k$ es el costo en recursos de cada niño y $s$ busca reflejar las restricciones

In [43]:
k = 0.4
s = 0.9

In [44]:
# Si es necesario calcular el número de niños
data['es_nino'] = data['edad'] < 10

data['ninos'] = data.groupby('idef_hogar')['es_nino'].transform('sum')

# Si es necesario calcular el número de adultos
data['es_adulto'] = data['edad'] > 10

data['adultos'] = data.groupby('idef_hogar')['es_adulto'].transform('sum')

In [45]:
data['escala'] = (data['adultos'] + k * data['ninos']) ** s

In [46]:
data['ingr_t_t1'] = data['ingr_t1_h'] / data['escala']
data['ingr_t_t2'] = data['ingr_t2_h'] / data['escala']
data['ingr_t_t3'] = data['ingr_t3_h'] / data['escala']
data['ingr_t_t4'] = data['ingr_t4_h'] / data['escala']

In [47]:
data[['ingr_t_t1', 'ingr_t_t2', 'ingr_t_t3', 'ingr_t_t4']].mean()

ingr_t_t1    19.598238
ingr_t_t2    39.356717
ingr_t_t3    38.679767
ingr_t_t4    24.837593
dtype: object

In [48]:
print("Ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].mean())
print("Mediana del ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].median())

Ingreso individual descontando cargas familiares t4:  24.837592822744032
Mediana del ingreso individual descontando cargas familiares t4:  2.626651375371305

## Umbrales de pobreza

Incluimos los índices de pobreza si es posible a nivel regional para luego poder utilizar de mejor forma el factor de expansión

$\begin{equation}
    umbral_{USD-base-2014}^{i} = umbral_{año}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

Diccionario de umbral

In [49]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

## Cálculo del índice de pobreza de Foster, Greer y Thorbecke

Para calcular un ínidce de pobreza se utiliza a Foster, Greer y Thorbecke (1984), ya que satisface algunas caracterísitcas de distribución que son positivas e igual a las enunciadas por Sen, el autor usa el mismo índice.

$\begin{equation}FGT_{\alpha} = \frac{1}{N}\sum_{i=1}^{H}\left(\frac{z-y_{i}}{z}\right)^{\alpha}\end{equation}$

Donde $z$ es el umbral de pobreza, $N$ es el número de personas en la economía, $H$ es el número de pobres (personas debajo de la línea de pobreza) $y_{i}$ es el ingreso de cada individuo. Mientras mayor es el valor de $\alpha$ mayor es el peso de los individuos más pobres, mayor $FGT$ mayor pobreza en la economía.

En este caso los umbrales están anivel nacional, aún así buscamos calcular la pobreza por región y sacar un promedio ponderado por región para la pobreza nacional, con el objetivo de hacerlo más específico

In [51]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [52]:
data['persona_fexp'] = 1 * data['fexp']

In [53]:
for t in [1, 2, 3, 4]:
    col_ingr = f'ingr_t_t{t}'
    col_pobres = f'pobres_t{t}'

    # una columna que identifica a quienes están por debajo de la línea de pobreza por trimestre
    data[col_pobres] = (
        (data[col_ingr] - umbral_dict.get(t)) < 0
    ).astype(int)

In [54]:
print("pobreza t1: ", (data['pobres_t1'] * data['fexp']).sum()/data.loc[data['ingr_t_t1'] >= 0]['persona_fexp'].sum())
print("pobreza t2: ", (data['pobres_t2'] * data['fexp']).sum()/data.loc[data['ingr_t_t2'] >= 0]['persona_fexp'].sum())
print("pobreza t3: ", (data['pobres_t3'] * data['fexp']).sum()/data.loc[data['ingr_t_t3'] >= 0]['persona_fexp'].sum())
print("pobreza t4: ", (data['pobres_t4'] * data['fexp']).sum()/data.loc[data['ingr_t_t4'] >= 0]['persona_fexp'].sum())

pobreza t1:  0.9423979025158848
pobreza t2:  0.8944781586923719
pobreza t3:  0.9038157446383626
pobreza t4:  0.93163715528624

In [55]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data[f'ingr_t_t{t}'] >= 0].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp[f'ingr_t_t{t}'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[t] - df_temp[f'ingr_t_t{t}']) / umbral_dict[t]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total
    
    # Guardamos los resultados
    datos_final.loc[f't{t}', 'fgt0'] = fgt0
    datos_final.loc[f't{t}', 'fgt1'] = fgt1
    datos_final.loc[f't{t}', 'fgt2'] = fgt2

In [56]:
datos_final

        fgt0      fgt1      fgt2  a25  a50  a75 ingreso_promedio
t1  0.942398  0.835284   0.79187  NaN  NaN  NaN              NaN
t2  0.894478  0.648886  0.543959  NaN  NaN  NaN              NaN
t3  0.903816  0.685981  0.593747  NaN  NaN  NaN              NaN
t4  0.931637  0.758669  0.686761  NaN  NaN  NaN              NaN

## Calculo del índice de desigualdad de Atkinson

Vamos a calcular el índice de desigualdad de atkinson con un parámetro $\epsilon$ de aversión a la desigualdad y un $\mu$ que es igual a la media de los ingresos individuales, con la siguiente fórmula.

$\begin{equation}A = 1-\frac{1}{\mu}\left(\frac{1}{N}\sum_{i=1}^{N}y^{1-\epsilon}\right)^{1/(1-\epsilon)}\end{equation}$

Donde $y_{i}$ es el ingreso individual y $\mu$ es el ingreso medio

In [57]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data[f'ingr_t_t{t}'] >= 0].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()
    
    # Ingreso promedio ponderado
    mu = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp[f'ingr_t_t{t}']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    datos_final.loc[f't{t}', 'a25'] = a25
    datos_final.loc[f't{t}', 'a50'] = a50
    datos_final.loc[f't{t}', 'a75'] = a75

In [58]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.942398,0.835284,0.79187,0.3932,0.750993,0.978338,NaN
t2,0.894478,0.648886,0.543959,0.367743,0.591237,0.837121,NaN
t3,0.903816,0.685981,0.593747,0.431555,0.668384,0.891208,NaN
t4,0.931637,0.758669,0.686761,0.290373,0.606728,0.917329,NaN

Guardamos el ingreso promedio

In [59]:
for t in [1, 2, 3, 4]:
    df_temp = data.loc[data[f'ingr_t_t{t}'] >= 0].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total
    
    datos_final.loc[f't{t}', 'ingreso_promedio'] = media_ponderada

In [60]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.942398,0.835284,0.79187,0.3932,0.750993,0.978338,16.690824
t2,0.894478,0.648886,0.543959,0.367743,0.591237,0.837121,47.980865
t3,0.903816,0.685981,0.593747,0.431555,0.668384,0.891208,49.96358
t4,0.931637,0.758669,0.686761,0.290373,0.606728,0.917329,23.83671

In [61]:
datos_final.to_csv('datos_final.csv')