In [1]:
import numpy as np
import pandas as pd

In [5]:
# data = pd.read_stata(r"Z:\harmonized\ECU\ENEMDU\data_arm\ECU_1990m11_BID.dta") # para bases de stata
data = pd.read_stata(r"datos/ECU_1998m11_BID.dta") # para bases de stata

## Revisar los datos

- rn - región natural
- dominio - dominio
- cuidad - ciudad
- zona - zona
- sector - sector
- vivienda - vivienda
- hogar - hogar
- persona - persona
- numpers - número de personas
- edad - edad
- ingpat - Ingresos como patrono o cuenta propia
- ingasg - Ingresos como asalariado de gobierno
- ingepv - Ingresos asalariado empresa privada
- ingdom - Ingresos como empleada doméstica
- ingalq - Ingresos por alquileres, rentas o interese
- ingjub - Ingresos por jubilación o pensión
- ingotr - por otros ingresos
- fexp - factor de expansión
- ingrl - ingresos

El valor de 'ingasg' e 'ingepv' son el ingreso laboral monetario vamos a incluir 'ingdom' para darle un scope mayor, no hay datos sobre ingreso laboral no monetario, las otras variables son ingreso no laboral monetario y no monetario e ingrl es un ingreso total

Hay variables dicotomicas para cada mes (ene, feb, mar, abr, may, jun, jul, ago, sep, oct, nov, dic) que dicen si estuvo o no trabajando, se puede usar estas variables y el ingreso laboral asumiendo que cuando estaba trabajando tenía ese ingreso para intentar aproximar el salario mensual y de ahí el salario trimestral, esto solo funciona así ya que no tenemos una variable que explicite el mes, en encuestas que tengan el mes o trimestre explícito esto no sería igual.

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40509 entries, 0 to 40508
Columns: 252 entries, region_BID_c to ppp_wdi2011
dtypes: category(77), float32(22), float64(105), int16(3), int32(1), int8(33), object(11)
memory usage: 43.9+ MB

Filtramos solo las columnas de interés para alivar el peso en la memoria

In [6]:
data.columns

Index(['region_BID_c', 'region_c', 'pais_c', 'anio_c', 'mes_c', 'zona_c',
       'factor_ch', 'idh_ch', 'idp_ci', 'factor_ci',
       ...
       'formal', 'formal_1', 'ylm_ci1', 'ynlm_ci1', 'aguafconsumo_ch',
       'aguafuente_ch', 'aguadisp1_ch', 'aguadisp2_ch', 'sinbano_ch',
       'ppp_wdi2011'],
      dtype='object', length=252)

In [7]:
data = data[['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
       'formul', 'persona', 'numpers', 'edad', 'trabajo', 'ingpat', 'ingasg',
       'ingepv', 'ingdom', 'ingjub', 'ingalq', 'ingotr', 'nov', 'dic', 'ene',
       'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'ingrl', 'fexp1', 'fexp']]

In [8]:
data ['sum_ing'] = data [['ingasg', 'ingepv', 'ingdom']].sum(axis=1)

In [9]:
data['suma_ing_ene'] = data.apply(lambda x: x['sum_ing'] if x['ene'] == 'trabajando' else None, axis=1)
data['suma_ing_feb'] = data.apply(lambda x: x['sum_ing'] if x['feb'] == 'trabajando' else None, axis=1)
data['suma_ing_mar'] = data.apply(lambda x: x['sum_ing'] if x['mar'] == 'trabajando' else None, axis=1)
data['suma_ing_abr'] = data.apply(lambda x: x['sum_ing'] if x['abr'] == 'trabajando' else None, axis=1)
data['suma_ing_may'] = data.apply(lambda x: x['sum_ing'] if x['may'] == 'trabajando' else None, axis=1)
data['suma_ing_jun'] = data.apply(lambda x: x['sum_ing'] if x['jun'] == 'trabajando' else None, axis=1)
data['suma_ing_jul'] = data.apply(lambda x: x['sum_ing'] if x['jul'] == 'trabajando' else None, axis=1)
data['suma_ing_ago'] = data.apply(lambda x: x['sum_ing'] if x['ago'] == 'trabajando' else None, axis=1)
data['suma_ing_sep'] = data.apply(lambda x: x['sum_ing'] if x['sep'] == 'trabajando' else None, axis=1)
data['suma_ing_oct'] = data.apply(lambda x: x['sum_ing'] if x['oct'] == 'trabajando' else None, axis=1)
data['suma_ing_nov'] = data.apply(lambda x: x['sum_ing'] if x['nov'] == 'trabajando' else None, axis=1)
data['suma_ing_dic'] = data.apply(lambda x: x['sum_ing'] if x['dic'] == 'trabajando' else None, axis=1)

In [10]:
data['suma_ing_t1'] = (data['suma_ing_ene'] + data['suma_ing_feb'] + data['suma_ing_mar'])/3
data['suma_ing_t2'] = (data['suma_ing_abr'] + data['suma_ing_may'] + data['suma_ing_jun'])/3
data['suma_ing_t3'] = (data['suma_ing_jul'] + data['suma_ing_ago'] + data['suma_ing_sep'])/3
data['suma_ing_t4'] = (data['suma_ing_oct'] + data['suma_ing_nov'] + data['suma_ing_dic'])/3

In [11]:
# Llenar valores perdidos con un dato (0)
data['suma_ing_t1'] = data['suma_ing_t1'].fillna(0)
data['suma_ing_t2'] = data['suma_ing_t2'].fillna(0)
data['suma_ing_t3'] = data['suma_ing_t3'].fillna(0)
data['suma_ing_t4'] = data['suma_ing_t4'].fillna(0)

In [12]:
data

,rn,dominio,ciudad,zona,sector,vivienda,hogar,formul,persona,numpers,...,suma_ing_jul,suma_ing_ago,suma_ing_sep,suma_ing_oct,suma_ing_nov,suma_ing_dic,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4
0,1,3,010150,001,007,01,1,1,1,6,...,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0,720000.0
1,1,3,010150,001,007,01,1,1,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,1,3,010150,001,007,01,1,1,3,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,1,3,010150,001,007,01,1,1,4,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,1,3,010150,001,007,01,1,1,5,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40504,3,8,210450,001,011,12,1,1,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40505,3,8,210450,001,011,12,1,1,3,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40506,3,8,210450,001,011,12,1,1,4,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40507,3,8,210450,001,011,12,1,1,5,6,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
40508,3,8,210450,001,011,12,1,1,6,6,...,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
data['suma_ing_t1'].mean()

np.float64(287102.9054284233)

In [14]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: openpyxl in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [16]:
data['ingr_ene'] = data.apply(lambda x: x['ingr'] if x['ene'] == 'trabajando' else None, axis=1)
data['ingr_feb'] = data.apply(lambda x: x['ingr'] if x['feb'] == 'trabajando' else None, axis=1)
data['ingr_mar'] = data.apply(lambda x: x['ingr'] if x['mar'] == 'trabajando' else None, axis=1)
data['ingr_abr'] = data.apply(lambda x: x['ingr'] if x['abr'] == 'trabajando' else None, axis=1)
data['ingr_may'] = data.apply(lambda x: x['ingr'] if x['may'] == 'trabajando' else None, axis=1)
data['ingr_jun'] = data.apply(lambda x: x['ingr'] if x['jun'] == 'trabajando' else None, axis=1)
data['ingr_jul'] = data.apply(lambda x: x['ingr'] if x['jul'] == 'trabajando' else None, axis=1)
data['ingr_ago'] = data.apply(lambda x: x['ingr'] if x['ago'] == 'trabajando' else None, axis=1)
data['ingr_sep'] = data.apply(lambda x: x['ingr'] if x['sep'] == 'trabajando' else None, axis=1)
data['ingr_oct'] = data.apply(lambda x: x['ingr'] if x['oct'] == 'trabajando' else None, axis=1)
data['ingr_nov'] = data.apply(lambda x: x['ingr'] if x['nov'] == 'trabajando' else None, axis=1)
data['ingr_dic'] = data.apply(lambda x: x['ingr'] if x['dic'] == 'trabajando' else None, axis=1)

## Deflactamos y transformamos el ingreso

Esto deja todo en dólares constantes de 2014, utilizamos el IPC de Estados Unidos para ajustar por inflación ya que no podemos usar la inflación en sucres si queremos dejar el valor final en dólares de 2014

In [17]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 1998]
datos_base = data_externa[data_externa['Año'] == 2014]

In [18]:
datos_actual

,Año,trimestre,Nacional,Sierra,Costa,Guayaquil,Esmeraldas,Machala,Manta,Santo Domingo,Quito,Loja,Cuenca,Ambato,salario básico unificado,tipo de cambio,umbral de pobreza
32,1998,1,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,4655.000000,375.832026
33,1998,2,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,5192.666667,378.853988
34,1998,3,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,5700.333333,381.904114
35,1998,4,11.900493,NaN,NaN,13.458188,NaN,NaN,NaN,NaN,11.962291,NaN,10.345311,NaN,18.360752,6676.000000,385.117817

In [19]:
ipc_dict = dict(zip(datos_actual['trimestre'], datos_actual['IPC Estados Unidos']))

ipc_base_dict = dict(zip(datos_base['trimestre'], datos_base['IPC Estados Unidos']))

tipo_cambio_dict = dict(zip(datos_actual['trimestre'], datos_actual['tipo de cambio']))

### Asignamos el ipc y tipo de cambio correspondiente según trimestre

$\begin{equation}
    ingr_{USD-base-2014}^{i} = \frac{ingr_{sucres}^{i}}{tipo-de-cambio^{i}}\left( \frac{ipcUSA^{i}_{2014}}{ipcUSA^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

In [11]:
data['ipc_t1'] = ipc_dict.get(1)
data['ipc_base_t1'] = ipc_base_dict.get(1)
data['tipo_cambio_t1'] = tipo_cambio_dict.get(1)

data['ipc_t2'] = ipc_dict.get(2)
data['ipc_base_t2'] = ipc_base_dict.get(2)
data['tipo_cambio_t2'] = tipo_cambio_dict.get(2)

data['ipc_t3'] = ipc_dict.get(3)
data['ipc_base_t3'] = ipc_base_dict.get(3)
data['tipo_cambio_t3'] = tipo_cambio_dict.get(3)

data['ipc_t4'] = ipc_dict.get(4)
data['ipc_base_t4'] = ipc_base_dict.get(4)
data['tipo_cambio_t4'] = tipo_cambio_dict.get(4)

In [12]:
# Calculamos el deflactor
data['def'] = (data['ipc_base'] / data['ipc'])

In [13]:
data['ingr_t1_r'] = (data['suma_ing_t1'] / data['tipo_cambio']) * data['def']
data['ingr_t2_r'] = (data['suma_ing_t2'] / data['tipo_cambio']) * data['def']
data['ingr_t3_r'] = (data['suma_ing_t3'] / data['tipo_cambio']) * data['def']
data['ingr_t4_r'] = (data['suma_ing_t4'] / data['tipo_cambio']) * data['def']

In [27]:
data[['suma_ing_t1', 'suma_ing_t2', 'suma_ing_t3', 'suma_ing_t4', 'ipc', 'ipc_base', 'def', 'tipo_cambio', 'ingr_t1_r', 'ingr_t2_r', 'ingr_t3_r', 'ingr_t4_r']]

,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4,ipc,ipc_base,def,tipo_cambio,ingr_t1_r,ingr_t2_r,ingr_t3_r,ingr_t4_r
0,720000.0,720000.0,720000.0,720000.0,10.345311,97.862086,9.459559,4655.0,1463.132682,1463.132682,1463.132682,1463.132682
1,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
40504,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40505,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40506,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40507,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40508,0.0,0.0,0.0,0.0,11.900493,98.083034,8.241930,4655.0,0.000000,0.000000,0.000000,0.000000

In [14]:
data['ingr_t1_r'] = (data['ingr_ene_r'] + data['ingr_feb_r'] + data['ingr_mar_r'])/3
data['ingr_t2_r'] = (data['ingr_abr_r'] + data['ingr_may_r'] + data['ingr_jun_r'])/3
data['ingr_t3_r'] = (data['ingr_jul_r'] + data['ingr_ago_r'] + data['ingr_sep_r'])/3
data['ingr_t4_r'] = (data['ingr_oct_r'] + data['ingr_nov_r'] + data['ingr_dic_r'])/3

data['ingr_t4_r'].mean()

In [15]:
columnas_idef = ['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar']

data['idef_hogar'] = data[columnas_idef].astype(str).agg(''.join, axis=1)
len(data['idef_hogar'].unique())

9216

In [16]:
data[['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar', 'idef_hogar', 'persona', 'numpers']]

,rn,dominio,ciudad,zona,sector,vivienda,hogar,idef_hogar,persona,numpers
0,1,3,10150,001,007,01,1,1310150001007011,6,6
1,1,3,10150,001,007,01,1,1310150001007011,3,6
2,1,3,10150,001,007,01,1,1310150001007011,1,6
3,1,3,10150,001,007,01,1,1310150001007011,5,6
4,1,3,10150,001,007,01,1,1310150001007011,2,6
...,...,...,...,...,...,...,...,...,...,...
40504,3,8,210450,001,011,12,1,38210450001011121,6,6
40505,3,8,210450,001,011,12,1,38210450001011121,3,6
40506,3,8,210450,001,011,12,1,38210450001011121,4,6
40507,3,8,210450,001,011,12,1,38210450001011121,1,6
40508,3,8,210450,001,011,12,1,38210450001011121,2,6

Si todos los miembros del hogar tienen NA como ingreso, mantener NA, si al menos uno tiene un ingreso sumamos para el ingreso del hogar, así evitamos subestimar el ingreso del hogar si tenemos valores perdidos

In [17]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [18]:
data['ingr_t1_h'] = data.groupby('idef_hogar')['ingr_t1_r'].transform('sum')
data['ingr_t2_h'] = data.groupby('idef_hogar')['ingr_t2_r'].transform('sum')
data['ingr_t3_h'] = data.groupby('idef_hogar')['ingr_t3_r'].transform('sum')
data['ingr_t4_h'] = data.groupby('idef_hogar')['ingr_t4_r'].transform('sum')

In [19]:
data[['ingr_t1_h', 'ingr_t2_h', 'ingr_t3_h', 'ingr_t4_h']]

ingr_t1_h    444.341546
ingr_t2_h    402.834589
ingr_t3_h    363.676169
ingr_t4_h    307.044702
dtype: object

In [20]:
print("Ingreso medio de un hogar t4: ", data['ingr_t4_h'].mean())
print("Mediana del ingreso de un hogar t4: ", data['ingr_t4_h'].median())

Ingreso medio de un hogar t4:  307.0447015166984
Mediana del ingreso de un hogar t4:  215.7162935906804

In [34]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

In [21]:
len(data)

0        33
1        28
2        12
3         7
4         4
         ..
40504    28
40505     9
40506     4
40507     2
40508    18
Name: edad, Length: 40509, dtype: int64

En este caso en la variable edad tenemos números y el texto 'menos de un año' así que primero transformamos todas las filas que digan 'menos de un año' a 0

In [22]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

In [23]:
data = data.loc[(data['edad'] >= 0) & (data['edad'] < 100)]
len(data)

40509

In [24]:
k = 0.4
s = 0.9

In [25]:
# Si es necesario calcular el número de niños
data['es_nino'] = data['edad'] < 10

data['ninos'] = data.groupby('idef_hogar')['es_nino'].transform('sum')

# Si es necesario calcular el número de adultos
data['es_adulto'] = data['edad'] > 10

data['adultos'] = data.groupby('idef_hogar')['es_adulto'].transform('sum')

In [26]:
data['escala'] = (data['adultos'] + k * data['ninos']) ** s

In [27]:
data['ingr_t_t1'] = data['ingr_t1_h'] / data['escala']
data['ingr_t_t2'] = data['ingr_t2_h'] / data['escala']
data['ingr_t_t3'] = data['ingr_t3_h'] / data['escala']
data['ingr_t_t4'] = data['ingr_t4_h'] / data['escala']

In [28]:
data[['ingr_t_t1', 'ingr_t_t2', 'ingr_t_t3', 'ingr_t_t4']]

       ingr_t_t1  ingr_t_t2  ingr_t_t3  ingr_t_t4
0      61.702577  55.668859  50.572413  42.686553
1      61.702577  55.668859  50.572413  42.686553
2      61.702577  55.668859  50.572413  42.686553
3      61.702577  55.668859  50.572413  42.686553
4      61.702577  55.668859  50.572413  42.686553
...          ...        ...        ...        ...
40504  77.128221  69.586074  63.215517  53.358191
40505  77.128221  69.586074  63.215517  53.358191
40506  77.128221  69.586074  63.215517  53.358191
40507  77.128221  69.586074  63.215517  53.358191
40508  77.128221  69.586074  63.215517  53.358191

[40509 rows x 4 columns]

In [29]:
print("Ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].mean())
print("Mediana del ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].median())

Ingreso individual descontando cargas familiares t4:  84.73963267683268
Mediana del ingreso individual descontando cargas familiares t4:  57.36432812907176

## Umbrales de pobreza

Incluimos los índices de pobreza si es posible a nivel regional para luego poder utilizar de mejor forma el factor de expansión

data[['ingr_t_t1', 'ingr_t_t2', 'ingr_t_t3', 'ingr_t_t4']]

In [42]:
print("Ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].mean())
print("Mediana del ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].median())

Ingreso individual descontando cargas familiares t4:  665.2600120566833
Mediana del ingreso individual descontando cargas familiares t4:  272.47600854064507

In [30]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

In [44]:
# Asigna el umbral por trimestre si hay umbral por región modificar
data['umbral'] = data['trimestre'].map(umbral_dict)

data['umbral'] = data.groupby('idef_hogar')['umbral'].transform('mean')

In [31]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [32]:
data['persona_fexp'] = 1 * data['fexp']

In [33]:
for t in [1, 2, 3, 4]:
    condicion = data['trimestre'] == t
    col_ingr = f'ingr_t_t{t}'
    col_pobres = f'pobres_t{t}'

    # una columna que identifica a quienes están por debajo de la línea de pobreza por trimestre
    data.loc[condicion, col_pobres] = (
        (data.loc[condicion, col_ingr] - data.loc[condicion, 'umbral']) < 0
    ).astype(int)

In [34]:
data[['pobres_t1', 'pobres_t2', 'pobres_t3', 'pobres_t4']].sum()

pobres_t1     8946
pobres_t2    10163
pobres_t3    11585
pobres_t4    13944
dtype: int64

In [35]:
print("pobreza t1: ", (data['pobres_t1'] * data['fexp']).sum()/data.loc[data['trimestre'] == 1]['persona_fexp'].sum())
print("pobreza t2: ", (data['pobres_t2'] * data['fexp']).sum()/data.loc[data['trimestre'] == 2]['persona_fexp'].sum())
print("pobreza t3: ", (data['pobres_t3'] * data['fexp']).sum()/data.loc[data['trimestre'] == 3]['persona_fexp'].sum())
print("pobreza t4: ", (data['pobres_t4'] * data['fexp']).sum()/data.loc[data['trimestre'] == 4]['persona_fexp'].sum())

pobreza t1:  0.3275167094784148
pobreza t2:  0.36324933056190906
pobreza t3:  0.42913620218413095
pobreza t4:  0.5267198253611451

In [36]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp[f'ingr_t_t{t}'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[t] - df_temp[f'ingr_t_t{t}']) / umbral_dict[t]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total
    
    # Guardamos los resultados
    datos_final.loc[f't{t}', 'fgt0'] = fgt0
    datos_final.loc[f't{t}', 'fgt1'] = fgt1
    datos_final.loc[f't{t}', 'fgt2'] = fgt2

In [37]:
datos_final

        fgt0      fgt1      fgt2  a25  a50  a75 ingreso_promedio
t1  0.327517  0.133478  0.075334  NaN  NaN  NaN              NaN
t2  0.363249  0.151462  0.086165  NaN  NaN  NaN              NaN
t3  0.429136  0.174847  0.099798  NaN  NaN  NaN              NaN
t4   0.52672  0.226436  0.132679  NaN  NaN  NaN              NaN

## Calculo del índice de desigualdad de Atkinson

Vamos a calcular el índice de desigualdad de atkinson con un parámetro $\epsilon$ de aversión a la desigualdad y un $\mu$ que es igual a la media de los ingresos individuales, con la siguiente fórmula.

$\begin{equation}A = 1-\frac{1}{\mu}\left(\frac{1}{N}\sum_{i=1}^{N}y^{1-\epsilon}\right)^{1/(1-\epsilon)}\end{equation}$

Donde $y_{i}$ es el ingreso individual y $\mu$ es el ingreso medio

In [38]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()
    
    # Ingreso promedio ponderado
    mu = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp[f'ingr_t_t{t}']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    datos_final.loc[f't{t}', 'a25'] = a25
    datos_final.loc[f't{t}', 'a50'] = a50
    datos_final.loc[f't{t}', 'a75'] = a75

In [39]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.327517,0.133478,0.075334,0.099223,0.188523,0.269041,NaN
t2,0.363249,0.151462,0.086165,0.097945,0.186115,0.26568,NaN
t3,0.429136,0.174847,0.099798,0.098416,0.186698,0.266081,NaN
t4,0.52672,0.226436,0.132679,0.09966,0.189216,0.269848,NaN

Guardamos el ingreso promedio

In [40]:
for t in [1, 2, 3, 4]:
    df_temp = data.loc[data['trimestre'] == t].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total
    
    datos_final.loc[f't{t}', 'ingreso_promedio'] = media_ponderada

In [41]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.327517,0.133478,0.075334,0.099223,0.188523,0.269041,129.134281
t2,0.363249,0.151462,0.086165,0.097945,0.186115,0.26568,116.540454
t3,0.429136,0.174847,0.099798,0.098416,0.186698,0.266081,105.461861
t4,0.52672,0.226436,0.132679,0.09966,0.189216,0.269848,89.007694

### Inserta los cálculos en la base final

In [42]:
indices = pd.read_csv("indices.csv", encoding='latin-1')

In [43]:
ano = 1998
# Asegurar que el índice de datos_final coincide con trimestres 1..4
datos_final = datos_final.copy()
datos_final["trimestre"] = [1, 2, 3, 4]
datos_final["Año"] = ano

# Reemplazar en indices usando mask
for col in ["fgt0","fgt1","fgt2","a25","a50","a75","ingreso_promedio"]:
    indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

/tmp/ipykernel_96954/4024059561.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.3275167094784148 0.36324933056190906 0.42913620218413095
 0.5267198253611451]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96954/4024059561.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.1334784257637082 0.15146223880808243 0.1748466774266044
 0.22643634191902176]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96954/4024059561.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.07533384493386149 0.08616545078962014 0.09979834307769304
 0.13267895734574506]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96954/4024059561.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.09922267222099845 0.09794485024446564 0.09841576067741875
 0.09966028646304659]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96954/4024059561.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.18852303098817624 0.18611469196231611 0.18669806768224584
 0.1892160295078923]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96954/4024059561.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2690405620931461 0.2656795566825709 0.2660811877465745
 0.26984799071706655]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96954/4024059561.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[129.13428126012454 116.54045442091734 105.46186144046816
 89.00769379823971]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

In [44]:
datos_final.to_csv('datos_final1998.csv')