In [1]:
import numpy as np
import pandas as pd

# Plantilla

Es necesario ajustar las definiciones, las fuentes de los datos y posiblemente definiciones si la ENEMDU tiene una dimensión geográfica y temporal al mismo tiempo

In [3]:
data = pd.read_stata(r"Z:\harmonized\ECU\ENEMDU\data_arm\ECU_2002m11_BID.dta") # para bases de stata
# data = pd.read_stata(r"datos/ECU_2002m11_BID.dta") # para bases de stata

## Revisar los datos

- area - area
- cuidad - ciudad
- zona - zona
- sector - sector
- vivienda - vivienda
- hogar - hogar
- persona - persona
- numpers - número de personas
- edad - edad
- fexp - factor de expansión
- ingrl - ingresos

Las variables de ingreso cambian en esta encuesta
- pe61 - Ingresos totales, patronos cta. propia
- pe63 - Ingreso de asalariados y/o empl. domésticos
- pe64 - descuentos de asalariados
- pe65a - Ingreso en especie de asalariados
- pe68a - Ingreso recibido por transacciones de capital
- pe69a - ingreso por jubilación o pensiones

De acuerdo a las etiquetas de las variables utilizaremos pe63 como la variable de ingreso laboral monetario de la actividad principal asalariada para mantener la concordancia con el resto de los años.

Hay variables dicotomicas para cada mes (ene, feb, mar, abr, may, jun, jul, ago, sep, oct, nov, dic) que dicen si estuvo o no trabajando, se puede usar estas variables y el ingreso laboral asumiendo que cuando estaba trabajando tenía ese ingreso para intentar aproximar el salario mensual y de ahí el salario trimestral, esto solo funciona así ya que no tenemos una variable que explicite el mes, en encuestas que tengan el mes o trimestre explícito esto no sería igual.

In [4]:
data[['pe61', 'pe63', 'pe64', 'pe65a', 'pe68a', 'pe69a']].mean()

pe61     36.896720
pe63     54.997781
pe64      5.311053
pe65a     2.737076
pe68a     5.714533
pe69a     2.955847
dtype: float64

Filtramos solo las columnas de interés para alivar el peso en la memoria

In [5]:
data.columns

Index(['region_BID_c', 'region_c', 'pais_c', 'anio_c', 'mes_c', 'zona_c',
       'factor_ch', 'idh_ch', 'idp_ci', 'factor_ci',
       ...
       'aguamejorada_ch', 'aguamide_ch', 'aguatrat_ch', 'bano_ch', 'banoex_ch',
       'banomejorado_ch', 'sinbano_ch', 'des1_ch', 'des2_ch', 'cpi'],
      dtype='object', length=329)

In [6]:
data = data[['area', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
             'persona', 'numpers', 'edad', 'fexp', 'ingrl', 'pe61', 'pe63',
              'pe64', 'pe65a', 'pe68a', 'pe69a',
              'ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 
              'oct', 'nov', 'dic']]

Creamos una variable de ingreso laboral que es igual al ingreso por asalariado y en función de la variable ingrl limpiamos los valores que son menores a 7128 que es el valor máximo del ingreso total corregido

In [7]:
data['pe63'] = data['pe63'].replace(999999, np.nan)
data['pe63'] = data['pe63'].replace(98020, np.nan)
data['pe63'] = data['pe63'].replace(20620, np.nan)
data['pe63'] = data['pe63'].replace(19938, np.nan)
data['pe63'] = data['pe63'].replace(18020, np.nan)
data['pe63'] = data['pe63'].replace(10000, np.nan)
data['pe63'] = data['pe63'].replace(9999, np.nan)

In [8]:
data['ingr'] = data['pe63']

Para este año las etiquetas de los meses vuelven a cambiar

In [9]:
data['ene'].value_counts()

ene
desocupado y sin buscar trabajo    11551
trabajando                          9855
0                                   2842
buscando trabajo                     551
Name: count, dtype: int64

In [10]:
data['ingr_ene'] = data.apply(lambda x: x['ingr'] if x['ene'] == 'trabajando' else None, axis=1)
data['ingr_feb'] = data.apply(lambda x: x['ingr'] if x['feb'] == 'trabajando' else None, axis=1)
data['ingr_mar'] = data.apply(lambda x: x['ingr'] if x['mar'] == 'trabajando' else None, axis=1)
data['ingr_abr'] = data.apply(lambda x: x['ingr'] if x['abr'] == 'trabajando' else None, axis=1)
data['ingr_may'] = data.apply(lambda x: x['ingr'] if x['may'] == 'trabajando' else None, axis=1)
data['ingr_jun'] = data.apply(lambda x: x['ingr'] if x['jun'] == 'trabajando' else None, axis=1)
data['ingr_jul'] = data.apply(lambda x: x['ingr'] if x['jul'] == 'trabajando' else None, axis=1)
data['ingr_ago'] = data.apply(lambda x: x['ingr'] if x['ago'] == 'trabajando' else None, axis=1)
data['ingr_sep'] = data.apply(lambda x: x['ingr'] if x['sep'] == 'trabajando' else None, axis=1)
data['ingr_oct'] = data.apply(lambda x: x['ingr'] if x['oct'] == 'trabajando' else None, axis=1)
data['ingr_nov'] = data.apply(lambda x: x['ingr'] if x['nov'] == 'trabajando' else None, axis=1)
data['ingr_dic'] = data.apply(lambda x: x['ingr'] if x['dic'] == 'trabajando' else None, axis=1)

In [11]:
data[['ingr_ene', 'ingr_feb', 'ingr_mar', 'ingr_abr', 'ingr_may', 'ingr_jun', 'ingr_jul', 'ingr_ago', 'ingr_sep', 'ingr_oct', 'ingr_nov', 'ingr_dic']].mean()

ingr_ene    114.629027
ingr_feb    114.506556
ingr_mar    114.803626
ingr_abr    114.732183
ingr_may    114.700658
ingr_jun    114.871774
ingr_jul    114.780137
ingr_ago    114.781451
ingr_sep    115.148130
ingr_oct    115.396615
ingr_nov    115.297687
ingr_dic    118.238272
dtype: float64

## Deflactamos y transformamos el ingreso

Esto deja todo en dólares constantes de 2014

In [12]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 2002]
datos_base = data_externa[data_externa['Año'] == 2014]

Diccionarios de ipc

In [13]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_base.iterrows()
     }

### Creamos identificadores para las ciudades siguiendo los códigos del INEC y para los trimestres

In [23]:
print(data['ciudad'][0])
fac = data['ciudad'].apply(lambda x: len(str(x))).min()
fac

010150

6

In [24]:
# Corregimos los códigos para usarlos cómo texto
data['ciudad'] = data['ciudad'].apply(str)
data['ciudad'] = data['ciudad'].apply(lambda x: '0' + x if len(x) == (fac-1) else x)

data['ciudad_2'] = data['ciudad'].apply(lambda x: x[:2])

Diccionario ciudades disponibles

In [25]:
parroquia_dict = {
    '01': 'Cuenca',
    '09': 'Guayaquil',
    '17': 'Quito'
}

data['ciudad_asignada'] = data['ciudad_2'].apply(lambda x: parroquia_dict.get(x, 'Nacional'))

In [26]:
data['ciudad_asignada'].value_counts()

ciudad_asignada
Nacional     10905
Guayaquil     6932
Quito         4835
Cuenca        2127
Name: count, dtype: int64

### Asignamos el ipc correspondiente según ciudad correspondiente

$\begin{equation}
    ingr_{USD-base-2014}^{i} = ingr_{dólares}^{i}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Desde 2000 en adelante ya no es necesario utilizar el tipo de cambio debido al cambio de moneda

In [27]:
# Función que asigna valores correspondientes
def asigna_ipc(fila, trimestre):
    return ipc_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila, trimestre):
    return ipc_base_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

In [28]:
data['ipc_t1'] = data.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data['ipc_base_t1'] = data.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data['ipc_t2'] = data.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data['ipc_base_t2'] = data.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data['ipc_t3'] = data.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data['ipc_base_t3'] = data.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data['ipc_t4'] = data.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data['ipc_base_t4'] = data.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

In [29]:
# Calculamos el deflactor
data['def_t1'] = (data['ipc_base_t1'] / data['ipc_t1'])
data['def_t2'] = (data['ipc_base_t2'] / data['ipc_t2'])
data['def_t3'] = (data['ipc_base_t3'] / data['ipc_t3'])
data['def_t4'] = (data['ipc_base_t4'] / data['ipc_t4'])

In [30]:
# Ingreso real por mes
data['ingr_ene_r'] = data['ingr_ene'] * data['def_t1']
data['ingr_feb_r'] = data['ingr_feb'] * data['def_t1']
data['ingr_mar_r'] = data['ingr_mar'] * data['def_t1']
data['ingr_abr_r'] = data['ingr_abr'] * data['def_t2']
data['ingr_may_r'] = data['ingr_may'] * data['def_t2']
data['ingr_jun_r'] = data['ingr_jun'] * data['def_t2']
data['ingr_jul_r'] = data['ingr_jul'] * data['def_t3']
data['ingr_ago_r'] = data['ingr_ago'] * data['def_t3']
data['ingr_sep_r'] = data['ingr_sep'] * data['def_t3']
data['ingr_oct_r'] = data['ingr_oct'] * data['def_t4']
data['ingr_nov_r'] = data['ingr_nov'] * data['def_t4']
data['ingr_dic_r'] = data['ingr_dic'] * data['def_t4']

Ingreso mensual promedio en el trimeste

In [31]:
data['ingr_t1_r'] = (data['ingr_ene_r'] + data['ingr_feb_r'] + data['ingr_mar_r'])/3
data['ingr_t2_r'] = (data['ingr_abr_r'] + data['ingr_may_r'] + data['ingr_jun_r'])/3
data['ingr_t3_r'] = (data['ingr_jul_r'] + data['ingr_ago_r'] + data['ingr_sep_r'])/3
data['ingr_t4_r'] = (data['ingr_oct_r'] + data['ingr_nov_r'] + data['ingr_dic_r'])/3

In [32]:
data[['ingr_t1_r', 'ingr_t2_r', 'ingr_t3_r', 'ingr_t4_r']].mean()

ingr_t1_r    183.491612
ingr_t2_r    185.547949
ingr_t3_r    188.198950
ingr_t4_r    203.886305
dtype: float64

## Regiones

In [33]:
# Corregimos los códigos para usarlos cómo texto
data['ciudad'] = data['ciudad'].apply(str)
data['ciudad'] = data['ciudad'].apply(lambda x: '0' + x if len(x) == (fac-1) else x)

data['ciudad_2'] = data['ciudad'].apply(lambda x: x[:2])

In [34]:
regiones_dict = {
    'Guayas': '09',
    'Manabí': '13',
    'El Oro': '07',
    'Los Ríos': '12',
    'Pichincha': '17',
    'Azuay': '01',
    'Galápagos': '20',
    'Sierra': ['04', '10', '05', '18', '02', '06', '03', '11'],
    'Costa, Santo Domingo': ['08', '24', '23'],
    'Amazonía': ['14', '15', '16', '19', '21', '22', '90']
}

In [35]:
codigo_region = {}
for region, codes in regiones_dict.items():
    
    if isinstance(codes, list):
        for code in codes:
            codigo_region[code] = region
    
    else:
        codigo_region[codes] = region

# Mapeo de regiones
data['region'] = data['ciudad_2'].map(codigo_region)

In [36]:
data['region'].value_counts()

region
Guayas                  6932
Pichincha               4835
Sierra                  2989
El Oro                  2440
Amazonía                2227
Azuay                   2127
Manabí                  1649
Los Ríos                 902
Costa, Santo Domingo     698
Name: count, dtype: int64

## Calculo ingreso de los hogares

In [37]:
columnas_idef = ['area', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar']

data['idef_hogar'] = data[columnas_idef].astype(str).agg(''.join, axis=1)
len(data['idef_hogar'].unique())

6030

In [38]:
data[['area', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
      'idef_hogar', 'persona', 'numpers']]

,area,ciudad,zona,sector,vivienda,hogar,idef_hogar,persona,numpers
0,1,010150,001,005,01,1,1010150001005011,01,2
1,1,010150,001,005,01,1,1010150001005011,02,2
2,1,010150,001,005,10,1,1010150001005101,03,3
3,1,010150,001,005,10,1,1010150001005101,02,3
4,1,010150,001,005,10,1,1010150001005101,01,3
...,...,...,...,...,...,...,...,...,...
24794,2,070150,013,008,10,1,2070150013008101,01,4
24795,2,070150,013,008,10,1,2070150013008101,04,4
24796,2,070150,013,008,10,1,2070150013008101,02,4
24797,2,070150,013,008,11,1,2070150013008111,01,1
24798,2,070150,013,008,12,1,2070150013008121,01,1

Si todos los miembros del hogar tienen NA como ingreso, mantener NA, si al menos uno tiene un ingreso sumamos para el ingreso del hogar, así evitamos subestimar el ingreso del hogar si tenemos valores perdidos

In [39]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [40]:
data['ingr_t1_h'] = data.groupby('idef_hogar')['ingr_t1_r'].transform(sum_with_na)
data['ingr_t2_h'] = data.groupby('idef_hogar')['ingr_t2_r'].transform(sum_with_na)
data['ingr_t3_h'] = data.groupby('idef_hogar')['ingr_t3_r'].transform(sum_with_na)
data['ingr_t4_h'] = data.groupby('idef_hogar')['ingr_t4_r'].transform(sum_with_na)

In [41]:
data[['ingr_t1_h', 'ingr_t2_h', 'ingr_t3_h', 'ingr_t4_h']].mean()

ingr_t1_h     342.81941
ingr_t2_h    347.490659
ingr_t3_h    354.259913
ingr_t4_h    335.084083
dtype: object

In [42]:
print("Ingreso medio de un hogar t4: ", data['ingr_t4_h'].mean())
print("Mediana del ingreso de un hogar t4: ", data['ingr_t4_h'].median())

Ingreso medio de un hogar t4:  335.08408286639894
Mediana del ingreso de un hogar t4:  200.25676656075294

## Sacamos edades negativas y mayores a 100 años

In [43]:
len(data)

24799

En este caso en la variable edad tenemos números y el texto 'menos de un año' así que primero transformamos todas las filas que digan 'menos de un año' a 0

In [44]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

In [45]:
data = data.loc[(data['edad'] >= 0) & (data['edad'] < 100)]
len(data)

24799

## Ingreso individual descontando cargas familiares

Utilizando la metodología del autor dividimos el ingreso del hogar para la escala $(A_{i}+kC_{i})^{s}$ donde $A_{i}$ es al número de adultos, $C_{i}$ es el número de niños en el hogar $i$. $k$ es el costo en recursos de cada niño y $s$ busca reflejar las restricciones

In [46]:
k = 0.4
s = 0.9

In [47]:
# Si es necesario calcular el número de niños
data['es_nino'] = data['edad'] < 10

data['ninos'] = data.groupby('idef_hogar')['es_nino'].transform('sum')

# Si es necesario calcular el número de adultos
data['es_adulto'] = data['edad'] > 10

data['adultos'] = data.groupby('idef_hogar')['es_adulto'].transform('sum')

In [48]:
data['escala'] = (data['adultos'] + k * data['ninos']) ** s

In [49]:
data['ingr_t_t1'] = data['ingr_t1_h'] / data['escala']
data['ingr_t_t2'] = data['ingr_t2_h'] / data['escala']
data['ingr_t_t3'] = data['ingr_t3_h'] / data['escala']
data['ingr_t_t4'] = data['ingr_t4_h'] / data['escala']

In [50]:
data[['ingr_t_t1', 'ingr_t_t2', 'ingr_t_t3', 'ingr_t_t4']].mean()

ingr_t_t1    100.467135
ingr_t_t2    101.551868
ingr_t_t3    103.465946
ingr_t_t4    102.270676
dtype: object

In [52]:
print("Ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].mean())
print("Mediana del ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].median())

Ingreso individual descontando cargas familiares t4:  102.27067562550702
Mediana del ingreso individual descontando cargas familiares t4:  59.135244398330336

## Umbrales de pobreza

Incluimos los índices de pobreza si es posible a nivel regional para luego poder utilizar de mejor forma el factor de expansión

$\begin{equation}
    umbral_{USD-base-2014}^{i} = umbral_{año}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

Diccionario de umbral

In [53]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))
salario_dict = dict(zip(datos_actual['trimestre'], datos_actual['salario básico unificado']))
ano = 2002

## Cálculo del índice de pobreza de Foster, Greer y Thorbecke

Para calcular un ínidce de pobreza se utiliza a Foster, Greer y Thorbecke (1984), ya que satisface algunas caracterísitcas de distribución que son positivas e igual a las enunciadas por Sen, el autor usa el mismo índice.

$\begin{equation}FGT_{\alpha} = \frac{1}{N}\sum_{i=1}^{H}\left(\frac{z-y_{i}}{z}\right)^{\alpha}\end{equation}$

Donde $z$ es el umbral de pobreza, $N$ es el número de personas en la economía, $H$ es el número de pobres (personas debajo de la línea de pobreza) $y_{i}$ es el ingreso de cada individuo. Mientras mayor es el valor de $\alpha$ mayor es el peso de los individuos más pobres, mayor $FGT$ mayor pobreza en la economía.

En este caso los umbrales están anivel nacional, aún así buscamos calcular la pobreza por región y sacar un promedio ponderado por región para la pobreza nacional, con el objetivo de hacerlo más específico

## Calculo del índice de desigualdad de Atkinson

Vamos a calcular el índice de desigualdad de atkinson con un parámetro $\epsilon$ de aversión a la desigualdad y un $\mu$ que es igual a la media de los ingresos individuales, con la siguiente fórmula.

$\begin{equation}A = 1-\frac{1}{\mu}\left(\frac{1}{N}\sum_{i=1}^{N}y^{1-\epsilon}\right)^{1/(1-\epsilon)}\end{equation}$

Donde $y_{i}$ es el ingreso individual y $\mu$ es el ingreso medio

In [54]:
resultados_list = []

# Para cada trimeste
for t in [1, 2, 3, 4]:
    salario = salario_dict.get(t)
    col_ingr = f'ingr_t_t{t}'
    umbral = umbral_dict.get(t)
    
    # Agrupa por región
    grouped = data.groupby('region')
    
    for region_name, group in grouped:
        # 1. Filtra datos
        valid = group.dropna(subset=[col_ingr])
        
        if len(valid) == 0:
            continue
            
        # Extrae los vectores 
        ingresos = valid[col_ingr].values
        pesos = valid['fexp'].values
        
        # 2. Calcula indices
        gaps = (umbral - ingresos) / umbral
        gaps = np.clip(gaps, a_min=0, a_max=None)
        
        # 3. Calcula FGT
        total_poblacion = pesos.sum()
        
        # FGT0
        fgt0 = (pesos * (gaps > 0).astype(int)).sum() / total_poblacion
        
        # FGT1
        fgt1 = (pesos * (gaps ** 1)).sum() / total_poblacion
        
        # FGT2
        fgt2 = (pesos * (gaps ** 2)).sum() / total_poblacion
        
        # 4. Calcula Ingreso promedio
        ingreso_promedio = np.average(ingresos, weights=pesos)

        # 5. Desigualdad de Atkinson
        atkinson_resultados = {}
        
        if ingreso_promedio > 0:
            for epsilon in [0.25, 0.5, 0.75]:
                # La suma ponderada de la utilidad
                utility_sum = np.sum((ingresos ** (1 - epsilon)) * pesos)
                
                # promedio de esa utilidad
                utility_mean = utility_sum / total_poblacion
                
                # ingreso equivalente
                y_ede = utility_mean ** (1 / (1 - epsilon))
                
                # índice final
                atkinson_index = 1 - (y_ede / ingreso_promedio)
                atkinson_resultados[f'a{int(epsilon*100)}'] = atkinson_index
        else:
            # Si nadie gana nada, definimos desigualdad como NaN
            atkinson_resultados = {'a25': np.nan, 'a50': np.nan, 'a75': np.nan}

        # 6. Calcula mediana del ingreso
        # Ordena
        sort_idx = np.argsort(ingresos)
        ingreso_ordenado = ingresos[sort_idx]
        pesos_ordenado = pesos[sort_idx]
        cumsum_pesos = np.cumsum(pesos_ordenado)
        cutoff = total_poblacion / 2.0
        mediana = ingreso_ordenado[np.searchsorted(cumsum_pesos, cutoff)]
        
        # 7. Guarda resultados
        resultados_list.append({
            'ano': ano,
            'trimestre': t,
            'region': region_name,
            'fgt0': fgt0,
            'fgt1': fgt1,
            'fgt2': fgt2,
            'a25': atkinson_resultados['a25'],
            'a50': atkinson_resultados['a50'],
            'a75': atkinson_resultados['a75'],
            'ingreso_promedio': ingreso_promedio,
            'ingreso_mediana': mediana + 1 if mediana < 1 else mediana,
            'salario_minimo': salario,
            'kaitz_indice': salario / (mediana + 1 if mediana < 1 else mediana)         
        })

# lista a DataFrame
df_final_regional = pd.DataFrame(resultados_list)
df_final_regional

,ano,trimestre,region,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,ingreso_mediana,salario_minimo,kaitz_indice
0,2002,1,Amazonía,0.533354,0.387240,0.345035,0.177630,0.400536,0.727387,95.790409,62.472630,104.88,1.678815
1,2002,1,Azuay,0.523640,0.408439,0.372077,0.202971,0.444741,0.775112,105.916754,61.941719,104.88,1.693205
2,2002,1,"Costa, Santo Domingo",0.640625,0.481707,0.425699,0.189478,0.430661,0.770573,63.143069,33.915571,104.88,3.092385
3,2002,1,El Oro,0.548103,0.393898,0.352682,0.180416,0.408708,0.746199,86.676663,59.145303,104.88,1.773260
4,2002,1,Guayas,0.576359,0.405878,0.359944,0.217840,0.451440,0.761449,94.586459,59.515004,104.88,1.762245
5,2002,1,Los Ríos,0.604462,0.395072,0.342534,0.157725,0.365552,0.694689,69.307646,57.170389,104.88,1.834516
6,2002,1,Manabí,0.622009,0.481297,0.426354,0.218687,0.469217,0.790771,78.908586,36.353669,104.88,2.884991
7,2002,1,Pichincha,0.417897,0.329177,0.307485,0.193943,0.416439,0.730378,149.767089,96.247670,104.88,1.089689
8,2002,1,Sierra,0.552110,0.426155,0.388427,0.196838,0.439829,0.775707,92.607569,58.928133,104.88,1.779795
9,2002,2,Amazonía,0.524673,0.373710,0.330652,0.171384,0.387270,0.709627,99.318454,64.989318,104.88,1.613804
10,2002,2,Azuay,0.514357,0.402522,0.366906,0.199912,0.439101,0.769119,108.150125,64.131021,104.88,1.635402
11,2002,2,"Costa, Santo Domingo",0.606046,0.459333,0.409963,0.181105,0.415903,0.755901,67.062486,39.886323,104.88,2.629473
12,2002,2,El Oro,0.550936,0.400975,0.360665,0.184283,0.416705,0.755826,87.141204,59.052333,104.88,1.776052
13,2002,2,Guayas,0.576414,0.405371,0.359322,0.217244,0.450713,0.760878,96.208406,60.130467,104.88,1.744207
14,2002,2,Los Ríos,0.585803,0.385893,0.333704,0.153975,0.358639,0.687562,70.323728,57.577102,104.88,1.821557
15,2002,2,Manabí,0.624158,0.480613,0.426382,0.218285,0.468776,0.790626,79.481889,37.023923,104.88,2.832763
16,2002,2,Pichincha,0.421541,0.333209,0.311157,0.195584,0.419416,0.733558,149.386075,96.872901,104.88,1.082656
17,2002,2,Sierra,0.555617,0.433234,0.395462,0.199614,0.445592,0.782628,91.930702,55.843478,104.88,1.878107
18,2002,3,Amazonía,0.518650,0.374618,0.331499,0.170860,0.386757,0.709688,100.753787,65.512542,104.88,1.600915
19,2002,3,Azuay,0.512636,0.399243,0.364162,0.199363,0.437179,0.765876,108.266089,69.770548,104.88,1.503213
20,2002,3,"Costa, Santo Domingo",0.608912,0.457636,0.401200,0.176959,0.406497,0.743626,67.639037,44.007393,104.88,2.383236
21,2002,3,El Oro,0.526514,0.384403,0.346592,0.177543,0.403107,0.739748,89.669551,64.700077,104.88,1.621018
22,2002,3,Guayas,0.563053,0.395170,0.350798,0.213222,0.443367,0.752917,98.273712,61.854657,104.88,1.695588
23,2002,3,Los Ríos,0.589270,0.387959,0.337303,0.155319,0.362096,0.692981,71.196518,58.507283,104.88,1.792597
24,2002,3,Manabí,0.609036,0.474038,0.421486,0.215929,0.464930,0.787711,80.533511,38.019174,104.88,2.758608
25,2002,3,Pichincha,0.411558,0.322006,0.300113,0.191092,0.410547,0.722873,153.246044,98.126186,104.88,1.068828
26,2002,3,Sierra,0.560048,0.429654,0.390786,0.197997,0.442377,0.779472,92.426659,56.293069,104.88,1.863107
27,2002,4,Amazonía,0.553816,0.415396,0.371321,0.191476,0.427215,0.757241,98.826768,58.582914,104.88,1.790283
28,2002,4,Azuay,0.623575,0.483431,0.437129,0.241980,0.503648,0.829470,70.665791,45.281600,104.88,2.316173
29,2002,4,"Costa, Santo Domingo",0.624742,0.459601,0.400591,0.176326,0.403599,0.737578,67.086032,44.377713,104.88,2.363348
30,2002,4,El Oro,0.547126,0.409430,0.376624,0.195030,0.437317,0.779569,90.301157,62.119705,104.88,1.688353
31,2002,4,Guayas,0.595211,0.427767,0.379013,0.229317,0.470897,0.780978,94.319918,54.140206,104.88,1.937192
32,2002,4,Los Ríos,0.627248,0.453102,0.397625,0.191068,0.427178,0.762417,71.644651,44.590176,104.88,2.352088
33,2002,4,Manabí,0.749473,0.598003,0.531233,0.245020,0.519192,0.839579,53.033022,17.204919,104.88,6.095931
34,2002,4,Pichincha,0.419190,0.328860,0.306488,0.194051,0.416252,0.729632,154.037275,98.936148,104.88,1.060078
35,2002,4,Sierra,0.660275,0.499811,0.455765,0.227823,0.496719,0.833594,70.770029,36.580663,104.88,2.867089

### Inserta los cálculos en la base final

In [55]:
indices = pd.read_csv("indices_region.csv", encoding='latin-1')

In [56]:
import os

# 2. cheque el archivo
if not os.path.isfile('indices_region.csv'):
    # Headers si es la primera vez
    df_final_regional.to_csv('indices_region.csv', index=False, encoding='latin-1')
else:
    # SI ya existe, append
    df_final_regional.to_csv('indices_region.csv', mode='a', index=False, header=False, encoding='latin-1')