In [1]:
import numpy as np
import pandas as pd

# Plantilla

Es necesario ajustar las definiciones, las fuentes de los datos y posiblemente definiciones si la ENEMDU tiene una dimensión geográfica y temporal al mismo tiempo

Ahora hay bases por mes, entonces calculamos para cada mes

In [2]:
data1 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_01_SPSS\enemdu_persona_2024_01.sav", convert_categoricals=False) # para bases de stata
data2 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_02_SPSS\enemdu_persona_2024_02.sav", convert_categoricals=False) # para bases de stata
data3 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_03_SPSS\enemdu_persona_2024_03.sav", convert_categoricals=False) # para bases de stata

data4 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_04_SPSS\enemdu_persona_2024_04.sav", convert_categoricals=False) # para bases de stata
data5 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_05_SPSS\enemdu_persona_2024_05.sav", convert_categoricals=False) # para bases de stata
data6 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_06_SPSS\enemdu_persona_2024_06.sav", convert_categoricals=False) # para bases de stata

data7 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_07_SPSS\enemdu_persona_2024_07.sav", convert_categoricals=False) # para bases de stata
data8 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_08_SPSS\enemdu_persona_2024_08.sav", convert_categoricals=False) # para bases de stata
data9 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_09_SPSS\enemdu_persona_2024_09.sav", convert_categoricals=False) # para bases de stata

data10 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_10_SPSS\enemdu_persona_2024_10.sav", convert_categoricals=False) # para bases de stata
data11 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_11_SPSS\enemdu_persona_2024_11.sav", convert_categoricals=False) # para bases de stata
data12 = pd.read_spss(r"C:\Users\oscarj\OneDrive - Inter-American Development Bank Group\Desktop\ecu\2024\1_BDD_ENEMDU_2024_12_SPSS\enemdu_persona_2024_12.sav", convert_categoricals=False) # para bases de stata

## Revisar los datos

| enero   | febrero | marzo   | abril   | mayo    | junio   | julio   | agosto  | septiembre | octubre | noviembre | diciembre |
|---------|---------|---------|---------|---------|---------|---------|---------|------------|---------|-----------|-----------|
| area| area| area| area| area| area| area| area| area| area| area| area|
| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad| ciudad|
| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda| vivienda|
| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar| hogar|
| p02| p02| p02| p02| p02| p02| p02| p02| p02| p02| p02| p02|
| p03| p03| p03| p03| p03| p03| p03| p03| p03| p03| p03| p03|
| p66| p66| p66| p66| p66| p66| p66| p66| p66| p66| p66| p66|
| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp| fexp|
| p20| p20| p20| p20| p20| p20| p20| p20| p20| p20| p20| p20|
| id_hogar| id_hogar| if_hogar| if_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar| id_hogar|

En esta encuesta tenemos una base para cada mes, esto cambia la lógica que habíamos tenido hasta ahora así que de aquí en adelante cambiamos algo del código, mantenemos de acuerdo a las etiquetas de las variables p66 como la variable de ingreso laboral monetario de la actividad principal asalariada para mantener la concordancia con el resto de los años.

Elegimos hacer los cálculos en las bases mensuales para poder usar la representatividad mensual, con un promedio simple debería bastar para tener el resultado del trimestre.

Ahora usamos p20 que pregunta si trabajo la semana pasada, si se cumple vamos a asumir que trabajo durante todo el mes, ahora en adelante capturaremos incluso de mejor forma el mercado laboral, mantenemos la idea de que si el individuo trabajo recibe su ingreso laboral reportado.

In [15]:
columnas = pd.Index(['area', 'ciudad', 'vivienda', 
                     'hogar', 'p66', 'fexp', 'p02', 'p03', 
                     'p20', 'id_hogar'])

Filtramos solo las columnas de interés para alivar el peso en la memoria

In [16]:
data1 = data1[columnas.intersection(data1.columns)]
data2 = data2[columnas.intersection(data2.columns)]
data3 = data3[columnas.intersection(data3.columns)]
data4 = data4[columnas.intersection(data4.columns)]
data5 = data5[columnas.intersection(data5.columns)]
data6 = data6[columnas.intersection(data6.columns)]
data7 = data7[columnas.intersection(data7.columns)]
data8 = data8[columnas.intersection(data8.columns)]
data9 = data9[columnas.intersection(data9.columns)]
data10 = data10[columnas.intersection(data10.columns)]
data11 = data11[columnas.intersection(data11.columns)]
data12 = data12[columnas.intersection(data12.columns)]

Creamos una variable de ingreso laboral que es igual al ingreso por asalariado y limpiamos según los valores de ingrl, para mantener ambas variables para cada base consistente

In [29]:
data12['p66'].value_counts().sort_index(ascending=False)

p66
999999.0    16
4527.0       1
4500.0       1
3800.0       1
3622.0       1
            ..
18.0         1
15.0         1
12.0         1
10.0         1
0.0         94
Name: count, Length: 460, dtype: int64

In [30]:
data1['p66'] = pd.to_numeric(data1['p66'], errors='coerce')
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x > 9000 else x)
data1['p66'] = data1['p66'].apply(lambda x: np.nan if x < 0 else x)

data2['p66'] = pd.to_numeric(data2['p66'], errors='coerce')
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x > 6000 else x)
data2['p66'] = data2['p66'].apply(lambda x: np.nan if x < 0 else x)

data3['p66'] = pd.to_numeric(data3['p66'], errors='coerce')
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x > 4500 else x)
data3['p66'] = data3['p66'].apply(lambda x: np.nan if x < 0 else x)

data4['p66'] = pd.to_numeric(data4['p66'], errors='coerce')
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x > 5500 else x)
data4['p66'] = data4['p66'].apply(lambda x: np.nan if x < 0 else x)

data5['p66'] = pd.to_numeric(data5['p66'], errors='coerce')
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x > 12634 else x)
data5['p66'] = data5['p66'].apply(lambda x: np.nan if x < 0 else x)

data6['p66'] = pd.to_numeric(data6['p66'], errors='coerce')
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x > 4300 else x)
data6['p66'] = data6['p66'].apply(lambda x: np.nan if x < 0 else x)

data7['p66'] = pd.to_numeric(data7['p66'], errors='coerce')
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x > 6500 else x)
data7['p66'] = data7['p66'].apply(lambda x: np.nan if x < 0 else x)

data8['p66'] = pd.to_numeric(data8['p66'], errors='coerce')
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x > 6500 else x)
data8['p66'] = data8['p66'].apply(lambda x: np.nan if x < 0 else x)

data9['p66'] = pd.to_numeric(data9['p66'], errors='coerce')
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x > 10460 else x)
data9['p66'] = data9['p66'].apply(lambda x: np.nan if x < 0 else x)

data10['p66'] = pd.to_numeric(data10['p66'], errors='coerce')
data10['p66'] = data10['p66'].apply(lambda x: np.nan if x > 8000 else x)
data10['p66'] = data10['p66'].apply(lambda x: np.nan if x < 0 else x)

data11['p66'] = pd.to_numeric(data11['p66'], errors='coerce')
data11['p66'] = data11['p66'].apply(lambda x: np.nan if x > 8145 else x)
data11['p66'] = data11['p66'].apply(lambda x: np.nan if x < 0 else x)

data12['p66'] = pd.to_numeric(data12['p66'], errors='coerce')
data12['p66'] = data12['p66'].apply(lambda x: np.nan if x > 4527 else x)
data12['p66'] = data12['p66'].apply(lambda x: np.nan if x < 0 else x)

In [31]:
for base in [data1, data2, data3, data4, data5, data6, 
             data7, data8, data9, data10, data11, data12]:
    base['ingr'] = base['p66']

Ingreso mensual asumiendo que las personas reciben el mismo valor reportado en 'ingr' siempre que reportan estar ocupados la semana pasada, de acuerdo a la variable 'trabajo'

In [32]:
for base in [data1, data2, data3, data4, data5, data6, 
             data7, data8, data9, data10, data11, data12]:
    base['ingr'] = base.apply(lambda x: x['ingr'] if x['p20'] == 1 else np.nan, axis=1)

## Deflactamos y transformamos el ingreso

Esto deja todo en dólares constantes de 2014

In [33]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 2024]
datos_base = data_externa[data_externa['Año'] == 2014]

Diccionarios de ipc

In [35]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Sierra': fila['Sierra'],
        'Costa': fila['Costa'],
        'Guayaquil': fila['Guayaquil'],
        'Esmeraldas': fila['Esmeraldas'],
        'Machala': fila['Machala'],
        'Manta': fila['Manta'],
        'Quito': fila['Quito'],
        'Loja': fila['Loja'],
        'Cuenca': fila['Cuenca'],
        'Ambato': fila['Ambato']
    }
     for _, fila in datos_base.iterrows()
     }

### Creamos identificadores para las ciudades siguiendo los códigos del INEC y para los trimestres

In [36]:
# Corregimos los códigos para usarlos cómo texto
for base in [data1, data2, data3, data4, data5,
             data6, data7, data8, data9, data10, data11,
             data12]:
    base['ciudad'] = base['ciudad'].apply(str)
    base['ciudad'] = base['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)
    base['ciudad_2'] = base['ciudad'].apply(lambda x: x[:4])

Diccionario ciudades disponibles

In [43]:
parroquia_dict = {
    '0101': 'Cuenca',
    '0901': 'Guayaquil',
    '0801': 'Esmeraldas',
    '0701': 'Machala',
    '1308': 'Manta',
    '1701': 'Quito',
    '1101': 'Loja',
    '1801': 'Ambato'
}

def get_parroquia(codigo):
    if codigo in parroquia_dict:
        return parroquia_dict[codigo]
    elif codigo[:2] in ['01', '02', '03', '04', '05', '06', '10', '11', '17', '18']:
        return 'Sierra'
    elif codigo[:2] in ['07', '08', '09', '12', '13', '23', '24']:
        return 'Costa'
    else:
        return 'Nacional'

for base in [data1, data2, data3, data4, data5,
             data6, data7, data8, data9,
             data10, data11, data12]:
    base['ciudad_asignada'] = base['ciudad_2'].apply(get_parroquia)

In [44]:
data12['ciudad_asignada'].value_counts()

ciudad_asignada
Nacional    14375
Sierra       4918
Quito        3437
Costa        2683
Ambato       1709
Loja          328
Manta         160
Name: count, dtype: int64

### Asignamos el ipc correspondiente según ciudad correspondiente

$\begin{equation}
    ingr_{USD-base-2014}^{i} = ingr_{dólares}^{i}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Desde 2000 en adelante ya no es necesario utilizar el tipo de cambio debido al cambio de moneda

In [45]:
# Función que asigna valores correspondientes
def asigna_ipc(fila, trimestre):
    return ipc_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila, trimestre):
    return ipc_base_dict.get(trimestre, {}).get(fila['ciudad_asignada'], None)

In [46]:
data1['ipc'] = data1.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data1['ipc_base'] = data1.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data2['ipc'] = data2.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data2['ipc_base'] = data2.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data3['ipc'] = data3.apply(lambda fila: asigna_ipc(fila, 1), axis=1)
data3['ipc_base'] = data3.apply(lambda fila: asigna_ipc_base(fila, 1), axis=1)

data4['ipc'] = data4.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data4['ipc_base'] = data4.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data5['ipc'] = data5.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data5['ipc_base'] = data5.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data6['ipc'] = data6.apply(lambda fila: asigna_ipc(fila, 2), axis=1)
data6['ipc_base'] = data6.apply(lambda fila: asigna_ipc_base(fila, 2), axis=1)

data7['ipc'] = data7.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data7['ipc_base'] = data7.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data8['ipc'] = data8.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data8['ipc_base'] = data8.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data9['ipc'] = data9.apply(lambda fila: asigna_ipc(fila, 3), axis=1)
data9['ipc_base'] = data9.apply(lambda fila: asigna_ipc_base(fila, 3), axis=1)

data10['ipc'] = data10.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data10['ipc_base'] = data10.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data11['ipc'] = data11.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data11['ipc_base'] = data11.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

data12['ipc'] = data12.apply(lambda fila: asigna_ipc(fila, 4), axis=1)
data12['ipc_base'] = data12.apply(lambda fila: asigna_ipc_base(fila, 4), axis=1)

In [47]:
# Calculamos el deflactor
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['def'] = (base['ipc_base'] / base['ipc'])

In [48]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_r'] = base['ingr'] * base['def']

In [50]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_r'].mean())

720.0949619211683
446.2563984132209
446.25220294643293
500.15803799374123
466.6911828332041
447.04267258487886
455.01090466497766
443.6959648485846
537.6477110327954
459.6163496020464
456.66285539820797
460.2319984084731

## Calculo ingreso de los hogares

In [51]:
for base in [data1, data2, data3, data4, data5, 
             data6, data7, data8, data9, data10, data11, data12]:
    base['idef_hogar'] = base['id_hogar']

for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['idef_hogar'].nunique())

8803
8803
8797
8804
8727
8796
8931
8906
8917
8792
8773
8726

Si todos los miembros del hogar tienen NA como ingreso, mantener NA, si al menos uno tiene un ingreso sumamos para el ingreso del hogar, así evitamos subestimar el ingreso del hogar si tenemos valores perdidos

In [52]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [53]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_h'] = base.groupby('idef_hogar')['ingr_r'].transform(sum_with_na)

In [54]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    print(base['ingr_h'].mean())

1029.9538295931466
659.1809490732021
651.31276295237
744.0619178790068
685.4723797492128
661.0590439340668
677.8296303452422
652.7649093105016
799.2903805021652
678.3821952625425
679.1361561683475
681.7488075562502

## Sacamos edades negativas y mayores a 100 años

Transformamos las variables de edad a numericas para evitar problemas

In [55]:
for base in [data1, data2, data3, data4, data5, data6, data7, 
             data8, data9, data10, data11, data12]:
    base['edad'] = pd.to_numeric(base['p03'], errors='coerce')

In [56]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base = base.loc[(base['edad'] >= 0) & (base['edad'] < 100)]

## Ingreso individual descontando cargas familiares

Utilizando la metodología del autor dividimos el ingreso del hogar para la escala $(A_{i}+kC_{i})^{s}$ donde $A_{i}$ es al número de adultos, $C_{i}$ es el número de niños en el hogar $i$. $k$ es el costo en recursos de cada niño y $s$ busca reflejar las restricciones

In [57]:
k = 0.4
s = 0.9

In [58]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    # Si es necesario calcular el número de niños
    base['es_nino'] = base['edad'] < 10 
    base['ninos'] = base.groupby('idef_hogar')['es_nino'].transform('sum')

    # Si es necesario calcular el número de adultos
    base['es_adulto'] = base['edad'] > 10
    base['adultos'] = base.groupby('idef_hogar')['es_adulto'].transform('sum')

In [59]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['escala'] = (base['adultos'] + k * base['ninos']) ** s

In [60]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    base['ingr_t'] = base['ingr_h'] / base['escala']

In [61]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
        print(base['ingr_t'].mean())

331.76893588871974
208.11422873578417
207.45940776120895
233.12872944085083
217.4963831720511
209.06982423680952
212.94319408843802
208.22947955769135
253.41488700799403
214.53579020305526
215.1164155712363
216.9862745060183

## Umbrales de pobreza

Incluimos los índices de pobreza si es posible a nivel regional para luego poder utilizar de mejor forma el factor de expansión

$\begin{equation}
    umbral_{USD-base-2014}^{i} = umbral_{año}\left( \frac{ipc^{i}_{2014}}{ipc^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

Diccionario de umbral

In [62]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

## Cálculo del índice de pobreza de Foster, Greer y Thorbecke

Para calcular un ínidce de pobreza se utiliza a Foster, Greer y Thorbecke (1984), ya que satisface algunas caracterísitcas de distribución que son positivas e igual a las enunciadas por Sen, el autor usa el mismo índice.

$\begin{equation}FGT_{\alpha} = \frac{1}{N}\sum_{i=1}^{H}\left(\frac{z-y_{i}}{z}\right)^{\alpha}\end{equation}$

Donde $z$ es el umbral de pobreza, $N$ es el número de personas en la economía, $H$ es el número de pobres (personas debajo de la línea de pobreza) $y_{i}$ es el ingreso de cada individuo. Mientras mayor es el valor de $\alpha$ mayor es el peso de los individuos más pobres, mayor $FGT$ mayor pobreza en la economía.

En este caso los umbrales están anivel nacional, aún así buscamos calcular la pobreza por región y sacar un promedio ponderado por región para la pobreza nacional, con el objetivo de hacerlo más específico

In [63]:
for base in [data1, data2, data3, data4, data5, data6, data7, 
             data8, data9, data10, data11, data12]:
        base['persona_fexp'] = 1 * base['fexp']

In [64]:
def trimestre(base):
    """Returns quarter number based on dataframe identity."""
    trimestre_1 = [data1, data2, data3]
    trimestre_2 = [data4, data5, data6]
    trimestre_3 = [data7, data8, data9]
    trimestre_4 = [data10, data11, data12]

    if any(base is df for df in trimestre_1):
        return 1
    elif any(base is df for df in trimestre_2):
        return 2
    elif any(base is df for df in trimestre_3):
        return 3
    elif any(base is df for df in trimestre_4):
        return 4
    else:
        return print("Problema")

In [65]:
for base in [data1, data2, data3, data4, data5, data6, data7, data8, data9,
             data10, data11, data12]:
    
    t = trimestre(base)
    base['pobres_t'] = (
        (base['ingr_t'] - umbral_dict.get(trimestre(base)) < 0
    ).astype(int))

In [66]:
for base in [data1, data2, data3, data4, data5, data6, data7, 
             data8, data9, data10, data11, data12]:
    print(f"pobreza : ", (base['pobres_t'] * base['fexp']).sum()/base.loc[base['ingr_t'] >= 0]['persona_fexp'].sum())

pobreza :  0.2168676625049561
pobreza :  0.27139069971550805
pobreza :  0.2780211661507432
pobreza :  0.2288184631404451
pobreza :  0.24841418570895166
pobreza :  0.23000305918085537
pobreza :  0.20706606648935313
pobreza :  0.24327015183092138
pobreza :  0.2227676580961078
pobreza :  0.2510144236740355
pobreza :  0.2808071461058247
pobreza :  0.290125203821643

In [67]:
# Calculamos los índices por mes, luego buscaremos la manera de sacar los indices trimestrales como un promedio ponderado de los meses
datos_final_mensual = pd.DataFrame(index=[f'm{x+1}' for x in range(12)], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio', 'factor'])

In [68]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12]

for idx, base in enumerate(datasets, start=1):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp['ingr_t'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[trimestre(base)] - df_temp['ingr_t']) / umbral_dict[trimestre(base)]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total

    # Assign to the corresponding row: data1→m1, data2→m2, etc.
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['fgt0','fgt1','fgt2']] = [fgt0, fgt1, fgt2]

In [69]:
datos_final_mensual

         fgt0      fgt1      fgt2  a25  a50  a75 ingreso_promedio factor
m1   0.230628  0.086692  0.049005  NaN  NaN  NaN              NaN    NaN
m2   0.280151  0.120229   0.07188  NaN  NaN  NaN              NaN    NaN
m3   0.292068   0.10646  0.058744  NaN  NaN  NaN              NaN    NaN
m4    0.24399  0.088232  0.049346  NaN  NaN  NaN              NaN    NaN
m5   0.261268  0.094077  0.052342  NaN  NaN  NaN              NaN    NaN
m6   0.239625  0.093825  0.053182  NaN  NaN  NaN              NaN    NaN
m7   0.216916  0.076806  0.040987  NaN  NaN  NaN              NaN    NaN
m8   0.252498  0.104427  0.062918  NaN  NaN  NaN              NaN    NaN
m9   0.230482  0.082252  0.044319  NaN  NaN  NaN              NaN    NaN
m10  0.251014  0.100639  0.060033  NaN  NaN  NaN              NaN    NaN
m11  0.280807  0.126757  0.086462  NaN  NaN  NaN              NaN    NaN
m12  0.290125  0.119147  0.071641  NaN  NaN  NaN              NaN    NaN

## Calculo del índice de desigualdad de Atkinson

Vamos a calcular el índice de desigualdad de atkinson con un parámetro $\epsilon$ de aversión a la desigualdad y un $\mu$ que es igual a la media de los ingresos individuales, con la siguiente fórmula.

$\begin{equation}A = 1-\frac{1}{\mu}\left(\frac{1}{N}\sum_{i=1}^{N}y^{1-\epsilon}\right)^{1/(1-\epsilon)}\end{equation}$

Donde $y_{i}$ es el ingreso individual y $\mu$ es el ingreso medio

In [70]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12]

for idx, base in enumerate(datasets, start=1):
    # Filtramos para cada trimestre
    df_temp = base.loc[base['ingr_t'] >= 0].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()

    # Ingreso promedio ponderado
    mu = (df_temp['ingr_t'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp['ingr_t']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['a25','a50','a75']] = [a25, a50, a75]

In [71]:
datos_final_mensual

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,factor
m1,0.230628,0.086692,0.049005,0.098639,0.192501,0.289086,NaN,NaN
m2,0.280151,0.120229,0.07188,0.081765,0.162033,0.251036,NaN,NaN
m3,0.292068,0.10646,0.058744,0.07944,0.155122,0.234323,NaN,NaN
m4,0.24399,0.088232,0.049346,0.080652,0.158473,0.239674,NaN,NaN
m5,0.261268,0.094077,0.052342,0.083378,0.161327,0.245319,NaN,NaN
m6,0.239625,0.093825,0.053182,0.071277,0.140347,0.212617,NaN,NaN
m7,0.216916,0.076806,0.040987,0.07014,0.136684,0.20542,NaN,NaN
m8,0.252498,0.104427,0.062918,0.074942,0.148401,0.229301,NaN,NaN
m9,0.230482,0.082252,0.044319,0.080394,0.155994,0.232675,NaN,NaN
m10,0.251014,0.100639,0.060033,0.075323,0.14772,0.224788,NaN,NaN
m11,0.280807,0.126757,0.086462,0.085734,0.173243,0.281315,NaN,NaN
m12,0.290125,0.119147,0.071641,0.077327,0.15428,0.241684,NaN,NaN

Guardamos el ingreso promedio

In [72]:
datasets = [data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12]

for idx, base in enumerate(datasets, start=1):
    df_temp = base.loc[base['ingr_t'] >= 0].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp['ingr_t'] * df_temp['fexp']).sum() / peso_total
    factor = df_temp['fexp'].sum()
    
    # Guardamos los resultados
    row_label = f"m{idx}"
    datos_final_mensual.loc[row_label, ['ingreso_promedio', 'factor']] = [media_ponderada, factor]

In [73]:
datos_final_mensual

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio,factor
m1,0.230628,0.086692,0.049005,0.098639,0.192501,0.289086,260.844049,11028154.785468
m2,0.280151,0.120229,0.07188,0.081765,0.162033,0.251036,170.090497,10996672.876128
m3,0.292068,0.10646,0.058744,0.07944,0.155122,0.234323,171.768947,11296868.238411
m4,0.24399,0.088232,0.049346,0.080652,0.158473,0.239674,202.487037,10812738.52646
m5,0.261268,0.094077,0.052342,0.083378,0.161327,0.245319,178.824037,10922685.498927
m6,0.239625,0.093825,0.053182,0.071277,0.140347,0.212617,179.625202,11576701.052341
m7,0.216916,0.076806,0.040987,0.07014,0.136684,0.20542,181.975601,10911389.524076
m8,0.252498,0.104427,0.062918,0.074942,0.148401,0.229301,171.901541,11288347.916171
m9,0.230482,0.082252,0.044319,0.080394,0.155994,0.232675,201.054782,11388777.102407
m10,0.251014,0.100639,0.060033,0.075323,0.14772,0.224788,172.716908,11644219.873581
m11,0.280807,0.126757,0.086462,0.085734,0.173243,0.281315,171.782192,11467209.08447
m12,0.290125,0.119147,0.071641,0.077327,0.15428,0.241684,169.353988,11272294.412433

### Con los índices calculados de forma trimestral calculamos un índice promedio trimestral ponderado por la suma de los factores en el mes

In [74]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [75]:
valuores = ['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio']
trimestres = {
    't1': ['m1', 'm2', 'm3'],
    't2': ['m4', 'm5', 'm6'], 
    't3': ['m7', 'm8', 'm9'],
    't4': ['m10', 'm11', 'm12']
}

for trimestre, mes in trimestres.items():
    datos_trimestre = datos_final_mensual.loc[mes]
    weights = datos_trimestre['factor']
    
    # Calcula promedio ponderado
    weighted_avgs = (datos_trimestre[valuores].multiply(weights, axis=0)).sum() / weights.sum()
    datos_final.loc[trimestre, valuores] = weighted_avgs

In [76]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.267801,0.104461,0.059856,0.086561,0.169774,0.257963,200.695346
t2,0.248138,0.092092,0.051661,0.078288,0.15311,0.232122,186.783201
t3,0.233474,0.087935,0.049487,0.075231,0.147169,0.222687,185.059067
t4,0.273773,0.115417,0.072653,0.079452,0.158383,0.249179,171.30268

### Inserta los cálculos en la base final

In [77]:
indices = pd.read_csv("indices.csv", encoding='latin-1')

In [78]:
ano = 2024
# Asegurar que el índice de datos_final coincide con trimestres 1..4
datos_final = datos_final.copy()
datos_final["trimestre"] = [1, 2, 3, 4]
datos_final["Año"] = ano

# Reemplazar en indices usando mask
for col in ["fgt0","fgt1","fgt2","a25","a50","a75","ingreso_promedio"]:
    indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

C:\Users\oscarj\AppData\Local\Temp\ipykernel_26552\378464659.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.26780084758291844 0.24813841157221453 0.2334738208012804
 0.27377250596236596]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_26552\378464659.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.10446132674286221 0.09209215154281747 0.08793538475686316
 0.11541723832631519]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_26552\378464659.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.05985596853448196 0.051661357206563556 0.04948693686953923
 0.07265276271144477]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_26552\378464659.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.08656143244195533 0.07828792767792325 0.07523072756062807
 0.07945205256670715]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_26552\378464659.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.16977369151021277 0.1531098378201795 0.14716898721437305
 0.15838279959420964]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_26552\378464659.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.25796287455335914 0.2321219687659583 0.22268694227347682
 0.24917921967587095]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
C:\Users\oscarj\AppData\Local\Temp\ipykernel_26552\378464659.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[200.69534564948074 186.78320139286987 185.0590670158766
 171.30268021705535]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

In [79]:
indices.to_csv('indices.csv', encoding='latin-1', index=None)